### ISSUE TITLE
Visible text content definition is subjective [2ee8b8]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1002]
The definition of "visible text content" relies on the WCAG definition of "non-text content", which is subjective. The ACT Rules Format does not permit the use of this in the applicability of a rule.

**Comment by jkodu** [comment]
As per updates on the PR #452, we have removed all references to `visible-text-content` & the related definition is deleted - https://github.com/act-rules/act-rules.github.io/pull/452/files#diff-03f51e8d5a28ed9b94154017fbb0760c
