### ISSUE TITLE
"iframe elements with identical accessible names have equivalent purpose" required by WCAG 2.1 .4.1.2 (4b1c6c)?

### ISSUE THREAD

**Issue by patrickhlauke** [act-rules/act-rules.github.io#1008]
Looking at [`iframe` elements with identical accessible names have equivalent purpose](https://act-rules.github.io/rules/4b1c6c) and [Understanding Success Criterion 4.1.2: Name, Role, Value](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html), it seems to me that this requirement on the name is something that's not actually present in the normative nor the non-normative text of WCAG 2.1 4.1.2. 

While I agree that exposing a correct/appropriate `role` is, while not explicit, strongly implied and logical when reading 4.1.2, my reading when it comes to `name` is that, essentially, an interface component just needs to expose *a* name. There's no mention about it needing to be unique, descriptive, to make sense in/out of context, or anything else. And while it makes sense to suggest that only things with the same name/content/purpose have the same name, I'm not quite sure if this is a normative requirement for 4.1.2, rather than just a best practice / common sense suggestion.

**Comment by Jym77** [comment]
I think there are two concerns here. My answers:
1. Does 4.1.2 require the name to be descriptive?
Not directly (4.1.2 only requires a name), but [technique H64](https://www.w3.org/WAI/WCAG21/Techniques/html/H64) says: "Check that the title attribute contains text that identifies the frame." This rule is based also on H64.
2. Can identical name accurately describe different content?
Yes. This has been discussed in #968. The conclusion was to add the assumption that is currently in the rule.

I think these are the reasons why we believe that this rule is a check for 4.1.2. The assumption is a known caveat.

**Comment by patrickhlauke** [comment]
> technique H64 says

this, to me, seems an imperfect/incorrect technique then which goes beyond what is normatively required by the SC (and even beyond what is then clarified in the SC's understanding). i guess this will have to be raised in WCAG as a related but separate issue

**Comment by patrickhlauke** [comment]
reading through responses so far on https://github.com/w3c/wcag/issues/929 it seems that 4.1.2 does not place any additional requirements on the accessible name other than the fact that interface components need one. whether it's then descriptive/appropriate is irrelevant in light of 4.1.2
