### ISSUE TITLE
"Language of parts" and failure when ancestors/document itself lack language definition

### ISSUE THREAD

**Issue by patrickhlauke** [act-rules/act-rules.github.io#1009]
Looking over [Element within body has valid lang attribute](https://act-rules.github.io/rules/de46e4), it seems to only apply to elements with an actual `lang` attribute present.

Just to gauge initial thoughts: assuming a page lacks a `lang` attribute altogether (i.e. fails 3.1.1 Language of Page), elements in the body without a `lang` attribute also fail 3.1.2 automatically (since if the human language of the overall page was not set, THEIR human language also cannot be programmatically determined). So, I'd argue, in the below, the `<p>` would fail as well:

```
<html>
  <body>
    <p></p>
  </body>
</html>
```

Is it worth me making an attempt at defining this as a new rule?

**Comment by patrickhlauke** [comment]
In essence, you'd want to go through every node in the `<body>`, and for each determine if it, or any of its ancestors all the way up to `<html>` have some defined and valid human language definition (wondering if there's even a property on the node itself that can provide this, without the need to climb down the whole DOM tree)

**Comment by Jym77** [comment]
Yes, this rule only check that **if** you use a `lang` attribute, it is valid. The rule does not check whether a `lang` attribute` is needed or not. Like many (all?) rules, it is only a partial check for its SC: you can pass the rule and still fail the SC.

I agree that the `p` in your example fails the SC. It is inapplicable for the rule (there is no `lang` attribute).

You are, of course, welcome to try and write a new rule to check whether a `lang` attribute is needed in the first place 😄 Be aware that the review process can be very lengthy and time consuming (for the author also). But if the rule looks good you might also find people willing to help for the final polishing…

An issue I see with the current crude formulation is that if a page has no `lang` attribute at all, you're going to flag every single element as a failure. For page with thousands of elements, that is going to be a lot of failures. This might not be a real issue for tools, but tools users might be drowned in thousands of errors when it's just the page needing a `lang` attribute (and worse case, somebody would believe that every single element needs a `lang` attribute).

A better middle ground might be to target specific elements where it make sense to have a `lang` attribute (typically, landmarks). <= this is a personal opinion only.

**Comment by patrickhlauke** [comment]
> For page with thousands of elements, that is going to be a lot of failures.

agreed, this would definitely result in a large number of failures, unless it can then be simplified/unified somehow in the reporting part (in some kind of programmatic way) to the highest nodes possible in the DOM tree...for instance, if you imagine the example code above, if the `<body>` contained another few thousand nodes, but none of them had a `lang` defined, you could fail it once for "`<body>` and all its content" or something...

anyway, i'll give this a short soon (as I only just joined the CG, i'm still trying to get my head around the processes here etc)

**Comment by crazybat** [comment]
Hello all. Funny, as I was just talking with @WilcoFiers about this this morning. 

I've seen examples of this with The Federal Government of Canada pages, for example. As Canada has 2 official languages: English and French, there's always instances of Language as a whole (3.1.1) and Language of the parts (3.1.2) - at a minimum, there's always a language flipper on every page.

(Personal opinion), I always thought that defining the language in the `<html>` element (not the `<body>`) for the whole page and defining the language of parts, when needed in whatever applicable element, makes sense.

Like @patrickhlauke, I'm fairly new here too and figuring out the process. Open and honest feedback appreciated!

**Comment by patrickhlauke** [comment]
>  I always thought that defining the language in the <html> element (not the <body>) for the whole page and defining the language of parts, when needed in whatever applicable element, makes sense.

and that's still the case. what i'm suggesting here as a missing rule is one that covers the failure state where language of any element/node can't be programmatically determined at all because neither it, nor any of its ancestors up the DOM tree, has a programmatically defined language.

**Comment by crazybat** [comment]
> > I always thought that defining the language in the  element (not the ) for the whole page and defining the language of parts, when needed in whatever applicable element, makes sense.
> 
> and that's still the case. what i'm suggesting here as a missing rule is one that covers the failure state where language of any element/node can't be programmatically determined at all because neither it, nor any of its ancestors up the DOM tree, has a programmatically defined language.

Okay, makes sense. So, it would be checks for:

- look for lang attribute in <html>. If none, fail. If so, passes language as a whole.
- if there's a lang attribute present in any other child elements within the DOM, then a check is needed for that specific element. I would think that this lang attribute should be different from the parent lang attribute, or something like this...

**Comment by Jym77** [comment]
@patrickhlauke @crazybat welcome to the CG!

You can try to team up for writing the rule, it can ease things. If you need to coordinate further, the ACT rules slack can let you do calls (sometimes talking is easier than writing), although without screen sharing.

Make sure to start with the [rule template](https://github.com/act-rules/act-rules.github.io/blob/develop/pages/design/atomic-template-empty.md) (this looks like it will be an atomic rule).

If you need help with git/github (creating branch and pull request), let me know.

Rule writing is not easy. As the saying goes, the devil is in the details and the rule needs to cater to as many corner cases as possible. You'll get (a lot) of feedback when reviews start, so don't worry the rule will be polished 😄 Don't get scared once you start getting feedback if it sometimes looks harsh. There's a lot happening in the repository and people tend to write short answers (which can easily be misinterpreted as harsh).

---
Looking at the discussion going on here, I'll advice to start with something simple and maybe write another rule later. This will give you a good idea of the rule writing process…

One notable point on @crazybat latest proposal (https://github.com/act-rules/act-rules.github.io/issues/1009#issuecomment-550438170): the rule needs to have a set of test target and give an outcome for each test target. If you want to look both at a global `lang` attribute and at individual ones, what would be the test target(s)? If it's the whole page, there will only be one outcome. If each element is a test target, you need an outcome per element, no matter what.

Also, testing that the local `lang` attribute is different from the "parent" one seems to be a completely different rule. Try to keep concern as separate as possible and have rules focus on one simple thing.
(and it is also not clear that adding `lang="en"` to every single element will fail WCAG 3.1.2, so there would not be a fail-on-fail relation with a WCAG SC…)

---
Grouping results in the reporting (https://github.com/act-rules/act-rules.github.io/issues/1009#issuecomment-550401224) is obviously possible. This will not be part of the implementation _per se_ (the implementation must give correct results for every single test target), but it can be done in tools that are built on top of these implementations. At the same time, having a rule that has thousands of outcomes is completely possible within ACT rules…

**Comment by crazybat** [comment]
Thanks @Jym77. I'm up for giving this a go. This sound good @patrickhlauke ?

Any advice on branching / pull requests would help, thank you. I currently use Github Desktop as it seems straight forward enough.

Also, I prefer to have my feedback blunt and direct. In the end, I would want to make sure the rule meets the proper expectations. No feeling are being hurt here :)

**Comment by Jym77** [comment]
From Github desktop, you should be able to (disclaimer: I'm not using it):
- clone the 'develop' branch of the repository;
- create a new branch for your change (try giving it a short but meaningful name);
- make changes and commit them into your branch;
- push the branch back into the repository.

Then, from Github interface (maybe also from Github Desktop), you can create a Pull Request proposing to merge your branch into develop. Prefix your PR name by "[WiP]" as long at it's work in progress. Once you feel ready to face the fire, remove the "[WiP]" prefix and add a "reviewers wanted" label.

The develop branch is strongly protected, so don't worry you shouldn't be able to accidentally break anything. Your branch is your playground, you can do whatever you want.

Several tests are run on the rules and you'll likely see red light in the PR screen. Don't worry about that, we'll help you fix them in time.

From the PR screen, you can also request reviews from specific persons. Don't hesitate to request some from me even while the rule is still WiP. Getting early feedback can avoid wasting time.

**Comment by patrickhlauke** [comment]
@crazybat happy to take an initial crack at it once i find a moment, unless you're super-keen to get a head-start.

**Comment by crazybat** [comment]
> @crazybat happy to take an initial crack at it once i find a moment, unless you're super-keen to get a head-start.

Sounds good. It'll help for me to get more familiar with the writing / submitting process, as well as give feedback, suggestions, etc. Appreciated :)

**Comment by WilcoFiers** [comment]
@patrickhlauke I never thought of SC 3.1.2, but I can see your point. I'd be in favour of a rule like that.

**Comment by patrickhlauke** [comment]
@crazybat et al ... made a first stab here https://github.com/act-rules/act-rules.github.io/pull/1027

**Comment by jkodu** [comment]
@patrickhlauke Yes, once a PR is opened that fully tackles a given issue, please close the issue & further conversations are had in the PR. Ta.
