### ISSUE TITLE
Rule 8 "Focusable element has no keyboard trap" (80af7b) uses single character key to ESC

### ISSUE THREAD

**Issue by detlevhfischer** [act-rules/act-rules.github.io#1012]
The rule has trapped examples where pressing a key escapes the trap (Press the M-key to Exit). You may want to update that to something like "Press STR-M to Exit" (or even use ESC key?)  for it to be in clearly line with SC 21.4 (although use ot as single character key may fall under the exception "Active only on focus" - haven't rendered the examples to work that out)

**Comment by WilcoFiers** [comment]
@detlevhfischer Good suggestion. I think changing this from just "M" to maybe "shift + M" would be best. Changing this to "ESC" wouldn't work for this, those test cases are specifically there to show that a non-standard escape mechanism can still be used to pass the rule, as long as there is an instruction that explains it.

**Comment by detlevhfischer** [comment]
I would have thought that SHIFT+M would not qualify as modifier key according to 2.1.4 Character key Shortcuts - it prints a capital M. Mentioned are "e.g. Ctrl, Alt, etc" - so one of those might be better?

**Comment by WilcoFiers** [comment]
Good point.
