### ISSUE TITLE
Do rules having language as input aspect need a way to tell the actual language?

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1015]
In #671, we decided to add "language" as input aspect for rules that have to deal with meaning. I tried to do that in #996. As part of that PR, I added an assumption to the rules, stating that the programatically determined language (or the `lang` attribute) is correctly set. @WilcoFiers is challenging the need for that assumption, arguing that none of these rules is mentioning a programatically determined language: see https://github.com/act-rules/act-rules.github.io/pull/996#discussion_r338968260 and the following discussion.

We had an inconclusive discussion with @WilcoFiers and @kasperisager and need further input…

---
@WilcoFiers's argument, as far as I can tell (please correct me if needed), is that if the tester of a rule has the ability to understand language (which is what the input aspect mean), then it can figure out the language of the page or part on its own. 

This is supported by [ACT rules common input aspects: Language](https://w3c.github.io/wcag-act/NOTE-act-rules-common-aspects.html#input-aspects-text) stating:
> The means by which the language is assessed, whether by a person or a machine, is not of importance as long as the assessment meets the criteria defined in [Requirements for WCAG 2.0 Checklists and Techniques §humantestable [WCAG]](https://www.w3.org/TR/wcag2-tech-req/#humantestable).

The WCAG requirements themselves stating:
>  The technique can be tested by human inspection and it is believed that at least 80% of knowledgeable human evaluators would agree on the conclusion.

Thus, the common input aspect confirm that we don't (need to) care about programmatic language, and the 80% threshold in the WCAG requirement seems fair enough for "guessing" language, especially as text become more than a couple of carefully crafted sentences.

---
My argument is that there exist sentences that can have (different) meanings in different languages and that a poorly set programmatic language (_e.g._ a CMS defaulting to `lang="en"`) could result in a bad result and, notably, in flagging something as a violation to the wrong success criterion.

Consider this example:
```html
<html lang="fr">
  <h1>Violence</h1>
  <div>Paul put dire comment on tape.</div>
</html>
```
This is passing both "language of the page" and "heading is descriptive" (the `div` is French for "Paul could say how to hit").

Now, consider this example:
```html
<html lang="en">
  <h1>Violence</h1>
  <div>Paul put dire comment on tape.</div>
</html>
```
If the `lang` attribute is correctly set, then the heading is not descriptive. Conversely, if I'm evaluating a rule "heading is descriptive", without any further information, I am going to assume that the page is in English, not in French, and flag this as a failure while it could very well be **passing** heading is descriptive, but failing **language of the page**.

That is, a poorly set programmatic language can lead an evaluator into flagging a false positive for a rule. We want to avoid false positives…

---
Obviously, an example as the one above is completely a corner case built for the sake of argument, but it does exist. Assumptions are often a good way to clean up this kind of corner cases, which is why I felt I need it (supported by https://github.com/act-rules/act-rules.github.io/issues/671#issuecomment-523818574 from the original issue).

What is people opinion? Do rule using language need some sort of assumption on how language is determined in the first place?

**Comment by WilcoFiers** [comment]
Do we have any real world examples of this? Because of not, I don't think we should spend time on it. In my experience, trying to solve problems for which we don't have real world examples isn't a good use of time. It's far too easy to come up with hypothetical edge cases like that.

**Comment by Jym77** [comment]
This happens with CMS automatically setting up `lang="en"`.

And I do think that Assumptions are precisely a way to dismiss known edge cases and limitations.

**Comment by Jym77** [comment]
As a matter of fact, the ACT rule format states under [Assumptions](https://www.w3.org/TR/act-rules-format/#assumptions)
> An ACT Rule _must_ list any known assumptions, limitations or any exceptions for the evaluation, the test environment, technologies being used or the subject being tested.

Given that we do have a known limitation for this, we have to list it one way or another.

**Comment by spanchang** [comment]
Well label text for form controls, alt for images need to be in the primary language of the  document or of language set for a particular section of the page IMO.

**Comment by Jym77** [comment]
#996 updated after CG call of Jan 09, 2020.
