### ISSUE TITLE
Sharing ACT rules with ACT TF after 2 implementations

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1017]
A little while ago we introduced the proposal to start sharing ACT rules with the ACT Task Force as soon as we have 3 independent implementations. The ACT Task Force has since decided that they aren't as concerned with having 3 independent implementations, and have set a minimum of 1, and a strong preference for 2.

It has also proven difficult on our part to get to 3 implementations. We currently have 8 rules at 2 implementations, with 0 rules at 3 (including the page title rule that was approved by AG).

I think until we have more implementors, we should start sharing rules that have 2 independent implementors, and revisit that number as soon as we reach 10 independent implementors. This will let us progress with publishing rules a little faster, and hopefully stimulate implementation as well.

**Comment by jkodu** [comment]
Agreed that 2 implementations is sufficient for sharing to ACT rules (currently).
