### ISSUE TITLE
Faulty logic in applicability of Form field label [cc0f0a]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1022]
> This rule applies to any HTML `label` element or other element referenced by `aria-labelledby` that, is [visible][] and is programmatically associated with an HTML element that has one of the following [semantic roles][]:

This logic doesn't work. For example this would match your applicability:

```html
<div id="foo">Hello</div>
<input aria-describedby="foo" />
<button aria-labelledby="foo"></button>
```

Also, this "other elements" is somewhat ambiguous. I take it this is supposed to mean **any HTML element, including label elements**, but it doesn't say that.

**Comment by Jym77** [comment]
Fixed in #973. Closing.
