### ISSUE TITLE
Examples not living up to assumption (cae760)

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1042]
Rule [`iframe` element has accessible name](https://act-rules.github.io/rules/cae760) is mapping to [SC 4.1.2 Name, Role, Value](https://www.w3.org/TR/WCAG21/#name-role-value). The SC only targets "User Interface Components" and therefore the rule has an assumption that `iframe` are UI components.

However, all the examples in that rule include the same file in their `iframe`: https://github.com/act-rules/act-rules.github.io/blob/develop/test-assets/SC4-1-2-frame-doc.html whose content is
```html
<p>
	My Page!
</p>
```
I'm having a very hard time at swallowing that this is indeed a User Interface Component…

And I don't think we should have examples that do not fulfil the assumption.

**Comment by WilcoFiers** [comment]
That iframe content isn't a user interface component, the iframe is. I'd recommend giving this a read: http://www.davidmacd.com/blog/is-title-attribute-on-iframe-required-by-wcag.html

**Comment by Jym77** [comment]
OK.
Interesting read. Thanks.
