### ISSUE TITLE
Documentation about choosing rule file name in rule design

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#1058]
The rule design page does not document how to arrive at a file name for a rule being authored.

Some history - https://github.com/act-rules/act-rules.github.io/pull/1051/files#diff-9772ff397ce17764837b9ae6f1fd71acR25

**Comment by Jym77** [comment]
This should probably be solved as part of #946

**Comment by jkodu** [comment]
Documentation PR exists - https://github.com/act-rules/act-rules.github.io/pull/946/files#diff-9772ff397ce17764837b9ae6f1fd71acR29
