### ISSUE TITLE
meta viewport does not prevent zoom [b4f0c3]

### ISSUE THREAD

**Issue by patrickhlauke** [act-rules/act-rules.github.io#1060]
Wondering if for https://act-rules.github.io/rules/b4f0c3 it's worth mentioning that this only affects mobile/tablet browsers (as desktop browsers simply ignore viewport meta), and that in most modern browsers the viewport meta that prevents zooming/scaling is ignored (Safari/iOS for the last few years) or that there's a user setting to always allow zoom (Chrome, Firefox, etc on Android).

Additionally, wondering if under assumptions it should also include something about there not being any alternative ways to zoom. For instance, even IF a site tried to block viewport scaling, but provided its own custom text resizing buttons/functionality/setting, it would pass the SC's requirement. Either that, or change the "Any failed outcomes:" to "further testing", rather than an outright "not satisfied".

**Comment by Jym77** [comment]
As per ACT Rules format, there must be a fail-on-fail relationship with the SC (if the rule fails, then the SC must fail; i.e. rules are always flagging actual errors, maybe not all of them).
https://www.w3.org/TR/act-rules-format/#outcome-mapping

If this is not the case, we indeed need to add an assumption to restrict the usage of the rule.

**Comment by WilcoFiers** [comment]
@patrickhlauke I think you're absolutely correct. I think the bit about only certain browsers blocking zoom with meta viewport should got into accessibility supported, and the assumption obviously in the assumptions section. Would you like to put together a pull request with a fix for this?

**Comment by WilcoFiers** [comment]
I've had some testing done for this, and all modern mobile browsers either ignore this, or have a setting which allows users to bypass this. I think the fix is to update the accessibility support note to make it clear this is only really a problem with older mobile browsers.

**Comment by WilcoFiers** [comment]
We're updating the accessibility support of this issue. Discussed on the call whether or not this rule should be deprecated. Group decided against it as there are still use cases for it, even if those are less common.
