### ISSUE TITLE
Applicability for Button has accessible name is not clear. (97a4e1)

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules.github.io#1061]
Applicability is not clear. "The rule applies to elements that are included in the accessibility tree with the semantic role of button, except for input elements of type="image"." It is not clear if this rule applies or does not apply to input elements of type="image". Would be better to state "The rule applies to elements that are included in the accessibility tree with the semantic role of button. This rule does not apply to input elements of type="image"."

**Comment by moekraft** [comment]
Maybe a clarification could be to state, "except where the button element is defined as <input type="image">" or except where the button element is an image button, defined as <input type="image">.

**Comment by moekraft** [comment]
How about clarifying the applicability in the following way: "The rule applies to elements that are included in the accessibility tree with the semantic role of button, except when the button is defined as an input element of type="image"."

**Comment by moekraft** [comment]
An alternate update would read, "The rule applies to elements that are included in the accessibility tree with the semantic role of button, except when an input element's type attribute is in the [Image Button state](https://html.spec.whatwg.org/multipage/input.html#image-button-state-(type=image))."

**Comment by Jym77** [comment]
We must definitely use the "in the Image Button state" formulation, not the `type="image"` one which covers less cases.

**Comment by kasperisager** [comment]
Related: https://github.com/act-rules/act-rules.github.io/issues/584#issuecomment-527828361
