### ISSUE TITLE
Passed example 1 in Button has accessible name should have a clear description

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules.github.io#1062]
Description for Passed Example 1 has "Regular button". Instead this should describe the core mapping that an accessible name is the name of a user interface element. Maybe restate to be "Button element name is accessible."

**Comment by Jym77** [comment]
All examples descriptions are bad in that rule 😞 
We're trying to work on improving examples descriptions, see #834 

I'm closing this issue in the meantime, considering that this is a duplicate of #834. Feel free to reopen if you think the button rule needs specific and immediate attention.
