### ISSUE TITLE
Link to HTML Core Mappings should go to Button section

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules.github.io#1063]
In Rule, Button has accessible name, set link to HTML Core Mappings to button section, https://www.w3.org/TR/html-aam/#input-type-button-input-type-submit-and-input-type-reset

**Comment by Jym77** [comment]
I think the current habit is that links from the Background section go to full documents (hence the link to the HTML-AAM at large).

A more precise link should be added where we mention that the implicit role of a `button` element is `button` (which is currently not done, this rule has bad examples descriptions).

**Comment by jkodu** [comment]
Parent issue https://github.com/w3c/wcag-act/issues/427. Closing this one.
