### ISSUE TITLE
Applicability of Image button has accessible name is confusing (59796f)

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules.github.io#1065]
Applicability is very confusing. "The rule applies to any HTML input element with a type attribute in the Image Button state, that is included in the accessibility tree.

Note: The specification of the type attribute describes in detail how to map the value of the attribute to its corresponding state."

Examples all show input elements with type="image", not sure what you mean by "ype attribute in the Image Button state,"

**Comment by Jym77** [comment]
Having `type="image"` does put the `type` attribute in the "Image button" state:
https://html.spec.whatwg.org/multipage/input.html#attr-input-type

Link to specs can be added for clarity…

**Comment by moekraft** [comment]
A link to https://html.spec.whatwg.org/#image-button-state-(type=image) would be helpful for the reader to understand where this comes from. 
The rule applies to any HTML input element with a type attribute in the [Image Button state](https://html.spec.whatwg.org/#image-button-state-(type=image)), that is included in the accessibility tree.

**Comment by Jym77** [comment]
Closed by #1117.
