### ISSUE TITLE
Inapplicable example 2 is confusing in Image button has accessible name (59796f)

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules.github.io#1066]
Inapplicable Example 2 is confusing in Image button has accessible name.
Similar to applicability, Inapplicable Example 2, is confusing. 

"The input element with type with a type attribute in the Button state is not an image button. Success Criterion 1.1.1 Non-text Content can not fail text buttons. Only non-text content is applicable."

Type is not really a state but rather an attribute. I would simplify to read 

"The input element with type with a type attribute in the Button is not applicable to this rule. The rule [Button has accessible name](https://act-rules.github.io/rules/97a4e1#applicability) applies to Button elements. Success Criterion 1.1.1 Non-text Content can not fail text buttons. Only non-text content is applicable."

**Comment by Jym77** [comment]
`type` is an enumerated attribute and hence is "in a state":
https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#enumerated-attribute
https://html.spec.whatwg.org/multipage/input.html#attr-input-type
https://html.spec.whatwg.org/multipage/input.html#states-of-the-type-attribute
(notably, `type` is case-insensitive and can only be in a finite number of pre-defined states)

So "a `type` attribute in the Button state" is the technically correct formulation. 

I agree that linking to the other rule would improve readability.

**Comment by jkodu** [comment]
Related issue - https://github.com/act-rules/act-rules.github.io/issues/1057
