### ISSUE TITLE
Links to element/attribute/role definitions?

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1071]
In many place, we use constructions such as
- "This `div` element"
- "has a role of `grid`"
- …

Should we link to the specs?
- "This [`div`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element) element"
- "has a role of [`grid`](https://www.w3.org/TR/wai-aria-1.1/#grid)"
-…

**Comment by WilcoFiers** [comment]
I don't think we should do this. We should use definitions when things are ambiguous. I don't think this is. It also creates more overhead to writing rules, and it makes the pages more difficult to navigate for keyboard users.

**Comment by Jym77** [comment]
OK. Closing this.
