### ISSUE TITLE
Shepherding rules to the ACT Task Force

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1076]
Currently I have taken 6 rules to the ACT Task Force. One of them has been approved, for others we have received feedback. But me doing all of this work creates a bottleneck. I was wondering if it might be possible for rule authors to take their rules to the ACT Task Force.

**Comment by EmmaJP** [comment]
After discussion at meeting, suggestion to create an issue in this github associated with the relevant rule and rule authors, which can also be used to track any feedback and subsequent changes.

**Comment by jkodu** [comment]
We have an agenda item to tackle this. Closing issue.

**Comment by jkodu** [comment]
We have an agenda item to tackle this. Closing issue.
