### ISSUE TITLE
Provide further explanation as to why passed iframe tests need further testing (cae760)

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules.github.io#1078]
Rule: iframe element has accessible name

I think you should expand upon or explain why "All passed outcomes: further testing needed."  It makes sense when you see passed example 4, <iframe title=":-)" src="/test-assets/SC4-1-2-frame-doc.html"> </iframe>. You need to validate that the accessible name is meaningful and describes the element. But would be good to state this explicitly maybe in the passed examples.

**Comment by jkodu** [comment]
Similar issue: https://github.com/act-rules/act-rules.github.io/issues/1079

**Comment by jkodu** [comment]
Related PR #1101
