### ISSUE TITLE
Concern with inapplicability for invisible table in test table-headers-attribute-refer-to-data-cells-a25f45

### ISSUE THREAD

**Issue by mraccess77** [act-rules/act-rules.github.io#1080]
Some scrollable tables have visible table header cells in one table but a 2nd set of CSS off-screen positioned table header cells in the scrollable table that visually contains the data cells.  In this case there may be mappings in the visible data cells with headers to the header cells that are marked with off-screen CSS text and we need those associations to be correct.  There are visible header cells that are in a separate table that duplicate these but we can't refer to them.  So there is a good case to test off-screen positioned cells in a table.

**Comment by WilcoFiers** [comment]
This relates to an open pull request. I've linked the two together so that we can resolve it before the PR is merged. Thank you for reporting.

**Comment by jkodu** [comment]
The proposed rule takes this into account. Please take a look & feel free to reopen if there are any concerns
