### ISSUE TITLE
iframe element has accessible name: add examples using role=presentation

### ISSUE THREAD

**Issue by maryjom** [act-rules/act-rules.github.io#1092]
From the ACT TF Survey on the 'iframe element has accessible name' rule Charu brought up the case where role=presentation could produce different test results from different test tools. Role=presentation but not removing the iframe from the tab order should result in a fail condition but role=presentation AND removing the iframe from the tab order should not require an accessible name as it would be ignored both by the AT and would not be navigable.  The rule should be updated to account for these situations. Here are the [survey results](https://www.w3.org/2002/09/wbs/93339/ValidPageLang/results) if you need to look at them and the [ACT TF meeting minutes](https://www.w3.org/2020/01/09-wcag-act-minutes.html#item05) where we discussed this comment.

**Comment by WilcoFiers** [comment]
There's a PR open to resolve this.
