### ISSUE TITLE
Cite source of rabbit video (and other resources?)

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1093]
Many video rules are using the video of a rabbit, seems to be taken from https://www.w3schools.com/html/html5_video.asp itsel/ff coming from https://peach.blender.org/

I think we should cite our source. Probably a global note at the start of the Examples section in the line of "The video used in these examples come from…"

We should also check other sources and give credit accordingly if needed.

**Comment by WilcoFiers** [comment]
That's a good idea. Now that we have an acknowledgement section, perhaps we can put something there?

**Comment by Jym77** [comment]
Acknowledgement section is a good place for that, indeed.
That would require some extra code to handle it, however. @jkodu? 


Other resources I'm thinking of and that we use in example is the "Moon speech" and the "keyboard" video. The Moon speech is already acknowledged in the example themselves ("this is an extract from a Kennedy speech" or similar sentences) but could nonetheless use proper citation.

**Comment by jkodu** [comment]
@jkodu to verify if any key value works in acknowledgements

**Comment by jkodu** [comment]
Verified that any key/value pair can be added to acknowledgments. So these need to be simply added to the frontmatter
