### ISSUE TITLE
Improve examples on lang rules

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1094]
Follow-up to:
* https://github.com/act-rules/act-rules.github.io/pull/1081#discussion_r364341324
bf051a has Failed Example 1 and 3 essentially identical.
* https://github.com/act-rules/act-rules.github.io/pull/1081#discussion_r364344609
5b7ae0 could use an example with mismatching primary tag but matching secondary.

@EmmaJP, you're on it 😉

**Comment by EmmaJP** [comment]
I may wait for #1081 to merge before looking at this

**Comment by Jym77** [comment]
I shipped this with #1082 😁
