### ISSUE TITLE
Similar failed examples in "HTML page language is valid" (bf051a)

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1097]
In [HTML page language is valid](https://act-rules.github.io/rules/bf051a) Failed Examples 1, 3 and 4 are very similar (an invalid primary tag, whether it's "xyz", "123", or "#!").
We probably only need one, maybe two, of them.

**Comment by EmmaJP** [comment]
Perhaps and example that is mis-spelled and an example with invalid characters?

`lang="enn"`
`lang="#2"`

**Comment by Jym77** [comment]
I shipped this with #1082 😁
