### ISSUE TITLE
"**note:**" or "**note**:"?

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1113]
When adding notes, we put the word "note" itself in bold type. But we vary on whether we put the colon in bold or not.
- **Note:**   (colon in bold)
- **Note**:   (colon not in bold).

Majority seems to go for colon in bold:
```shell
$ grep -ri \*\*note:\*\* _rules/ pages/glossary/ | wc -l
100
$ grep -ri \*\*note\*\*: _rules/ pages/glossary/ | wc -l
40
```
I personally prefer colon not in bold, but I'll put all of them in bold soon-ish to unify things. Unless somebody else has something to say in favour of the "colon not in bold" syntax…

**Comment by WilcoFiers** [comment]
I don't think it matters TBH. Unless you're putting in a test to enforce the consistency, I don't think we should bother.

**Comment by Jym77** [comment]
I agree it's not really important, but it's also 5min to put up a sed one-liner… So it may happen on one of my fragmented days…
