### ISSUE TITLE
(Process) closing issues and leveraging github PR analysis

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1122]
Currently, PR template has a "Closes issue(s): XXX" part, and the way we do it is to close the issue as soon as the PR is in place.

I recently discover that github is analysing PR texts and if we write "closes #XXX" in a PR description, Github will automatically link the PR and the issue, and automatically close the issue when the PR is merged.
https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

I suggest that we change our habits (and template) and start using this trick and automation.

Benefits:
- automation. No need to manually close issues and no risk of forgetting to do so. Github does the work for us.
- no closing issues too eagerly. Currently, we may well put a PR in place, thus closing the issue (manually) and the decide to drop the PR (for various reason) and forget to re-open the issue.

Drawbacks:
- need to update a bit the PR template to have the precise format "closes #XXX" (or one of the other keywords).
- need to change a bit our habits.

What do people think about this?

**Comment by jkodu** [comment]
Please update the PR template.
