### ISSUE TITLE
Implementations that don't work can pass the 'Image has accessible name' tests

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1124]
There are no `src` attributes in any of the `img` element test cases. It's possible to create an implementation that  only checks the accessible name when the the `src` attribute is missing. 

An implementation like this would pass all the `img` test cases, but not work in practice.

https://act-rules.github.io/rules/23a2a8

**Comment by dd8** [comment]
The behaviour of `<img/>` is specified in the HTML spec - with not `src` and no `alt` it should be ignored:

> If the src attribute is not set and either the alt attribute is set to the empty string or the alt attribute is not set at all
The element represents nothing

https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element

In Safari it is not exposed in the accessibility tree, but in Firefox it is.

**Comment by WilcoFiers** [comment]
That's a completely valid point. These were some of the earlier rules we wrote. I don't think this would make it in today. But yeah, I agree the rule should look at whether or not there's an src attribute. Would you like to put together a pull request to change this?

**Comment by dd8** [comment]
> That's a completely valid point. These were some of the earlier rules we wrote. I don't think this would make it in today. But yeah, I agree the rule should look at whether or not there's an src attribute. Would you like to put together a pull request to change this?

I'll try to put a PR together - I think it should look like this:

- change the applicability to say 'The rule applies to HTML img elements with a src attribute or any HTML element with the semantic role of img that is included in the accessibility tree.'
- add a `src` attribute to all the existing `img` examples (probably linked to /test-assets/shared/w3c-logo.png)
- create a new `<img/>` Inapplicable Example 

Does that look reasonable?

**Comment by jkodu** [comment]
@dd8 thanks for offering to open a PR for this.

**Comment by kasperisager** [comment]
Do be aware that `<img>` elements without a `src` attribute can still be used as images. Consider this:

```html
<img aria-label="Placeholder image" style="
    width: 100px;
    height: 100px;
    background-image: url(https://picsum.photos/200);
">
```

This will be presented to AT as an image with a name of "Placeholder image".

**Comment by dd8** [comment]
Good point - also need to consider `srcset` and `picture`

```
<img srcset="photo-640x.png 2x">
```

```
<picture>
  <source type="image/svg+xml" srcset="pyramid.svg">
  <source type="image/webp" srcset="pyramid.webp"> 
  <img src="pyramid.png" alt="regular pyramid built from four equilateral triangles">
</picture>
```

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/1208, closing issue.
