### ISSUE TITLE
None of the pass/fail tests for 'Image has accessible name' have non-text content

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1125]
This test maps to 1.1.1 Non-text Content (Level: A). There are two main cases used in the test:

- `img` with no `src` - has no image so can't have non-text content
-  an empty `div role=img` also doesn't have non-text content

There are no tests for the main use case of `img` with `src` and `div role=img` containing content. At best the test cases are testing edge conditions, and in some cases are doing the wrong thing because HTML specifies `img` with no `src` should not be rendered - see  https://github.com/act-rules/act-rules.github.io/issues/1124#issuecomment-578042900

**Comment by dd8** [comment]
@jkodu I've added a PR for this, but can't add a label or assignees because I don't have write access to the report. Can you add the Rule label and assign whoever is appropriate?

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/1208, closing issue.
