### ISSUE TITLE
Heading has accessible name failed example 1 is not a failure

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1126]
```
<h1 aria-label="">ACT rules</h1>
```

https://act-rules.github.io/rules/ffd0e9#failed-example-1

The acc-name calculation ignores an `aria-label` if it's empty or only contain whitespace, so 'ACT rules' is used as the name in this example. Safari, Firefox and Chrome all use 'ACT rules' as the accessible name for this test case.

Here's the step from the acc-name calculation

> Otherwise, if computing a name, and if the current node has an aria-label attribute whose value is not the empty string, nor, when trimmed of white space, is not the empty string:
If traversal of the current node is due to recursion and the current node is an embedded control as defined in step 2E, ignore aria-label and skip to rule 2E.
Otherwise, return the value of aria-label.

https://www.w3.org/TR/accname-1.2/

**Comment by Jym77** [comment]
Good catch 👍. We're already aware of this 😄 
This is fixed in #1116.

If it's OK with you, I'll close this issue once #1116. is merged.

**Comment by dd8** [comment]
> Good catch 👍. We're already aware of this 😄
> This is fixed in #1116.
> 
> If it's OK with you, I'll close this issue once #1116. is merged.

Yep, perfect, thanks
