### ISSUE TITLE
Semantic role definition improvements

### ISSUE THREAD

**Issue by EmmaJP** [act-rules/act-rules.github.io#1129]
https://github.com/act-rules/act-rules.github.io/blob/develop/pages/glossary/semantic-role.md

It may help to be clear that an assigned role should be defined in a suitable taxonomy, such as the WAI-ARIA spec (https://www.w3.org/TR/wai-aria-1.1/#role_definitions), Graphics AAM spec (https://w3c.github.io/graphics-aam/#mapping_role_table) or similar.

See https://github.com/act-rules/act-rules.github.io/pull/1085/files/5e18343309bbe6fbcc998f311131883db60d50a9#r365270117

-------

It is also very confusing that the files relating to these definitions link back to themselves when linking to other definitions. Seeing how they are pulled into rules, it sort of makes sense, but does not always work as expected if all the referenced definitions are not included in a rule because the rule itself does not mention them. This is particularly noticeable with rules that reference semantic role, which in turn references explicit semantic role and implicit semantic role.

**Comment by Jym77** [comment]
> It is also very confusing that the files relating to these definitions link back to themselves when linking to other definitions. Seeing how they are pulled into rules, it sort of makes sense, but does not always work as expected if all the referenced definitions are not included in a rule because the rule itself does not mention them. This is particularly noticeable with rules that reference semantic role, which in turn references explicit semantic role and implicit semantic role.

Inclusion of the definition in the rules should be recursive (i.e. also including definitions that are only used in an included definition, not in the rule itself). If this is not the case, can you open a specific issue for this, pointing to the precise case and assigning @jkodu ?

**Comment by EmmaJP** [comment]
Does it require a separate issue?

**Comment by Jym77** [comment]
Yes, notably because this is a website building problem, not an rule problem. So it's should be an issue in the https://github.com/act-rules/act-rules-web project.

**Comment by WilcoFiers** [comment]
I'm not entirely sure what you mean Emma, but would you like to put together a pull request for this?

**Comment by EmmaJP** [comment]
> Yes, notably because this is a website building problem, not an rule problem. So it's should be an issue in the https://github.com/act-rules/act-rules-web project.

https://github.com/act-rules/act-rules-web/issues/120

**Comment by jkodu** [comment]
Closing issue, as we have a PR in place.
