### ISSUE TITLE
Applicability of  'language is valid' rules doesn't match spec (de46e4)

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1130]
The HTML standard says:

> Its value must be a valid BCP 47 language tag, or the empty string
https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes

BCP-47 says:
>Whitespace is not permitted in a language tag. 
https://tools.ietf.org/html/bcp47#section-2.1

The W3 validator flags `lang=' '`  as an error.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fact-rules.github.io%2Ftestcases%2Fde46e4%2Fe0a8e368d7aba4e94771903d5e994766f6548348.html

The applicability in the lang is valid rules says
>has a lang attribute that is neither empty ("") nor only ASCII whitespace; and

`lang=''` does match spec, but `lang=' '` is not allowed by spec and causes undefined AT behaviour:

```
<html lang='en'>
    <div lang='fr'>
        <p lang=" ">1 2 3 4 5 <code aria-hidden='true'>lang=' '</code></p>
    </div>
</html>
```

* Voiceover macOS 10.15 with Safari 13 - speaks lang=' ' as English
* NVDA 2019.2.1 (eSpeak) with FF68 - speaks lang='' as English
* NVDA 2019.2.1 (eSpeak) with IE11 - speaks lang=' ' as English
* NVDA 2019.2.1 (eSpeak) with Chrome 79 - lang=' ' as French
* JAWS 2019.1912.1 with FF68 - speaks lang=' ' as French
* JAWS 2019.1912.1 with IE11 - speaks lang=' ' as English
* JAWS 2019.1912.1 with Chrome 79 - speaks lang=' ' as French

Test results here:
https://qa.powermapper.com/Tests/ACT-R/primary-ext-lang.html

I suggest changing the applicability both lang valid to:

>has a lang attribute that is neither empty (""); and

and making inapplicable-example-3 a failure:
https://act-rules.github.io/rules/de46e4#inapplicable-example-3

**Comment by WilcoFiers** [comment]
Not matching the spec doesn't matter much, but that some AT switch back to the page default language is definitely an issue, and (to me) rather surprising!

Thank you for the test data. That really helps make a case here. Do you happen to know if the same behaviour occurs with empty `lang` attributes or with `lang` attributes without value? That seems relevant here too.

**Comment by dd8** [comment]
lang='' is defined in the HTML spec as meaning 'unknown language' - in all but 1 one case this is read as the parent language:

* Voiceover macOS 10.15 with Safari 13 - speaks lang='' as parent language (French)
* NVDA 2019.2.1 (eSpeak) with FF68 - speaks lang='' as English (this looks like a FF bug)
* NVDA 2019.2.1 (eSpeak) with IE11 - speaks lang='' as parent language (French),
* NVDA 2019.2.1 (eSpeak) with Chrome 79 - speaks lang='' as parent language (French)
* JAWS 2019.1912.1 with FF68 - speaks lang='' as parent language (French)
* JAWS 2019.1912.1 with IE11 - speaks lang='' as parent language (French)
* JAWS 2019.1912.1 with Chrome 79 - speaks lang='' as parent language (French)

So in terms of behaviour `lang=''` is much more reliable than `lang=' '`

Because whitespace is not allowed in lang browsers/ATs don't expect to see it and may either normalize the whitespace to the empty string or treat it is as anlanguage whose name is a single space (which then gets passed to the speech synthesiser to decide how to handle - this varies depending on the synthesiser)

**Comment by jkodu** [comment]
PR in place. Closing issue. All discussions to be continued in the open PR.
