### ISSUE TITLE
Test that definitions have unambiguous / objective in frontmatter

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1132]
We recently added the `unambiguous` and `objective` properties to the frontmatter of our definitions. We should put tests in place to enforce this going forward.

https://github.com/act-rules/act-rules.github.io/pull/1085/files/

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/1157
