### ISSUE TITLE
meta refresh test case issues

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1141]
https://act-rules.github.io/rules/bc659a

Inapplicable Example 4 causes an instant redirect in Firefox 72 but not in Chrome, Safari or IE11
https://act-rules.github.io/testcases/bc659a/0cf51395718454dabba4bbad975f41fd51f33f4a.html

Inapplicable Example 5 causes an instant redirect in Firefox 72 but not Chrome, Safari or IE11
https://act-rules.github.io/testcases/bc659a/26966d81745c8ab45553c3c305eacba632f4b11f.html

Inapplicable Example 7 causes a redirect after 5 seconds in Firefox 72 but not Chrome, Safari or IE11
https://act-rules.github.io/testcases/bc659a/497149cc71c91862653f8e379134f8c05b2bd8a1.html

Inapplicable Example 8 causes an instant redirect in Firefox 72 but not Chrome, Safari or IE11
https://act-rules.github.io/testcases/bc659a/45e9561106965ddc43f915ede35e4f4b50db0743.html

The differences in parsing means this code goes into an infinite refresh loop in Firefox, but not other browsers:

```
<!DOCTYPE html> 
<meta http-equiv="refresh" content="-0" />
<body>
    <script>
        var now = new Date();
        document.write( now.toTimeString() );
    </script>
</body>
```

**Comment by jkodu** [comment]
@dd8 thanks for the reports on how different browsers work.

I think the right direction is to add accessibility support for this rule & also conduct some tests which can be documented in the wiki

**Comment by dd8** [comment]
I think there's a difficult accessibility supported issue here - if these stay inapplicable then the `<meta http-equiv="refresh" content="-0" ` stays inapplicable.

This example has the potential to trigger seizures in Firefox users, so if these are inapplicable then it's the same as saying "this is conformant, but might kill Firefox users"

**Comment by WilcoFiers** [comment]
These examples were not meant to cause infinite redirects. I think that is the thing that needs to be fixed. Let me work on this.
