### ISSUE TITLE
Rule idea: check that `id` is not empty

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1148]
As suggested in https://github.com/w3c/wcag-act/issues/426

**Comment by dd8** [comment]
ASCII whitespace is also invalid in an ID . It gives problems when you try to reference the ID in an attribute that accepts space separated IDs like `aria-labelledby` and `headers`

**Comment by WilcoFiers** [comment]
Closing, since nobody has picked this up. If someone's still interested, feel free to create the PR. Consider though that AG has not approved the duplicate ID rule, so this isn't likely to get a different response.
