### ISSUE TITLE
Give implementors the option to document their implementation

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1151]
Most tools in the implementors list are running a prerelease version of their tool, sometimes with adjusted defaults. There is currently no way for implementors to communicate this. Providing implementors with a way to document how they came to the results they got will improve transparency, and make it easier for others to verify the results.

I think maybe the best way to do this is to have a markdown file for each implementation, which is put into the top of the implementation page (between the h1 and the implementation tables).

**Comment by jkodu** [comment]
We already have a yaml file where implementation meta data is maintained. See https://github.com/act-rules/act-rules-web/blob/master/implementations.yml

Perhaps we can extend this structure to have one more attrubute:

```
description: | some multiline paragraph
```

This is already parsed into gatsbyjs, and can be easily deciphered and rendered wherever desired.
