### ISSUE TITLE
'audio or video has no audio that plays automatically' failed examples aren't failures

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1160]
'audio or video has no audio that plays automatically' failed examples 1 and and 2 are supposed to autoplay:

https://act-rules.github.io/rules/80f0bf#failed-example-1
https://act-rules.github.io/rules/80f0bf#failed-example-2

https://act-rules.github.io/testcases/80f0bf/104b6e5d9dda4eb31d06dab80f7d8d89c858f151.html
https://act-rules.github.io/testcases/80f0bf/593e65fb0017189463401a5030980c3bc6d5d824.html

Neither example autoplays in Safari, Chrome, Firefox or IE11 so aren't failures.

The W3 validator reports this:

> Bad value true for attribute autoplay on element audio
> `<audio src="/test-assets/moon-audio/moon-speech.mp3" autoplay="true">`

>Bad value true for attribute autoplay on element video.
>`<video autoplay="true">`

**Comment by WilcoFiers** [comment]
Thanks for reporting this Mark!

**Comment by Jym77** [comment]
Nice catch.

Fixed by #1167.
