### ISSUE TITLE
Disabled form field example in "Form control has accessible name" (e086e5)

### ISSUE THREAD

**Issue by kengdoj** [act-rules/act-rules.github.io#1164]
(Creating an issue for survey results)

I don't think disabled form fields require an accessible name.

[Passed Example 2](https://act-rules.github.io/rules/e086e5#passed-example-2):
> Implicit role with aria-label
>`<input` aria-label="last name" disabled />

With disabled set, this does not get keyboard focus and is not operable. A screen reader (NVDA) will announce this as "last name edit unavailable", which is more than a sighted person would perceive since there is no visual label.

If there were no accessible name provided: 
Ex: `<input disabled>` 

NVDA announces "edit unavailable", which is what a sighted person would perceive. 

When there is a visual label and acc name, 
Ex: `Address: <input type="text" aria-label="address" disabled>`

NVDA announces both the label and the acc name: "Address address edit unavailable"

The screen reader announces both the visual label and the acc name, which isn't necessary.

**Comment by kengdoj** [comment]
Additional info:
At Wilco's suggestion, I reviewed NVDA's forms list with disabled forms. I see the benefit of having acc name on a disabled form that has a visual label in a screen reader forms list. 

However, I am not convinced that a disabled form should be required to have an acc name when it has no visual label. How would a tester determine if the acc name describes its purpose? Can the acc name be anything (aria-label="x")?

**Comment by EmmaJP** [comment]
A sighted user is often shown a disabled submit button to indicate that required fields are not yet completed. A disabled input with an accessible name will be announced by a screen reader, which is an equivalent experience.

The example given `Address: <input type="text" aria-label="address" disabled>` is poorly coded. The visible label should be programmatically associated with the input using a `label` element and `for` attribute.

**Comment by WilcoFiers** [comment]
Conclusion: the group things disabled form controls still need a label. Having an adjacent text is insufficient for all cases where disabled form controls can be encountered. We'll add a note to the rule to explain this.

**Comment by Jym77** [comment]
@kengdoj I've added a note to the rule (#1190) to explain why we consider that disabled form fields still need an accessible name.

I will now close this issue because the PR is in place, according to our process. Fell free to reopen it if you think that the note is not sufficient.
