### ISSUE TITLE
Rule afw4f7 - Text has minimum contrast - Passed Example 10

### ISSUE THREAD

**Issue by joao-vicente** [act-rules/act-rules.github.io#1168]
[https://act-rules.github.io/rules/afw4f7#passed-example-10](https://act-rules.github.io/rules/afw4f7#passed-example-10)

Shouldn't the `shadowRoot.textContent` be `shadowRoot.innerHTML`?

**Comment by carlosapaduarte** [comment]
Additionally, there are issues in the descriptions of Inapplicable examples 10 and 11. Both descriptions mention "disabled widgets", but in both examples, there are no widgets but elements with the semantic role of `group`

**Comment by WilcoFiers** [comment]
Issue was resolved a while back. I disagree with the description thing. An input element is a widget. It could be more descriptive though. We'll get to this when this rule is taken to the task force.
