### ISSUE TITLE
Definition of role do not take presentational conflict into account

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1177]
Our current definition of [Semantic role](https://act-rules.github.io/glossary/#semantic-role) is (in short) "explicit if exists, otherwise implicit". This does not take into account the [Presentational Roles Conflict Resolution](https://www.w3.org/TR/wai-aria-1.1/#conflict_resolution_presentation_none).

So for example, an `<img role="presentation" src="" aria-label="foo">` has an explicit role of `presentation` (good), but also has an "ACT semantic role" of `presentation` while the conflict resolution indicate that it must fallback to the implicit role (of `img`) due to the global property `aria-label`.

---
Among other, this has implication for rule [ARIA state or property is permitted](https://act-rules.github.io/rules/5c01ea).
`<h1 role="presentation" aria-level=2 tabindex=1>Hello World!</h1>` has an explicit role of `presentation` and thus an "ACT semantic role" of presentation. This would fail the rule because `aria-level` is not permitted on a role of `presentation`.
But conflict resolution mandates UA to expose this with the implicit role of `heading` because of the `tabindex` (and test indicates that this indeed happens in Chrome, element is exposed if the `tabindex` is here, hidden otherwise). The `aria-level` is permitted on a role of `heading`, so this does not fail the ARIA role model.

---
I haven't checked the other rules using semantic role. I suspect a few, but not many, would be impacted by this.

---
Proposed fix:
- keep the current definition of implicit and explicit roles as they are simple and generally useful.
- update the definition of semantic role to take the conflict resolution into account (or maybe create a new definition if that keeps things simpler).
- need to check every other rule using semantic role to see if it is impacted…

**Comment by WilcoFiers** [comment]
Related:
- https://github.com/FreedomScientific/VFO-standards-support/issues/256
- https://github.com/w3c/aria/issues/1192

This seems like a bit of a minefield to get in to...

**Comment by Jym77** [comment]
I'd say the way to go would be to follow standards (are they are now), with an Accessibility Support note mentioning that not all UA/AT do that.

Given that Chrome seems rather good at implementing the standard (according to the test you link) and that it is by large the most used browser (50-65% apparently), I think we have good reasons to stick with the standard.

**Comment by Jym77** [comment]
@WilcoFiers What about defining the semantic role as whatever role the element has in the accessibility tree (if any)?

* **Pros**: easy, no need to dig into the conflict resolution and choose side, circumvent the whole "If an element with a role of presentation is focusable, **or otherwise interactive**" which would need further definition any way.
* **Cons**: all rules using role will need the accessibility tree as input aspect, not entirely clear what is actually the role of an element, examples will de-facto take side if we want to showcase the conflict resolution.

**Comment by WilcoFiers** [comment]
@Jym77 Seems reasonable, although I'd keep some info in the definition about implicit / explicit roles. Maybe in a note?

**Comment by Jym77** [comment]
Yes, both a note explaining things and an accessibility support will be needed.

**Comment by Jym77** [comment]
Things getting worse: `aria-hidden` seems to be half-ignored by Chrome if the element is focusable.
Make things very hairy for elements who are focusable by default.

So `<a href="#" aria-hidden="true">hidden</a>` **is exposed** in Chrome accessibility tree (with the hidden property set, however) but **is not listed** by NVDA (on top of Chrome).

I'm running some tests and I'll gather results…
A quick grep on our use of `aria-hidden` shows that we shouldn't be too bad on that point because most of the time it's not used on focusable elements (so it will actually be hidden).

**Comment by Jym77** [comment]
https://github.com/act-rules/act-rules.github.io/wiki/Tests-on-Presentational-role-Conflict-resolution

**Comment by spanchang** [comment]
I believe there should be a composite rule that flags failure of a conformance requirement: accessibility-supported ways of using technologies.
ARIA markup that is incongruent with the ARIA specs should be flagged under this rule. It could be  a rule that sort of checks for "well formed" in the context of ARIA.
Issues like "aria-level is not permitted on a role of presentation" should be flagged under this, just like invalid ARIA attribute value or Required ARIA parents role not present.
  The nearest SC if one is required would be SC 4.1.1.  if sort of extends it in the spirit of the Robust principle.

**Comment by Jym77** [comment]
@spanchang two comments on your suggestion:

1. We don't necessarily need to map a rule to a WCAG SC. We do have rules that do not check WCAG failure, but rather usage of ARIA or general best practices ([ARIA state or property is permitted](https://act-rules.github.io/rules/5c01ea) for example maps to section 7.6 of the ARIA specs). So there is no problem with that an no need to "twist" the SC.

---
2. In the case you suggest, each of the atomic rule (ARIA property not allowed, invalid ARIA attribute value, context role missing, …) is enough in itself to fail the accessibility mapping. We usually don't write composite rules in that case.

The reason for that is that the composite rule wouldn't add much in term of detecting errors. The composite rule would fail if one of the atomic rule fails. But the goal of the rules (and the failure) is ultimately to detect accessibility issues. So the composite rule would essentially says "if one of this rules fail, then there is an accessibility issue". This is expressed in a simpler way by having the atomic rules directly say "if I fail, then there is an accessibility issue".

(the situation is much more different with the current composite rules failing if **all** their input rules are failing, in that case, none of the atomic rule alone detects an accessibility issue, and the composite rule is adding some information by saying "if all of these rules fail, then there is an accessibility issue").

Because we cannot have several levels of composite rules, we're much better not adding any that isn't needed…
