### ISSUE TITLE
Update a11y note on acc-name rules

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1185]
There are a few rules with the following note:

> Note: Testing that the accessible name is descriptive is not part of this rule and must be tested separately.

This should be renamed to:

> Note: Testing that the accessible name describes the purpose of the element is not part of this rule and must be tested separately.

This note is used in the following rules:

- 97a4e1
- 7d6734
- e086e5
- cae760
- 23a2a8
- 59796f
- c487ae

**Comment by Jym77** [comment]
Closed by #1216.
