### ISSUE TITLE
Add input aspect to definitions

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1196]
PR #1189 added an input aspect to a number of rules, because one of its definitions was updated. That made me wonder if it would be helpful to include input aspects in the frontmatter of the definition. This would help authors know what input aspects to use in new rules, and it'd give us a way to check no input aspects needed for the definitions were missing from rules.

**Comment by jkodu** [comment]
> Note: it would be nice to have tests for this.

**Comment by Jym77** [comment]
Closed by #1226.
