### ISSUE TITLE
ACT-R Github guidelines

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1199]
Looking for feedback on the following:

## For reviewers

- Submit a review with "changes requested" if any actions are needed from the author
- Submit with "approved" if you agree with the change, unless someone else in your organisation already approved the pull request (1 approval per organisation). This does not prevent you from requesting changes.
- In addition to checking that the change in the pull request is correct, check whether or not the final call period is indicated correctly in the PR description
- Keep your feedback relevant to the pull request. If you have feedback unrelated to the PR, open an issue

## For pull request authors

- Keep changes in the pull request about one topic only.
- When updating your pull request, unless it is editorial, dismiss all reviewers
- Indicate the final call period in the PR description:
  - 2 weeks for a new rule, or for major changes
  - 1 week for smaller changes
  - final call can be skipped for changes that do not change the meaning of the rule and don't change or remove test cases.
- Review your own pull requests before you request changes
- Use the "reviewers wanted" label when the rule is ready for review
- For final calls, add the apprpriate final call label, send an e-mail to the ACT-R mailing list, and remove the "reviewers wanted" label

## For people with write access

- Don't edit or delete other people's posts
- Don't close other people's issues
- Don't update, merge or close other people's pull requests

If any of these need to happen, ask the ACT-R chair instead.

**Comment by dd8** [comment]
I think this needs tweaked since people without write access (like me) can't add labels or assignees to PRs. I think you need some guidance on how to do a PR without write-access

**Comment by daniel-montalvo** [comment]
I am glad to see this coming through. 

I think we need to step back a little bit for this one. We kind of take for granted that people are going to know how to put pull requests, that people are familiar with the review workflow in GitHub (and what it implies).

I think we could try to address a wider audience or, to be more specific, those who are not very familiar with GitHub, even if they may or may not have write access.

**Comment by dd8** [comment]
I think depending on Github PRs discourages people from contributing:

- it's very public if you mess up
- there's a lot you have to get right even if you know git well (remembering to fork, putting the commits in the correct branch, etc)

I use Git every day, and have used source code control systems since the 1980s.  I still put off doing Github PRs for these reasons (and not just on this project).

**Comment by dd8** [comment]
One of the problems with Git is summed up by this joke:

![Commits map to isomorphic contours in source-code phase space (https://www.tartley.com/assets/2010/12/I1546manifold.png)

> It's simplest to think of the state of your [git] repository as a
point in a high-dimensional "code-space", in which branches
are represented as n-dimensional membranes, mapping the
spatial loci of successive commits onto the projected
manifold of each cloned repository.

https://www.tartley.com/a-guide-to-git-using-spatial-analogies

**Comment by jkodu** [comment]
@WilcoFiers what was the decision on this issue during the CG call on 5th March. The minutes have nothing captured.

**Comment by Jym77** [comment]
> Looking for feedback on the following:

Maybe open a PR with some fake-ish file containing that would be easier to gather feedback?

> ## For people with write access
> * Don't close other people's issues

This does conflict with the "close issue when opening PR" guideline that we've been using all along…

**Comment by daniel-montalvo** [comment]
> > Looking for feedback on the following:
> 
> Maybe open a PR with some fake-ish file containing that would be easier to gather feedback?
> 
> > ## For people with write access
> > 
> > * Don't close other people's issues
> 
> This does conflict with the "close issue when opening PR" guideline that we've been using all along…

I don't understand this. The issue would be close only when the pr is merged, right? We use

"Closes issue #xxx." in the PR template.


So what matters heer is if the issue has been solved, rather than who closes it.

I see this advice not to close others issues as a good practice rather than as something compulsory.

**Comment by WilcoFiers** [comment]
Conversation has moved to pull request #1242.
