### ISSUE TITLE
Failed example 1 has accessible name [ffd0e9]

### ISSUE THREAD

**Issue by adilsofficial** [act-rules/act-rules.github.io#1203]
```
<span id="label"></span>
<h1 aria-labelledby="label">ACT rules</h1>
```
https://act-rules.github.io/rules/ffd0e9#failed-example-1

This example actually has accessibile name as the current node `<h1>` is an element with a Text node, return its textual contents: 
here's the G step from accessible name and description computation:
> Otherwise, if the current node is a Text node, return its textual contents.

On the other hand according to [Name and Description](https://www.w3.org/TR/accname-1.1/#mapping_additional_nd) the determinations of content contributes to the names string can be from two possible values i.e. "author" or "contents". As name from "author" value is empty but it still have name from "contents" value.

**Comment by JAWS-test** [comment]
name is empty due to aria-labelledby (see also: https://whatsock.github.io/w3c-alternative-text-computation/Editable%20Live%20Input%20AccName%20Test.html)

**Comment by Jym77** [comment]
It is not that clear.

As per specs, [Step 2.B](https://www.w3.org/TR/accname-1.1/#step2B) is processed first and return the content of the `aria-labelledby` references, no matter if its empty or not.
Note the difference with [Step 2.C](https://www.w3.org/TR/accname-1.1/#step2C) which is explicitly skipped if the `aria-label` is empty. There is no such exception in Step 2.B and the presence of an `aria-labelledby` should result in skipping 2.G (and the rest).

---

As always, browser support is another story…
Chrome does respect that and does not give an accessible name to that heading. Both Edge and Firefox ignore this and do fallback to the text content as accessible name.
NVDA on top of Chrome also defaults to the text content as accessible name in this case…

---

We usually try to stick with the specs and add accessibility support notes instead…

**Comment by Jym77** [comment]
Issue is reported upstsream: https://github.com/w3c/accname/issues/72

**Comment by Jym77** [comment]
Let's add an accessibility support to warn about browsers differences.
