### ISSUE TITLE
Add labels to every input field used as example [73f2c2]

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1215]
As reported by @daniel-montalvo in https://github.com/act-rules/act-rules.github.io/pull/1189#discussion_r388804284 we have several test cases with `input` elements without a corresponding label. This is normally in unrelated rules (e.g., most examples of [`autocomplete` attribute has valid value](https://act-rules.github.io/rules/73f2c2)).

Should we add a label to these?
The absence of a label does not make the (passed) examples fail the SC, but it is still a bad practice…

**Comment by WilcoFiers** [comment]
During the CG call we agreed we're going to ensure all examples with form fields have labels, except if not having one changes the outcome of the example.
