### ISSUE TITLE
Circular reference in the definition of semantic role

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1230]
As pointed out by @WilcoFiers (https://github.com/act-rules/act-rules.github.io/pull/1189#discussion_r390910846) our definition of "semantic role" depends on the definitions of "explicit/implicit role" but both these depends on the definition of "semantic role"…

---
I think this isn’t too much of a problem because the circular reference is technical more than logical. That is, "semantic role" is both the semantic association (a concept) and the actual role of an element (a technical thingie) that are unfortunately named the same way. The dependence goes that way:
* The concept of "semantic role" is defined:
> A semantic role is a semantic association that indicates an object's type. This allows tools to present and support interaction with the object in a manner that is consistent with user expectations about other objects of that type.
* The technical terms "explicit/implicit role" are defined and point to the concept since they are way to flesh it out:
> The explicit semantic role is the semantic role of an element set by its role attribute.
* The technical term "semantic role" is defined, and it points to "explicit/implicit role" as it can be any of these and depends on these terms:
> The semantic role of an element is its explicit semantic role if it has any, otherwise, the implicit semantic role is used.

So, all in all, I think this isn’t too bad. This still needs to be solved and properly unfolded.

---
The less intrusive way I see to solve it is to introduce a definition of "semantic association", or something similar, for the concept. That way "explicit/implicit role" could refer to this. This would not change any of the technical terms, hence not change what we actually use in the rules.

Another way to solve this could be to inline the definition of "explicit/implicit role" inside the definition of "semantic role" (back to what we had last summer, essentially). This would however make it somewhat harder to directly refer to the "explicit/implicit roles", something we now do quite often, so I’d rather avoid that…

---
Thoughts?
I’ll probably try and write a PR for this once #1189 is done (to avoid 2 PRs on roles at the same time…)

**Comment by EmmaJP** [comment]
I don't think its an issue for definitions to reference each other, so long as the unique thing about a definition isn't dependent on the referenced definition. If the definitions for explicit role and implicit role focus on what makes them explicit or implicit, that should help.
