### ISSUE TITLE
2 links different destination same acc name is passing, should discuss [b20e66]

### ISSUE THREAD

**Issue by DavidMacDonald** [act-rules/act-rules.github.io#1248]
2.4.4 requires description of destination. 2 identical ACCNAMES with dif destination is not sufficient description I would say... but its grey, let's discuss.
Links with identical accessible names have equivalent purpose - Passed Example 7

https://www.davidmacd.com/auto-test-files/act-mar17/testcases/b20e66/ffd847275f8d2d4537d7f7346be39a226e33fbea.html
https://act-rules.github.io/rules/b20e66

**Comment by WilcoFiers** [comment]
Hey David. We've talked about it in the CG today. The group seems a little divided on this issue. Not as much about example 7, which most seem to agree should pass the SC, but about the difference between passed example 4 and failed example 2. A number of people in the group seem to think the difference between the two is too small to justify one as a failure and the other as a pass.

One thing that needs to be done here is to improve the examples. A lot of context is missing from the examples, making it difficult to gage. I'm not sure that fully addresses the issue, but that's where we'll start. We'll see how far that gets us.

**Comment by WilcoFiers** [comment]
BTW, looking for someone to pick up this issue. If anyone is interested, feel free to open a pull request.
