### ISSUE TITLE
Autoplaying audio in audio or video rules title

### ISSUE THREAD

**Issue by daniel-montalvo** [act-rules/act-rules.github.io#1258]
Titles for these rules currently ar:

* audio or video has no audio that plays automatically
  * audio or video that plays automatically does not exceed 3 seconds
  * audio or video that plays automatically has a control mechanism

I feel the title of the composite rule does not fit well into the new [rule design guidelines](https://act-rules.github.io/pages/design/rule-design/#rule-name) that we recently approve. We could improve the following:

> * Refer to each applicable thing in a consistent way across rules, especially when related or checking the same applicable thing.

Currently composite and atomic rules refer to 'applicable thing' in a slightly different way.

> * Describe the passing condition, e.g. "id attribute value is unique", rather than "page has no duplicate ids".
  
  Currently the composite rule name is describing what audio does not do rather that what it needs to have.

------

So instead of:

* audio or video has no audio that plays automatically

We would have:

* Composite: Audio and video that plays automatically lasts for less than 3 seconds or has a control mechanism
  * Atomic 1: Audio and video that plays automatically lasts for less than 3 seconds
  * Atomic 2: Would remain the same.

My proposal is to address this in #1249, where I am currently updating the example descriptions, just to keep it simple and have a unique place where we are updating this rule to send it to the Task Force.

-----

On the other hand, we can reasonably argue that these rules are using WCAG language.

Thoughts?

**Comment by Jym77** [comment]
I agree that the names can be improved. Small problem is that it is actually OK (for the rule) to have a video that last longer than 3 seconds **if** there is no audio or even if the audio on it only last 3 seconds. So it's not just about "Audio and video that plays automatically"…

* Composite: Audio or Video that plays automatically has **n audio** lasting more than 3 seconds, or has a control mechanism
  * Atomic: Audio or video that plays automatically has **no audio** lasting more than 3 seconds
  * Atomic: Audio or video that plays automatically has a control mechanism (unchanged)

I guess there's a point of balance between accurate and short names ⚖️

**Comment by daniel-montalvo** [comment]
According to @WilcoFiers  we could have:

> * Video avoids audio that plays for more than 3 seconds.

Based on the discussion in ACT-CG meeting, will think about it and create a separate pull request if we decide to change the title.
