### ISSUE TITLE
Formatting listed conditions

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1275]
We have a couple or rules now that do things like:

> Each element that has:
> - property A, or
> - property B

The formatting of these conditional lists is a little inconsistent. I'd like to discuss normalising these. Here is what I think it should be:

## Proposed format

> Some condition... for which (all | one of) the following is true:
> - (**label 1**:) The (X) has condition A; (and | or)
> - (**label 2**:) The (X) has condition B; ( and | or)
> - (**label 3**:) The (X) has condition C.

This means we'd have adjust these types of conditions to use the following rules:

-  Use phrasing like "for which all the following is true" or "for which one of the following is true"; this creates clarity. This can be modified based on use, such as "to achieve one of the following objectives".
-  Labels are optional, not recommended for lists of 2, and recommended for lists of 4 or more conditions
- The subject must be referenced in some way in each conditional. For example by starting with "the element has", or by using phrasing like "The innerText of the element has...". The subject must be a single word that is referenced in the phrase preceding the conditional list.
- Use "; and" or "; or" at the end of each condition, except the last which ends with a period. This reenforces whether this applies to "all" or "one of"

## Guidance on conditional lists

Additionally, i think we should have the following guidelines for using conditional lists

- If there are more than three conditions, use a list, But keep the most important condition(s) in the phrase, not in the list. Don't do "Each element for which ... - that is a link; and - that is some other thing". Instead do "Each element that is a link, for which ... - some condition". This is to establish what type of element / node / etc is being tested, before limiting it down.

- Put things in order of how common they likely are. Even for unordered lists, this helps understand the list 

- Avoid nested conditional lists. Having one condition and inside that condition becomes difficult to read. Instead try to restructure the conditionals. The can be done by either moving some of the conditional logic into a definition, or by phrasing the conditions as a sentence. In expectations, multiple expectations could also be used.

- Group similar concepts into the same list item. For example, if there is a condition for absolute of fixed position, because they are closely related they could be part of the same condition item.

**Comment by Jym77** [comment]
Yes, I think this is a good thing to do. I mostly agree with your proposal.

I would maybe add:
* something about presenting examples in the order of the condition list when it makes sense (e.g. examples 1-3 illustrate the general text, example 4 is about the first condition, examples 5-6 about the second, …) I feel this makes it that much easier to review or read rules and navigate between conditions and examples.
* as much as possible, have examples that pass/fail one condition and only it. This is to illustrate why this precise condition is needed and can't be removed.

OK, this is not really related to the formatting of conditions 🤷 but having a clear formatted list tend to make these problems more blatant…

**Comment by EmmaJP** [comment]
Sounds good. Would be good to update https://act-rules.github.io/pages/design/rule-design so its documented.

**Comment by Jym77** [comment]
> ## Guidance on conditional lists

> * If there are more than three conditions, use a list, But keep the most important condition(s) in the phrase, not in the list. Don't do "Each element for which ... - that is a link; and - that is some other thing". Instead do "Each element that is a link, for which ... - some condition". This is to establish what type of element / node / etc is being tested, before limiting it down.

This does not work as well for "or" lists.
Plus, naming the conditions might make it better to leave the important thing in the first item. Consider the difference between:
(first item inlined):
> This rule apply to each element which has a role of `img` and for which all of the following are true:
> * (**visible:**) the element is visible; and
> * (**accessible name:**) the element has a non-empty accessible name; and
> * (**foo:**) the element is foo.

(first item separated, with explicit label):
> This rule apply to each element for which all of the following are true:
> * (**image:**) the element has a role of `img`; and
> * (**visible:**) the element is visible; and
> * (**accessible name:**) the element has a non-empty accessible name; and
> * (**foo:**) the element is foo.

I feel the bold labels actually make the second case more obvious  that this talk about images. It is fairly easy to skim through the labels and read "image, visible, accessible name, foo" and get a pretty good idea of what this is about.

**Comment by Jym77** [comment]
> ## Proposed format
> > Some condition... for which (all | one of) the following is true:
> > 
> > * (**label 1**:) The (X) has condition A; (and | or)
> > * (**label 2**:) The (X) has condition B; ( and | or)
> > * (**label 3**:) The (X) has condition C.

Also, typographic nerd mode, but the items shouldn't start with an uppercase letter if the are separated by semi-colon + and/or. 🤓
