### ISSUE TITLE
Element with `role` attribute has required states and properties (4e8ab6): Make combobox examples correct

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1282]
Many examples in [Element with `role` attribute has required states and properties](https://act-rules.github.io/rules/4e8ab6) are using elements with role of `combobox` but alone in the void.

These examples should probably be updated to show good practice of building `combobox`:
* at the very least adding the required `textbox` and likely also the `listbox` popup when relevant;
* avoid `aria-control` referencing to a non-existing ID.

**Comment by WilcoFiers** [comment]
I think we should talk about if we want to support all versions of ARIA, or if we want to fail when the latest version of ARIA is not used correctly.

**Comment by Jym77** [comment]
This was closed by #1884
