### ISSUE TITLE
Error message describes invalid form field value (36b590): Undefined behaviour for form fields without error indicators

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#1298]
Each of the three expectations start with "For each test target with a form field error indicator, [...]" which made me realise during implementation of the rule that it's not currently defined what to do about the test targets that _don't_ have a form field error indicator. I therefore had to assume that they should simply pass.

In hindsight, it also seems a little odd to have the rule be applicable to form fields without error indicators, but that's currently an unfortunate consequence of not having an objective definition of what an error indicator is.

Summoning @carlosapaduarte, @joao-vicente, and @WilcoFiers.

**Comment by WilcoFiers** [comment]
While I do very much agree, I'm not entirely sure what can be done about it.

**Comment by kasperisager** [comment]
I definitely think something should be done and it might be as simple as changing the expectations to something along the lines of this:

> Each test target either has no form field error indicators, or at least of the form field error indicators [...].

**Comment by carlosapaduarte** [comment]
Following the CG meeting:
- I'll open a PR to address this suggestion
- Wilco will raise in the TF the issue that with the current rule format we cannot include something as "form field error indicator" in the applicability (this also impacts other rules)
