### ISSUE TITLE
Do we need the "reviewer wanted" label?

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1307]
It seems to me that every PR that isn't in final call or draft has the "reviewer wanted" label. We introduced that label to indicate a PR was ready for review. This was before Github supported draft PRs. I think we could possibly get rid of that label and use drafts instead.

**Comment by Jym77** [comment]
Labels are good for filtering. It's easy to filter on "reviewer wanted" to see what need eyes. It's harder to filter on (not draft and not Final Call 1 week and not Final Call 2 weeks).
