### ISSUE TITLE
Presentational Roles Conflict Resolution test cases are inconsistent

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1308]
The form control has accessible name rule has 3 examples that are inconsistent with other examples in the same rule.

1) This is a fail:
`<input role="none" />`
https://act-rules.github.io/rules/e086e5#failed-example-8

2) This is inapplicable but is a synonym for failed example 8:
`<input role="presentation" />`
https://act-rules.github.io/rules/e086e5#inapplicable-example-3 

They should both produce identical results because `role=none` is a synonym for `role=presentation`:
https://www.w3.org/TR/wai-aria-1.1/#none

3) This example should be a fail if role conflict resolution is used because the control is focusable and interactive so role=none is ignored:
```
<select role="none">
	<option value="volvo">Volvo</option>
	<option value="saab">Saab</option>
	<option value="opel">Opel</option>
</select>
```
https://act-rules.github.io/rules/e086e5#inapplicable-example-4

**Comment by Jym77** [comment]
Yes, #1189 added Failed Example 8 and patched Inapplicable example 1 but forgot to patch Inapplicable examples 3 and 4. Good catch.

**Comment by dd8** [comment]
I did a grep for `role=none` and `role=presentation` and it looks like other rules may have similar problems:

https://act-rules.github.io/rules/73f2c2#passed-example-10
https://act-rules.github.io/rules/73f2c2#inapplicable-example-8
https://act-rules.github.io/rules/97a4e1#inapplicable-example-5

**Comment by Jym77** [comment]
Thanks a lot.

Note that `<button role="none" disabled>` is actually good (i.e. has a role of `none`) due to the `disabled` attribute, and this will likely be the easier fix to most of these examples.

**Comment by WilcoFiers** [comment]
Looks like this is getting addressed, no need for an agenda item
