### ISSUE TITLE
Consider extended descriptions

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1314]
Rule descriptions are currently fairly brief. They are basically just a slightly expanded title. This is fine for some rules, but for more complex rules, we often end up putting further explanations into notes. Instead of putting this information into notes, we could use a more elaborate description.

A rule that comes to mind is [ARIA required context role](https://act-rules.github.io/rules/ff89c9), which has 3 notes in applicability and 2 more notes in the expectation.

**Comment by Jym77** [comment]
Longer descriptions might need to be moved out of the frontmatter. Especially if we start putting text in it that requires links (https://github.com/act-rules/act-rules.github.io/pull/1340#discussion_r440123748).

Another place where such notes might be moved is in the background section (https://github.com/act-rules/act-rules.github.io/issues/1305#issuecomment-644622078). I feel this is especially relevant for notes like "the rule doesn't care about [some element] for [some reason]" or "the list of applicable elements is `foo`, `bar`".

**Comment by WilcoFiers** [comment]
This info is put in the background section instead. Closing this issue.
