### ISSUE TITLE
Broken links in Image filename is accessible name for image test cases

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1321]
Many published test cases for 'Image filename is accessible name for image' have broken image links due to a missing '/' before 'test-assets' in the `src` and `srcset` paths:

https://act-rules.github.io/rules/9eb3f6#passed-example-3
https://act-rules.github.io/rules/9eb3f6#passed-example-4
https://act-rules.github.io/rules/9eb3f6#passed-example-5
https://act-rules.github.io/rules/9eb3f6#passed-example-6
https://act-rules.github.io/rules/9eb3f6#failed-example-4
https://act-rules.github.io/rules/9eb3f6#failed-example-5
https://act-rules.github.io/rules/9eb3f6#inapplicable-example-3
https://act-rules.github.io/rules/9eb3f6#inapplicable-example-4

Click on the 'Open in a new tab' link next to each test case to see the problem

**Comment by Jym77** [comment]
Damn!
Good catch. I'll fix it asap.
