### ISSUE TITLE
Zoomed text node is not clipped with CSS overflow (59br37): Is Inapplicable Example 5 right?

### ISSUE THREAD

**Issue by joao-vicente** [act-rules/act-rules.github.io#1326]
In this example, the text node is considered fully hidden, but it does not fit any of the examples presented in here [https://act-rules.github.io/rules/59br37#examples-for-visible](url).

**Comment by kasperisager** [comment]
The list of examples of how to make things invisible is by no means exhaustive. Looking at the test case:

```html
<style>
	@media screen and (max-width: 640px) {
		.mobile-hidden {
			position: absolute;
			width: 1px;
			height: 1px;
			overflow: hidden;
			font-size: 16px;
		}
	}
</style>
<a href="/"> Next<span class="mobile-hidden">: Web Content Accessibility Guidelines 2.1</span> </a>
```

What happens is that the `<span>` element is collapsed to a single, transparent pixel when the screen size is equal to or less than 640 pixels. That doesn't qualify as visible as making that pixel fully transparent will have no effect on the rendered pixels as it _already is_ fully transparent.

**Comment by carlosapaduarte** [comment]
@kasperisager I must be missing something obvious, but why is the pixel transparent?

**Comment by kasperisager** [comment]
With the default word wrapping, what the text ends up looking like by reducing the width of the `<span>` element to a single pixel is this:

<img src="https://user-images.githubusercontent.com/1174718/83505962-cf806700-a4c6-11ea-8744-dfe19b2c7592.png" width=67>

I've increased the width slightly to help visualise what the text looks like. Looking at this, it should be evident that there's nothing rendered in the upper right corner of the `<span>` element, as visualised here:

<img src="https://user-images.githubusercontent.com/1174718/83506404-6ea55e80-a4c7-11ea-8273-e4285a8f5876.png" width=67>

**Comment by kasperisager** [comment]
I should add that without also reducing the height to a single pixel, the `<span>` element would actually be considered visible as the left most pixels of the letters then show:

<img src="https://user-images.githubusercontent.com/1174718/83506731-d65ba980-a4c7-11ea-948b-9035d68be490.png" width=42>
