### ISSUE TITLE
"valid" language (sub)tag is not a good term [de46e4, bf051a, 5b7ae0]

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1330]
The language rules use the term "valid language subtag" from our glossary (https://act-rules.github.io/glossary/#valid-language-subtag).

The word "valid" is not really correct here as the definition doesn't really check that the subtag is valid.

This is made even worse by #1328 which changes it to "valid language tag" but the definition only sets conditions on the primary **sub**tag.

**Comment by WilcoFiers** [comment]
I disagree that this definition only has requirements on the primary language subtag. It requires a language tag from which a known primary language subtag can be derived. For example `lang="english"` is not a valid language tag, even though it starts with "en" which is a primary language subtag. 

The "valid language tag" definition has three requirements:
1. The first few characters must follow the format of a primary language subtag
2. Either comes after the primary language subtag, or it must be followed by a dash (`-`)
3. The primary language subtag must be in the registry.

The second requirement makes this not just about the primary language subtag, but about the language tag as a whole. It's a small requirement, but a requirement nonetheless. 

I agree that the word "valid" could be misunderstood to mean "following the BCP47 syntax", but isn't what it means here. The definition explicitly states that this is not the case. I've looked for alternatives, but I didn't find any that didn't cause other issues. In my opinion this is a fairly minor issue.

**Comment by Jym77** [comment]
"english" does not start with a valid primary language subtag because the definition (in BCP 47: https://tools.ietf.org/html/bcp47#section-2.2) is that "subtags" are separated by hyphen. So, in `lang="english"`, the first subtag is "english" and this is not in the language subtag registry.

Then our definition tries to ignore the BCP definition and thus has to rephrase the need for hyphen as subtag separator… 🙄 But at the same time we do link "primary language subtag" to BCP 47 which is then defined as "the first subtag" and thus has to include everything until an hyphen is met making the end of the definition a bit weird…

Maybe
> A language tag is _valid_ if its primary language subtag is from the language subtag registry

would make the definition itself cleaner (not solving the fact that "valid" is not a perfect word).


As for the name, maybe "acceptable language tag" or "adequate language tag" or "suitable language tag" would carry the information that this is not really correct as per language tags specs, but good enough in practice (i.e. accepted by CSS).

**Comment by WilcoFiers** [comment]
I like this suggestion:
> A language tag is valid if its primary language subtag is from the language subtag registry
