### ISSUE TITLE
Dealing with differing font size computations

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#135]
So... `font-size`. We rely on it for contrast computation, which is very well defined, but perhaps unbeknownst to many of us, `font-size` is quite a trickster. My primary concern, though there are plenty of others, is the reliance on `font-family` for inferring the base size of a given font. Consider the following example:

```css
pre {
  font-size: medium;
  font-family: Menlo, monospace;
}
```

```html
<pre>Hello world</pre>
```

What will the computed font size of the `<pre>` be? With default user preferences, `medium` will result in a `font-size` of 16px for non-generic fonts.  If we're in Chrome on macOS, we'll have access to the Menlo typeface and will therefore see "Hello world" rendered in Menlo at 16px. 

If, however, we're using Chrome on an OS where Menlo is not available, or had an external font been used instead and the service hosting the font been unavailable, or had one of many other interesting situations occurred in which Chrome had fallen back to the generic `monospace` font, we'd have seen "Hello world" rendered in whatever generic monospaced font Chrome had chosen at _13px_. Coupled with the cascade, the difference in computed `font-size` can vary quite a bit depending on the used `font-family`, which in turn will impact how our test tools perceive color contrast.

At @Siteimprove, we deal with issues like this quite often due to the way our tool and presentation of results work. We run our accessibility engine in Chrome on Linux on our end, and when we present results to users, we run our engine again in whatever browser and operating system the user happens to be using and do a cross-reference between their results and ours. We're therefore very susceptible to e.g. differences in computed `font-size` even within our own tool, and I have no doubt that this type of issue will be very visible once different vendors start adopting the same set of standardised accessibility rules.

I'd therefore strongly suggest that we take a hard look at how to deal with this. For `font-size` computation, it might mean agreeing on which specific typefaces should be considered and which should be ignored. 

Thoughts and comments? I'll go ahead and mention you, @WilcoFiers, as I'm fairly certain you'll have an opinion on this 😄

**Comment by kasperisager** [comment]
Any thoughts on this at all? I'm working towards an implementation in [Alfa](https://github.com/Siteimprove/alfa/) so feedback would be appreciated!

**Comment by WilcoFiers** [comment]
Related to #571. My understanding is that font size is not relative to the font. At least, not if you use the definition in CSS. There are properties of how a glyph is rendered that impact the legibility of it, like the height of the characters relative to the font size. Mostly that's down to the x-height. This is not something that WCAG takes into consideration, so I don't think we should either.

**Comment by kasperisager** [comment]
Font sizes _can_ however be relative to the font family used, which is the whole point of this issue as I've outlined above. See this article for more a more in-depth explanation: https://manishearth.github.io/blog/2017/08/10/font-size-an-unexpectedly-complex-css-property/.

**Comment by EmmaJP** [comment]
@kasperisager That stuff about the keywords and font-family combinations impacting on calculated font-size is bonkers, but understandable. I guess colour-contrast calculations need to be based on a calculated rendered font-size rather than a value set in the CSS.

**Comment by jkodu** [comment]
Given this is catered for in color-contrast rule, closing this.
@kasperisager feel free to open it if you believe this is a larger discusssion.

**Comment by kasperisager** [comment]
The proposed contrast rule sort of deals with this issue by defining font size in terms of advance height, which if font face specific. As such, it acknowledges that certain font face metrics are specific to each font face, which at least provides transparency into why results might differ between environments.

In summary, I'm fine with closing this.
