### ISSUE TITLE
Font awesome icon has accessible name [c487ae]

### ISSUE THREAD

**Issue by carlosapaduarte** [act-rules/act-rules.github.io#1353]
Font awesome icons insert the unicode of the icon using css (content for :before)

This means that failed example 3 in rule [Link has non-empty accessible name](https://act-rules.github.io/rules/c487ae) should in fact pass.

Firefox gives an accessible name to the link in that example. Chrome does not. We're tending to agree with Firefox on this. What is everyone's else opinion?

**Comment by WilcoFiers** [comment]
Hmmm, fair enough! Not all browsers include pseudo element content. I imagine that's why we have some consistent implementations on this one. I think we just need a different example. Don't think this needs to go on the agenda.

**Comment by carlosapaduarte** [comment]
I'm not sure we need a different example. I seem to remember this was done on purpose to illustrate font awesome. And the rule already has a good coverage of failed examples.
I would be happy just to see it go. I never liked the use of the `i` element for icons, anyway. I can create a PR for this if you want.

**Comment by WilcoFiers** [comment]
Looked at this on the TF call. I think we need to remove this example. It doesn't seem to have an accessible name, but it isn't empty either because of that content property. Can you put together a PR?

**Comment by carlosapaduarte** [comment]
PR #1360 in place
