### ISSUE TITLE
"Heading is descriptive" (b49b2e) What do heading need to describe?

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1361]
This is the latest spin-off from #1311 …

The question about "sections of content" is twofold. One part is the full fledged "what is a section of content?". The other part is "What do we need to do to fix [Heading is descriptive](https://act-rules.github.io/rules/b49b2e)?"

---
SC 2.4.6 (nor its Understanding document) actually does not speaks about "sections of content". It requires headings to "describe topic or purpose" without precising "topic of **what**". Our rule did add the "section of content" as an answer to that question but this is now creating more problems that it solved… (comparatively, 2.4.10 does refer to "sections").

The point here is that in order to fix "Heading is descriptive", which is currently the **only** rule using "section of content", we don't really need to have a full blown up definition of "section of content" that is correct for every single case we can think of. We only need something that patches this very rule. If and when we need a full definition of section of content later, we can evolve the patch or make a full new def.

---
Now, that rule is (and has always been) targeting "elements with a role of `heading` that is either visible or included in the accessibility tree". It is a subset of every thing that WCAG consider as "heading", so the rule is a partial check. Targeting that subset ensures that the applicability is objective and unambiguous without requiring us to have a full fledged definition of "heading" (in the WCAG sense of the term) which we all know will be hard to agree upon…

So, the question becomes: "here's an element with a role of `heading` which is visible or included in the accessibility tree; which part of the page needs to be described by that element?"

I do feel that the suggestion here: https://github.com/act-rules/act-rules.github.io/issues/1311#issuecomment-629989783 is a reasonable answer for that specific question. However, @EmmaJP is making a very good point in https://github.com/act-rules/act-rules.github.io/pull/1293#issuecomment-649504044 that images just before a heading but illustrating the following text are often used, so maybe not so good…

---
I do not think that the "visual cues" approach would work for that specific rule (but it may be good for a more general definition if needed). More details: https://github.com/act-rules/act-rules.github.io/pull/1293#issuecomment-644758580

---
@EmmaJP is also suggesting (https://github.com/act-rules/act-rules.github.io/pull/1293#issuecomment-649504044) to use something like "whatever user perceives as associated to this heading" for this rule. Maybe there is a way to turn that into something workable. This is definitely subjective, which is OK for expectation. I am afraid that it is so subjective that it becomes ambiguous (it's essentially not that different from "a distinctive part of the document" which is our current definition.

---
Of course, it is not clear that the rule must stay the way it is now. The rule can be expanded to handle more than "elements with a role of `heading`" (as suggested by @ajanec01 https://github.com/act-rules/act-rules.github.io/pull/1293#issuecomment-649590561).

The rule might also be split further (I am specifically thinking of having one rule targeting "elements with a role of `heading` that are included in the accessibility tree" and one for "elements with a role of `heading` that are visible" as these might need to describe different things (the first rule would be aimed mostly at AT users, the second at sighted users)).

If these tricks help us solve the issue, they're welcome given how complex this problem has become…

**Comment by ajanec01** [comment]
If the definition is supposed to fit only the elements with the role of heading then a section of content could be changed to something like “programmatically determined section context”.  I base that on the definition of [programmatically determined link context](https://www.w3.org/TR/WCAG21/#dfn-programmatically-determined-link-context). I see an analogy between the two definitions. Link in context also referred to a certain section of a page.

**Comment by Jym77** [comment]
Maybe rewrite as
"The next palpable content element is described by the heading"

"Foo & Bar.   foofoofoofoo (barbarbar)" => OK.
"Foo & Bar.   bazbazbaz (foofoofoo barbarbar)" => KO.
