### ISSUE TITLE
Autocomplete field name needs an appropriate control group (#73f2c2)

### ISSUE THREAD

**Issue by ajanec01** [act-rules/act-rules.github.io#1366]
I've just noticed that the [autocomplete attribute has valid value rule](https://act-rules.github.io/rules/73f2c2) does not mention that the autocomplete field name needs an appropriate control group, i.e. Field name: "bday-day" needs "numeric" control group. 

Do you think it's worth adding a note?

**Comment by WilcoFiers** [comment]
If I understand what you're suggesting, this should be covered by expectation 3. Can you clarify maybe why you think it may not be, or why it may not be clear enough?

**Comment by ajanec01** [comment]
Neither of the definitions in expectation 3 ([correct autocomplete field](https://act-rules.github.io/rules/73f2c2#correct-autocomplete-field), [appropriate autocomplete field](https://act-rules.github.io/rules/73f2c2#appropriate-field-for-the-form-control)) explains that an autocomplete field needs an appropriate control group.  In fact, they both explain the same thing- the value of the autocomplete attribute needs to match any name in the first column of the spec (https://html.spec.whatwg.org/#autofilling-form-controls:-the-autocomplete-attribute:autofill-field-5).

There is no mention that the appropriate field name, in essence, autocomplete attribute value, can go with only a limited number of input types described in the last column of the spec (Control group).

However, there is a clash. The rule does not test for `input` elements with `type="hidden"` and all of the control groups include such `type` in the spec. This would have to be worded appropriately in the rule to make more sense.

**Comment by ajanec01** [comment]
The suggestion is to re-word the definition of [appropriate autocomplete field](https://act-rules.github.io/rules/73f2c2#appropriate-field-for-the-form-control) to say that each autocomplete field name is applicable to input elements with a limited number of states.

**Comment by WilcoFiers** [comment]
Sounds good to me. Would you like to put together a pull request?

**Comment by ajanec01** [comment]
Sure! PR #1387
