### ISSUE TITLE
aria-* attribute is defined in WAI-ARIA - Failed Example 1

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1368]
Both https://validator.w3.org/ and https://validator.nu/ detect mis-spelled aria-* attributes

But they don't report attribute errors when the element containing the attributes is mis-spelled or wrongly nested. 

This is a good thing because it prevents consequent errors which are often misleading, but it means they don't report an ARIA attribute error on Failed Example 1 because they both report
> "Element li not allowed as child of element body in this context. (Suppressing further errors from this subtree.)"

https://act-rules.github.io/rules/5f99a7#failed-example-1

As currently written example 1 prevents this type of error suppression, and neither validator passes this test case

**Comment by Jym77** [comment]
Easy fix: we add a `ul` around the `li`.
