### ISSUE TITLE
Add menuitem and button to form-control-acc-name? [e086e5]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1374]
Question from [@jnurthen](https://github.com/act-rules/act-rules.github.io/pull/1357/files#r450379608):

> I question why menuitemcheckbox and menuitemradio appear here and menuitem does not.

And a related question from myself:

> Fair Similarly I think it's worth asking why this include spinbutton but not button.

It makes logical sense to say a menuitem is not a form control, but a checkbox in a menu is, but is there any particular reason that that rule be limited to form controls, e.g. controls that have a value.

**Comment by WilcoFiers** [comment]
Talked about this in the ACT TF, it might make sense to split the rule into an "input has acc name" and "select has acc name" rule.

**Comment by WilcoFiers** [comment]
CG seems to lean towards writing a generic "widget has non-empty accessible name rule" with a few exceptions for roles that do not need it. Examples such as image buttons will be tested in two rules, one for 4.1.2 and another for 1.1.1.

**Comment by carlosapaduarte** [comment]
Write the "widget has non-empty accessible name" rule, that replaces:
- [Button has non-empty accessible name](https://act-rules.github.io/rules/97a4e1)
- [Form field has non-empty accessible name](https://act-rules.github.io/rules/e086e5)
- [Image button has non-empty accessible name](https://act-rules.github.io/rules/59796f)
- [Link has non-empty accessible name](https://act-rules.github.io/rules/c487ae)
- [Menuitem has non-empty accessible name](https://act-rules.github.io/rules/m6b1q3)

This will also help to streamline the 4.1.2 Understanding Document by having just a single rule checking widgets

**Comment by carlosapaduarte** [comment]
Image button and link rules should not be deprecated because they check other SC also

**Comment by carlosapaduarte** [comment]
Closing as #1790 has been closed
