### ISSUE TITLE
menuitemcheckbox / menuitemradio do not inherit from input in ARIA 1.2 

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1375]
From [@jnurthen](https://github.com/act-rules/act-rules.github.io/pull/1357/files#r450380522)

> w3c/aria#1278 removes the multiple inheritance from menuitemcheckbox and menuitemradio such that this will no longer be true once this appears in a spec.

Content in the background section needs to be updated when we move to WAI-ARIA 1.2.

**Comment by WilcoFiers** [comment]
This was discussed on the ACT TF call. The conclusion there is that the rule "from field has accessible name" is not a good description of what the rule does. The correct title really is "input or select widget has accessible name", which suggests the problem with that particular rule; It combines testing roles that inherit from select, and that inherit from input in the same rule.

Thinking of this a little more systematically. I think once ARIA 1.2 is out, we should revisit the way these requirements are split up. I think the following breakdown makes the most sense:

1. Command widget has non-empty accessible name:
    - button
    - link
    - menuitem

1. Select widget has non-empty accessible name:
    - listbox
    - menu
    - radiogroup
    - tree

1. Input widget has non-empty accessible name:
    - checkbox
    - combobox
    - option
    - radio
    - slider
    - spinbutton
    - textbox

1. Range widget has non-empty accessible name: 
  (This does not include all range, just ones that are also widgets)
    - progressbar
    - scrollbar
    - slider
    - spinbutton

1. Irregular widget has non-empty accessible name:
  (Widgets that do not inherit from command, select, input or range)
    - gridcell
    - row
    - separator
    - tab

**Comment by WilcoFiers** [comment]
For ARIA 1.2 we just need to update the background section to clarify that menuitem is also a role to consider.

**Comment by Jym77** [comment]
This was closed by #1942
