### ISSUE TITLE
overflow: clip is not scrollable

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1388]
ACT Rules defines scrollable elements as those with `overflow-x` or `overflow-y` with `auto`, `clip` or `scroll` computed values:
https://act-rules.github.io/rules/0ssw9k#scrollable-element

CSS defines `clip` as non-scrollable:
https://drafts.csswg.org/css-overflow-3/#propdef-overflow

**Comment by WilcoFiers** [comment]
Fully agree. I'm not sure why that's there. Definitely an oversight.
