### ISSUE TITLE
Scrollable element is keyboard accessible: test cases break if user changes browser default font

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1389]
Some of the test cases only work when the user hasn't changed the browser default font family or font size

Making the font smaller makes some of the failed examples pass (because the content is too small to scroll), making the font bigger makes some passed examples fail.

I think you need a style rule on the `section` element to set `line-height`, `font-size` and `font-family` (and possibly other properties that affect text rendering).

**Comment by dd8** [comment]
There are also cases like this where the fonts used caused failures on Windows, but not Mac (or vice versa). This doesn't have hidden scrolling text on macOS but does on other platforms because Verdana characters are wider than AppleGothic characters,

```
font-family: AppleGothic, Verdana;
```

**Comment by Jym77** [comment]
But, can't user style override any styling?
In which case almost any rule that use CSS can have that overriden and has all its examples broken…

**Comment by carlosapaduarte** [comment]
I don't think @dd8 was addressing user stylesheets, but just changing the default font family and size in the browser settings. To be honest, I haven't checked in all browsers, but I think that does not override inline styles.

**Comment by dd8** [comment]
Yes, it's the user settings - 

In Chrome it's in the Appearance section of the settings page (chrome://settings/)

In Safari on macOS it's even easier to change - just hold down the Option key when zooming:
https://support.apple.com/en-gb/HT207209

In Firefox it's on the Preferences page:
https://support.mozilla.org/en-US/kb/font-size-and-zoom-increase-size-of-web-pages#w_set-a-default-zoom-level-for-all-websites

**Comment by dd8** [comment]
The default font size is implemented as the CSS initial value for the `font-size:` property. Any author CSS stylesheets or style attributes that specify `font-size:` override it unless they specify `font-size: initial`.

**Comment by WilcoFiers** [comment]
We discussed this on the TF last time around. The decision there is that browser default are something content authors should be able to rely on. If the user does something to the font-size that causes issues, that is not something the content author is responsible for. Implementors need to make sure they are running a browser with default settings for testing, since not doing so can cause false positives. Carlos has this issue to resolve this #1445.
