### ISSUE TITLE
Image filename is accessible name for image - problems with examples

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1390]
## Passed Example 5 has a broken link
Missing slash before `test-assets/`
https://act-rules.github.io/rules/9eb3f6#passed-example-5

## Failed Example 5
I've not been able to find a device where this displays the "pain" image - the first media query `min-width: 45em` always evaluates to true:
https://act-rules.github.io/rules/9eb3f6#failed-example-5

If I change the media queries to `px` as in the example below I can get the image to switch between pain and Nyhavn - will display 'pain' on small mobile screens and switch to 'nyhavn' on iPads and laptops:

```
<picture>
		<source media="(min-width: 1000px)" srcset="/test-assets/image-filename-as-accessible-name-9eb3f6/nyhavn">
		<source media="(min-width: 320px)" srcset="/test-assets/image-filename-as-accessible-name-9eb3f6/pain">
		<img src="/test-assets/image-filename-as-accessible-name-9eb3f6/nyhavn.jpeg" alt="Nyhavn">
	</picture>
```

Note: Passed Example 6 uses the same media queries, so is passing for the wrong reason.

**Comment by Jym77** [comment]
Yeah, media queries were a bit random in that rule 😅
