### ISSUE TITLE
Should rules check for the duration of effects that can come into play for passing the rule?

### ISSUE THREAD

**Issue by carlosapaduarte** [act-rules/act-rules.github.io#1394]
@Jym77 and I have been discussing this, prompted by his review of #873, but also directly applicable at least to [Device motion based changes to the content can be disabled](https://act-rules.github.io/rules/c249d5)

Here is a scenario for the published rule:
- The event that reacts to the device motion triggers a `setTimeout(doSomething, XXX)`
- The disable button executes `disable(); setTimeout(enable, YYY)`

A manual check of the rule would proceed like this
- I move the phone and check that there are no changes to the content within 1 minute. 
- If XXX is bigger than 1 minute: the rule passes.
- If XXX is smaller than 1 minute: I detect a change in content, but I found a disable button. Now I want to check what the disable button does. I press disable, move the phone and wait for changes within 1 minute. If YYY is small enough (we’re probably talking about a few seconds here, because that would be the time I’m moving the phone), the “device motion functionality” would be enabled while I was still moving the phone and the rule would fail. Otherwise, it would pass, even though the device motion functionality would be re-enabled in YYY milliseconds (the SC says nothing about how long the event should be disabled).

We would like to have input from the group on what should we do in the situation where YYY is larger than the few seconds that takes me to shake the phone. In particular:
- Do you consider the event was disabled? (because that is what the SC requires - it does not state how long it needs to remain disabled)
- If yes, do we also need to set a time limit to check for re-enabling of the functionality in order to make the rule testable?

**Comment by ajanec01** [comment]
I think there are more arguments to consider that the "device motion functionality" was not disabled. I guess that it could be argued that you can disable or turn off something only temporarily but even if we consider that this rule would pass 2.5.4, which I don't think it would, I would be inclined to fail it under 2.2.1. 

That is based on the assumption that the user can't turn off, adjust, or extend the time left to switching the device motion functionality back on.

**Comment by carlosapaduarte** [comment]
Discussed on CG call today. The decision was to add an assumption that the disabling effect keeps until re-enabling.

**Comment by carlosapaduarte** [comment]
+ open an issue with the AG regarding the definition of disabled

**Comment by carlosapaduarte** [comment]
Issue https://github.com/w3c/wcag/issues/1480 opened
