### ISSUE TITLE
Add a placeholder example to form-controls-acc-name (e086e5)

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1405]
I recently learned that placeholder is now included in the accessible name computation. I think it would be useful to add the following passed example:

```html
<input placeholder="Family name" />
```

(Didn't put it in because this rule is currently being looked at by the ACT TF. Adding it now would invalidate the implementation data.

There is some test data for it here: https://github.com/dequelabs/axe-core/issues/2413 this work in all major browsers.

**Comment by Jym77** [comment]
https://www.w3.org/TR/html-aam-1.0/#input-type-text-input-type-password-input-type-search-input-type-tel-input-type-email-input-type-url-and-textarea-element-accessible-name-computation

So it's actually part of the second layer in the name computation (just like `<button type="submit"></button>` ends up having "Submit" as accessible name), not part of the accessible name computation algorithm.

**Comment by kasperisager** [comment]
@Jym77 It falls under Step 2D of the accessible name computation: https://w3c.github.io/accname/#step2D
