### ISSUE TITLE
Object element has non-empty accessible name - better explanations in failures

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules.github.io#1410]
Please describe the issue with references and relevant examples where necessary.
https://act-rules.github.io/rules/8fc3b6
It would be helpful in Failure examples 1, 2, and 4 to give a further explanation as to why the example fails. 
1. because title is empty
2. because the span element with id="label" is empty
4. because it does not provide an accessible name in it's title, an aria-label or aria-labelledby

--- or ---

If authoring a proposal for a new rule, choose from one of the issue templates:

- [Atomic Rule Template](https://raw.githubusercontent.com/act-rules/act-rules.github.io/develop/pages/design/atomic-template-empty.md)
- [Composite Rule Template](https://raw.githubusercontent.com/act-rules/act-rules.github.io/develop/pages/design/composite-template-empty.md)

**Comment by Jym77** [comment]
@carlosapaduarte I think this is for you (you're sheperding this rule).

**Comment by carlosapaduarte** [comment]
Solved in PR #1441 
Closing this issue
