### ISSUE TITLE
Aria prop has valid value, are existing IDREFs required? [6a7281]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1432]
There's an inconsistency in this rule. The expectation first says that IDREF must reference an existing element, but is immediately followed by a note that says this isn't required.

> For value types ID Reference and ID Reference List for WAI-ARIA required properties at least one of the elements with the given ids exists in the same document tree or shadow tree as the element that specifies the target attribute.
> ...
> Note: Only for WAI-ARIA required properties with value types ID Reference and ID Reference List is there a requirement that the elements with the given ids actually exists. For non-required properties, this is not a requirement.

I think the idea of only making this required if the attribute is required is a reasonable one, but isn't how ARIA is designed. For instance combobox in ARIA 1.2 required aria-controls, regardless of if the popup is visible or not. It seems unreasonable to pass a combobox where the popup is hidden by toggling `display:none` but fail it if it is hidden by injecting and removing the popup from the DOM.

While I think a strict reading of WAI-ARIA suggests referencing non-existent elements isn't allowed, that doesn't seem like the intended behaviour. In my opinion, we should put in an exception for IDREF and IDREFs to exclude them.

**Comment by jeeyyy** [comment]
@WilcoFiers what you mention here makes sense especially with the combobox example.

> `In my opinion, we should put in an exception for IDREF and IDREFs to exclude them`

Are you suggesting that we amend the expectation in such a way that we do not it mandatory for ID(REFS) actually exist?

**Comment by WilcoFiers** [comment]
I think we should not make this required, correct. There are good reasons for IDREFs to point to non-existing elements.

**Comment by ajanec01** [comment]
> ... at least one of the elements with the given ids exists in the same document tree or shadow tree as the element that specifies the target attribute.

On a slightly separate note, I think that the information about referenced `id` values of elements inside a shadow tree needs to be either removed or the accessibility support section needs to be expanded. If we check the [code pen example by Steve Faulkner](https://codepen.io/stevef/pen/Djzga/) then it's clear that relationships based on the `id` values don't work between the DOM and the shadow DOM. 

I don't think there is any value in adding a note to the Accessibility Support section. I think that id relationships between DOM and shadow DOM should be inapplicable, if not a failure.

**Comment by ajanec01** [comment]
Addressed in #1649
