### ISSUE TITLE
Background section in (out?) of definitions

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1472]
Several definitions have a bit which is the technical definition itself, and a bit which is more background notes or explanations as to why he definition is the way it is.
I'm typically thinking of [marked as decorative](https://act-rules.github.io/glossary/#marked-as-decorative) where the actual definition is the bullet list and the next two paragraph are more background and explanation as to why the definition is that way and how it differs from similar concepts.

While I feel these notes are useful, they could benefit from being clearly labelled in a "Background" section or similar (very similar to how we move notes to Background in rules).

Of course, like for Examples, Accessibility Support, Assumptions, … this may clutter the rule pages and we might want to do it in the way summed up in https://github.com/act-rules/act-rules.github.io/issues/1416#issuecomment-698220843: keep the Background section in the Glossary page, but strip it out of the Rule pages.

**Comment by Jym77** [comment]
Proposal, after https://www.w3.org/2020/11/12-act-r-minutes.html#item03

1. Everything in a definition up to the first heading (excluded) is considered to be the definition itself. Everything after the first heading (included) is considered to be extra information.
2. When building the website, extra information will be extracted into a separate page, e.g. `https://act-rules.github.io/pages/extra/definition-key/`. Probably with a link "this is extra information about [definition name]".
3. In the individual rule pages, only the definition itself is included, with a link "for more details about this definition, click here" (or a better name not involving "click here" 😬 )
4. In the Glossary page, either
  a. We do the same thing (link to extra info)
  b. We include everything (to limit number of clicks to get all data)

Extra info would include Background, but also Examples, Accessibility Support, Assumptions, … Thus it would be a generic solution to several problems we've faced recently…

Steps 2, 3, and 4 (whichever variant) need to be implemented upfront and will happen automatically at build time. 

Correctly formatting the individual definition files, moving the "Note:" to Background, … will happen on a per need basis with authors and reviewers handling it whenever a given definition is changed, or submitted to TF as part of a rule. TF may also request cleaning a given def when a linked rule is submitted to them.
Thus, the process should be relatively lightweight upfront and we'll slowly converge to a better state.

Potential problem: it becomes impossible to add sections inside a definition. This seems to not be done for anything else that extra information currently, so it shouldn't be a real issue in the short-to-mid term at least.

**Comment by WilcoFiers** [comment]
For the new website I am removing all the content after the first h2 from the definition in the rules pages. I'm going to need to work on a glossary page, or possibly multiple pages? Will look into this.

**Comment by WilcoFiers** [comment]
This is getting addressed on the W3C website, which removes all content from the first heading of a definition on.
