### ISSUE TITLE
Should applicability start with "this rule applies to"?

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1477]
A minority of our rules start with the phrase "This rule applies to" in the applicability. I think we should either do this everywhere, or do it nowhere, but doing this in some rules but not in others seems a little unnecessary.

**Comment by Jym77** [comment]
Agree on need to unify.
No opinion on which one to choose…

**Comment by EmmaJP** [comment]
https://act-rules.github.io/pages/design/rule-design/#applicability
