### ISSUE TITLE
Add test case with different capitalization in valid language tag rules (de46e4 and bf051a)

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#1499]
I have found a bug in an implementation of the rule "Element with lang attribute has valid language tag" (de46e4) that has to do with the implementation only accepting a certain capitalization in language tags. 
According to the implementation report, this tool had a correct implementation, so I suggest adding a new test case with different capitalization (e.g. lang="EN") to ensure consistency in implementations in this area.

The same applies to the rule "HTML page lang attribute has valid language tag" (bf051a).

**Comment by WilcoFiers** [comment]
@annethyme would you like to submit a pull request for this?
