### ISSUE TITLE
"Zoomed text node is not clipped with CSS overflow" (59br37): computed line-height is not always a length

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1508]
[Expectation of Zoomed text node is not clipped with CSS overflow](https://act-rules.github.io/rules/59br37#expectation) refers to the "computed line-height" and compares it to a length.
However, computed line-height may also be a number or the keyword `normal` and the rule doesn't tell what to do in these case.

We can either change it to "used line-height" (but this is a bit more blurry since it depends on many things) or assume that `normal` is 1.2 (which seems to be a good approximation). Handling numbers is not too hard since it just need to be multiplied by the font size.

**Comment by WilcoFiers** [comment]
Do you want to put together a pull request?

**Comment by Jym77** [comment]
I'll see if I find the time…
