### ISSUE TITLE
"Table header cell has assigned data cells" (d0f69e) should accept header cells

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1512]
[Table header cell has assigned data cells](https://act-rules.github.io/rules/d0f69e) is currently failing a case like https://www.w3.org/WAI/tutorials/tables/irregular/#table-with-headers-spanning-multiple-rows-or-columns which boils down to
```html
<table>
<tr><th scope="col">Foo</th><th scope="col">Bar</th></tr>
<tr><th scope="row">A</th><td>1</td></tr>
<tr><th scope="row">B</th><td>2</td></tr>
</table>
```
In that table, the first column is only **header** cells. So the top-left cell ("Foo" is assigned to only **header** cells and to no **data** cell and thus fails the rule.

[H63](https://www.w3.org/WAI/WCAG21/Techniques/html/H63) which is sufficient for the accessibility requirement of this rule (1.3.1) also has a similar example (the second column has only header cells).

Given that WCAG technique and WAI tutorials are giving examples like that, I guess we shouldn't fail this…

**Comment by WilcoFiers** [comment]
I think you're right. We just need to add rowheader and columnheader as possible roles. Would you like to submit a PR?
