### ISSUE TITLE
autocomplete="off" fails "autocomplete attribute has valid value" (73f2c2)

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#1540]
The rule "autocomplete attribute has valid value" (73f2c2) has the assumption "The autocomplete attribute is used on form fields that correspond to Input Purposes for User Interface Components and collect information about the user."

This means that the use of autocomplete="off" is actually not applicable to the rule due to the expectation. 

However, I have twice this week had to debug automated testing results (from two different checker engines) that failed autocomplete="off". 
I think this is an indication that the rule incorrectly flags a common practice as an accessibility issue.

**Comment by WilcoFiers** [comment]
Yeah, looks like we missed that one. I had a quick look at our own implementation, and it gets this right, but it does not seem to be covered by the rule. Would you be up for submitting a fix for this? I think another bullet in the applicability, and an inapplicable example of this would be the way to go for this.

**Comment by ajanec01** [comment]
Is the background section not sufficient to fix this issue? I guess we could move it to applicability but that would create a rather large applicability section.

> The auto-completing feature of the autocomplete attribute benefits many users, but it is not required to satisfy success Criterion 1.3.5 Identify Input Purpose. Setting autocomplete="off" on the element's form owner prevents the user agent from completing it, but it does not prevent the autocomplete attribute value from being programmatically identifiable.

**Comment by annethyme** [comment]
I think it would be best to include it in the expectation, like e.g. Siteimprove has done in their rule documentation: https://alfa.siteimprove.com/rules/sia-r10.

Right now an automated checker implementing a more naive version of this rule will get a bunch of false positives for this rule.

**Comment by ajanec01** [comment]
I will create a pull request to create expectation number 3. I'm inclined to keep the entire paragraph as is because it clearly refers to `autocomplete="off"` being on the form owner as opposed to the actual input elements. The assumption is that input elements collect information about the user so cases such as `<label>Username<input autocomplete="off" /></label>` are indeed a failure of sc 1.3.5.

**Comment by annethyme** [comment]
As I see it, this rule should check whether the autocomplete has a valid value, while another rule could be created to check whether the value is appropriate. Much like it is being done for the rules for 3.1.1 Language of Page.

**Comment by ajanec01** [comment]
I've no objections to that. It would be good to get input from the rest of the community before we do that. @WilcoFiers and @carlosapaduarte, is it ok to put it on the agenda for the next call?
