### ISSUE TITLE
With autocomplete, should type=tel be allowed on all numbers? [73f2c2]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1541]
Common feedback we got on the autocomplete rule was people that wanted to use `type=tel` on number fields such as `bday-month`. The reason is that with type=tel IOS opens the number keypad, which it does not do if you use type=number. 

Axe-core has since built an exception in its autocomplete rule that allows type=tel. I wonder if this is something the autocomplete rule should allow. Or alternatively... if we should have a test case that shows axe-core's implementation is a partially consistent one, because of this exception.

**Comment by ajanec01** [comment]
I think that we had a similar discussion. It is not a failure of sc 1.3.5. An incorrect control group may prevent auto-filling (doesn't mean it will), but the autocomplete property is still programmatically identifiable. The easiest fix is to remove Expectation 2.

**Comment by ajanec01** [comment]
The `type` can be incorrect, see #1583
