### ISSUE TITLE
Change to w3c.org in tests leading to intermittent test failures

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1543]
The change from example.com to w3c.org in https://github.com/act-rules/act-rules.github.io/commit/8e20cff8c510a64cb42678da55a8658fb8181a77 is leading to intermittent test failures

https://w3c.org redirects to https://w3.org but requests to https://w3c.org sometimes fail when running the test suite, and in Chrome. The screenshot shows what happens in Chrome after running the test suite. 

There may be rate limiting on w3c.org triggered by too many requests in a short time (which will happen when running a test test suite)

<img width="888" alt="Screenshot 2021-01-30 at 08 05 29" src="https://user-images.githubusercontent.com/16352274/106351161-67db1f80-62d2-11eb-8835-4d0a89ab960a.png">

Edit: after requests to https://w3c.org fail I can still access https://w3.org
Edit2: if we're all running the test suite and making requests to w3c.org the traffic pattern might look very similar to a DDOS

**Comment by dd8** [comment]
Seeing w3c.org showing as down in downforeveryoneorjustme but w3.org is up

![Screenshot 2021-01-30 at 21 23 55](https://user-images.githubusercontent.com/16352274/106368503-db684580-6341-11eb-85aa-d10069954462.png)
![Screenshot 2021-01-30 at 21 23 33](https://user-images.githubusercontent.com/16352274/106368506-dd320900-6341-11eb-9439-716111fc70b2.png)

**Comment by WilcoFiers** [comment]
Thanks Mark! Yeah I ran into that problem yesterday too. I'll get it fixed ASAP. Not sure how we missed that. Apologies.
