### ISSUE TITLE
"role attribute has valid value" (674b10): Failed Example 1 and 2 are incorrect

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#1551]
https://act-rules.github.io/rules/674b10#failed-example-1

```html
<style>
	.link {
		color: #0000ee;
		text-decoration: underline;
		cursor: pointer;
	}
</style>
I love <span class="link" onclick="location.href='https://act-rules.github.io/'" role="lnik">ACT rules</span>.
```

https://act-rules.github.io/rules/674b10#failed-example-2

```html
<style>
	.ref {
		color: #0000ee;
		text-decoration: underline;
		cursor: pointer;
	}
</style>
See [<span class="ref" onclick="location.href='https://act-rules.github.io/'" role="bibliographic-reference lnik"
	>ACT rules</span
>].
```

The rule applies to non-empty `role` attributes specified on elements that are included in the accessibility. The `<span>` elements in the code above _aren't_ included in the accessibility tree as they fit none of the inclusion criteria: https://www.w3.org/TR/wai-aria-1.2/#tree_inclusion. Firefox, for example, computes the following accessibility tree for the second example:

<img alt="Accessibility tree computed by Firefox for Failed Example 2" src="https://user-images.githubusercontent.com/1174718/109296005-f7bbad00-782f-11eb-941e-4a0a8116dfe1.png" height="104">

Alfa computes the following accessibility tree, with "uninteresting" nodes included in the output:

```
container
  container
  container
    ignored
    container
      text "See ["
      container
        text "ACT rules"
      text "]."
```

**Comment by kasperisager** [comment]
Interestingly enough, Firefox _is_ actually exposing the `<span>` element as a "clickable" text node. Chrome, on the other hand, doesn't do that and instead exposes 3 separate text nodes similar to Alfa, with "container" instead being Chrome's equivalent "generic". Safari merges all text nodes into a single one.

**Comment by Jym77** [comment]
🤔 I guess we can either replace them with `button` elements, add a `tabindex` or add an `aria-label`.
Not sure which would be the best solution here…

Maybe an `aria-label` a bit more explicit than the text, like "ACT rules home page" to make it not too artificial… (and more explicit name would make a bit of sense for giving a good name in the list of links (which here doesn't work due to the bad role, but that's the full point of the examples…))

**Comment by WilcoFiers** [comment]
I think the change needed is to replace "included in the accessibility tree" with a "has a hidden state of false". Adding it to the agenda, probably worth talking about.

**Comment by Jym77** [comment]
I think it makes sense, and would match the assumption that it has some presentation (at least, it is not hidden…)

**Comment by Jym77** [comment]
https://act-rules.github.io/glossary/#hidden-state
