### ISSUE TITLE
"ARIA state or property is permitted" (5c01ea) should allow more attributes, following "ARIA in HTML"

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1573]
[ARIA state or property is permitted](https://act-rules.github.io/rules/5c01ea) only allows for global ARIA attributes and the ones explicitly mentioned in ARIA.
However, [ARIA in HTML](https://w3c.github.io/html-aria/#docconformance) is having an extended list of attributes (and roles) that are allowed depending on the HTML element. There are more of them than the stuff mentioned in ARIA.

Among other, `<input type="password">` have no role which, according to our rule, only allow for global `aria-*` attribute, but [ARIA in HTML of password](https://w3c.github.io/html-aria/#el-input-password) explicitly allows the attribute allowed on `textbox`.

Thus, our rule is failing `<input type="password" aria-required>` since `aria-required` is not a global attribute, but it shouldn't fail since `aria-required` is allowed on `textbox` and therefore on `input type="password"`.

See https://github.com/w3c/aria/issues/1461

Not entirely sure how to salvage the rule without being too verbose…

**Comment by WilcoFiers** [comment]
The group is in agreement that this needs to be accounted for in the expectation. Feel free to suggest a change to this.

**Comment by WilcoFiers** [comment]
As part of resolving this, we should also check if other rules are impacted by this.

**Comment by ajanec01** [comment]
Fixed in #1612
