### ISSUE TITLE
[Quick Review] Focusable element has no keyboard trap via non-standard navigation

### ISSUE THREAD

**Issue by tbostic32** [act-rules/act-rules.github.io#1586]
Rule Link: https://act-rules.github.io/rules/ebe86a

@daniel-montalvo Pinging you again since apparently we got matched up a few times. I accepted this rule in the excel doc, but I did have a couple concerns I wanted to bring up for discussion:

- The note in applicability could probably be removed
- Since each expectation is dependent on the help information defined in the first expectation, I was wondering if it would be easier as a single expectation using the "conditional format" (i.e., help information exists and; is visible; and explains stuff; and ...)
- The first assumption seems duplicative of the applicability to me. I think it could be removed.

As for some programming notes
- I am wondering why we use inline anonymous functions for the javascript instead of specifying it in the `<script>` like I think we normally do. As it is now, it seems like a bit of a wall of text looking at all of the inline functions.
- I would recommend using `event.key === 'm'` over `event.keyCode` just for readability (readers can quickly confirm the 'm' button must be pushed instead of looking up the keyCode for 'm')

**Comment by daniel-montalvo** [comment]
Sorry for the late response, @tbostic32 

This definitely requires some editorials, I agree to what you just said and I would also take a pass on the test case descriptions.

I'll mark as accepted as we agreed that editorial is not a reason to reject at this stage.
