### ISSUE TITLE
Headings under discussion in "Bypass Blocks of Repeated Content"

### ISSUE THREAD

**Issue by kengdoj** [act-rules/act-rules.github.io#1587]
Block on [Bypass Blocks of Repeated Content](https://act-rules.github.io/rules/cf77f2) explanation:

Open Issue [Are 'Headings' enough to pass 2.4.1: Bypass Blocks](https://github.com/w3c/wcag/issues/1712). Since headings (and other techniques for grouping and identifying blocks of content) are not keyboard accessible mechanisms to bypass blocks, there is some question as to whether these techniques should pass 2.4.1.

**Comment by WilcoFiers** [comment]
I've reached out to the AG chairs asking if this can be on the agenda soon.
