### ISSUE TITLE
Link in context editorial suggestions  5effbb

### ISSUE THREAD

**Issue by ajanec01** [act-rules/act-rules.github.io#1605]
Test cases for [Link in context is descriptive rule](https://act-rules.github.io/rules/5effbb#semantic-link) need updating. Happy to do that, just want to get opinions on another related subject before doing so.

This rule uses the definition of [programmatically determined link context](https://act-rules.github.io/rules/5effbb#programmatically-determined-link-context).  I've noticed that there is no mention of context being provided by preceding headings, which, at least in my opinion, is a common pattern. There is an [advisory technique H80](https://www.w3.org/WAI/WCAG21/Techniques/html/H80.html), that proposes the following example:
```
<h2><a href="royal_palm_hotel.html">Royal Palm Hotel</a></h2>
  <ul class="horizontal">
    <li><a href="royal_palm_hotel_map.html">Map</a></li>
    <li><a href="royal_palm_hotel_photos.html">Photos</a></li>
    <li><a href="hroyal_palm_hotel_directions.html">Directions</a></li>
    <li><a href="royal_palm_hotel_reviews.html">Guest reviews</a></li>
    <li><a href="royal_palm_hotel_book.html">Book now</a></li>
  </ul>

<h2><a href="hotel_three_rivers.html">Hotel Three Rivers</a></h2>
  <ul class="horizontal">
    <li><a href="hotel_three_rivers_map.html">Map</a></li>
    <li><a href="hotel_three_rivers_photos.html">Photos</a></li>
    <li><a href="hotel_three_rivers_directions.html">Directions</a></li>
    <li><a href="hotel_three_rivers_reviews.html">Guest reviews</a></li>
    <li><a href="hotel_three_rivers_book.html">Book now</a></li>
  </ul>   
  ```

The description for the technique reads:

> The objective of this technique is to describe the purpose of a link from the context provided by its heading context. The preceding heading provides context for an otherwise unclear link. The description lets a user distinguish this link from links in the Web page that lead to other destinations and helps the user determine whether to follow the link.

Based on this, I assume that if a heading provides enough context for a link, this is a pass of 2.4.4. I assume that the idea there was that, for example, a screen reader user can check what the previous heading is after arriving at a link.  

It would be good to know what you think, should the definition of programmatically determined link context be expanded by headings?

**Comment by Jym77** [comment]
See also #1572.

**Comment by carlosapaduarte** [comment]
Waiting for #1765 to be merged. Then update examples of [Link in context is descriptive](https://act-rules.github.io/rules/5effbb)

**Comment by carlosapaduarte** [comment]
As per my comment in https://github.com/act-rules/act-rules.github.io/pull/1765#discussion_r799745301, WCAG removed headings from the programmatically determined context from 2.0 to 2.1

Therefore, I'm closing this issue. Feel free to reopen if needed.
