### ISSUE TITLE
Printable characters expectation issue ffbc54

### ISSUE THREAD

**Issue by ajanec01** [act-rules/act-rules.github.io#1606]
In [No keyboard shortcut uses only printable characters](https://act-rules.github.io/rules/ffbc54), the description and some of the examples clearly say that single printable character key shortcuts are allowed when an element has focus, the expectation does is only implying it by referring to widgets. 

I'm not sure how exactly to do it so just posting an issue for now.

**Comment by kengdoj** [comment]
Also:
- Expection is missing (disable) a mechanism to disable the shortcut, or...
- in Passed Ex 6, disabling works but control + does not work when set. The description says that the remap should work. (Passed Ex 4's control + works.)

**Comment by ajanec01** [comment]
Thanks @Jym77!

Yes, I've had a look and [Carlos's comment](https://github.com/act-rules/act-rules.github.io/pull/873#discussion_r460766616) is explaining it. I'll put something into the background section to try avoid any other potential confusions.

@kengdoj, regarding your point about Expectation, I think this is covered by **remap** , as in the event that uses the same key is blocked (no changes to the content) and the `getModifierState` still returns `false`. `true` for any of the modifiers would be ok with WCAG (@Jym77 please correct me if I'm wrong). I'll see how I can improve as it is not so obvious.

Also, I'm not sure what do you mean by 

> in Passed Ex 6, disabling works but control + does not work when set

The toggling mechanism for the '+' key works well for me. the remap for using Ctrl also works for me just like in Passed example 4, with the only difference being that in example 6, the user has the chance to toggle the shortcut and then to customize it even better by adding a modifier key.
