### ISSUE TITLE
Some video examples should have audio, but they do not [1ec09b]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1620]
I haven't checked them all but at least passed example 1 and 3 should have audio. But this does not seem to be the case:
https://act-rules.github.io/rules/1ec09b

**Comment by ajanec01** [comment]
I get audio on my iPhone. I think that falls under the accessibility support section. I had the same concern for [video element visual content has audio description](https://act-rules.github.io/rules/1ea59c), as in, it did not want to work in Firefox and Chrome on desktop.

**Comment by ajanec01** [comment]
Maybe it would be good to park those rules (meaning not to publish as proposed) until we test it thoroughly across browsers and write a more descriptive accessibility support section?

**Comment by kengdoj** [comment]
I can hear audio in Passed 1 and 3 in Edge. (But not in Chrome.)

I hear audio in Passed Ex 2, but do not hear audio descriptions. Same for Failed Ex 2.

**Comment by tbostic32** [comment]
Currently investigating this, after a bit of digging, one possible reason for this is that the [rabbit video file that works](https://github.com/act-rules/act-rules.github.io/blob/develop/test-assets/rabbit-video/video.mp4) uses the audio codec MPEG AAC Audio while the others that are failing use A52 (AC3) Audio. 

I haven't had a chance to determine which files have this, but I was able to confirm that converting to the MPEG AAC Audio format does fix the issue.

**Comment by tbostic32** [comment]
See the pull request above. One thing I also noticed was that several of the videos were 720p while others were just 240p or something like that.
