### ISSUE TITLE
Does `video` need audio to check for a transcript [1a02b0]

### ISSUE THREAD

**Issue by ajanec01** [act-rules/act-rules.github.io#1625]
In rule [video element visual content has transcript](https://act-rules.github.io/rules/1a02b0), the applicability says:

> This rule applies to every non-streaming video element that is visible **where the video contains audio.**

This rule is mapping to [1.2.8](https://www.w3.org/TR/WCAG21/#media-alternative-prerecorded) which says that "all prerecorded synchronized media" **and**  "all prerecorded video-only media" need to have a transcript. I recommend for the applicability to be:

> This rule applies to every non-streaming video element that is visible. 

The last inapplicable example 2 should also be removed.

**Comment by kengdoj** [comment]
Agree with @ajanec01 on all points.

Also, suggest Rule name be "video element audio and visual has transcript"
