### ISSUE TITLE
Should videos allow description tracks? 

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1637]
The following two rules allow description tracks for WCAG. However since description tracks have no support in browsers whatsoever, it doesn't seem like you'd be able to conform to WCAG 2 with them, since if it is relied on it would need to have some sort of accessibility support. There just isn't any.

We can keep these two rules around, but I think it would be better not to include them in their composite rules.

- [video element visual content has description track](https://act-rules.github.io/rules/f196ce)
- [video element visual-only content has description track](https://act-rules.github.io/rules/ac7dc6)

**Comment by tbostic32** [comment]
I didn't make an issue for it, but I noted in the excel sheet that [visual content has description track](https://act-rules.github.io/rules/f196ce) had these major accessibility support caveats, so I am good with not including them.

**Comment by colabottles** [comment]
@WilcoFiers Can you assign me to this so I can come back to this later, please? Thank you.

**Comment by kengdoj** [comment]
Related to #1665 

- [video element visual content has description track](https://act-rules.github.io/rules/f196ce): listed in spreadsheet as migrated, will fix
- [video element visual-only content has description track](https://act-rules.github.io/rules/ac7dc6): currently blocked and should remain blocked. Will remove reference to this rule from other rules.
