### ISSUE TITLE
c3232f Inconsistency in test cases examples

### ISSUE THREAD

**Issue by daniel-montalvo** [act-rules/act-rules.github.io#1644]
* [Passed Example 1](https://act-rules.github.io/rules/c3232f#inapplicable-example-1) mentions an audio description track. I cannot find any audio description track on that page. See #1637 
* [Failed example 1](https://act-rules.github.io/rules/c3232f#inapplicable-example-1) I cannot access the audio track either
* [Inapplicable example 1](https://act-rules.github.io/rules/c3232f#inapplicable-example-1) says it has audio, but I cannot hear  any audio.

**Comment by WilcoFiers** [comment]
Fixed with #1680
