### ISSUE TITLE
"Hidden state" is not a very good name

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1660]
So, we have a definition of [hidden state](https://act-rules.github.io/glossary/#hidden-state) which is actually about stuff being announced by ATs or not (which differs from "included in the accessibility tree" because containers elements (e.g. `div`) are not really in the accessibility tree, but still not hidden to ATs).

Anyway, the name "hidden" sounds like this has something to do with visibility, not with ATs… This makes a bit confusing.

I'm not having a perfect name idea for it… We could replace "element has a hidden state of true" by:
* "element is not exposed to ATs"
* "element is not announced by ATs"
* "element is inert"
* "element is hidden from ATs"
* "element is concealed"
* …

**Comment by WilcoFiers** [comment]
Personally, I quite like "hidden state". Happy to discuss.

**Comment by WilcoFiers** [comment]
Alternative suggestion: Programatically hidden
