### ISSUE TITLE
autocomplete attribute has valid value 73f2c2 - inapplicable test cases

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1667]
I think the inapplicable test cases that currently use `autocomplete="username"` would be better if they used an value that would cause a failure like `autocomplete="badterm"`

Otherwise I think a tool can get the applicability wrong and still pass all the test cases.

**Comment by WilcoFiers** [comment]
@dd8 That's a good point. Yeah I totally agree. Would you be up for opening a PR? Here's a direct link:

https://github.com/act-rules/act-rules.github.io/edit/develop/_rules/autocomplete-valid-value-73f2c2.md

**Comment by WilcoFiers** [comment]
Assigned to @colabottles
