### ISSUE TITLE
Rename "valid language tag" definition

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1672]
I think "valid language tag" is a bit misleading. It used to be that we actually required valid BCP-47 tags, but now it's more just that the tag can be parsed. I think we should look for some term that we can use other than "valid" to better suggest the "looseness" of the requirement.

I'm thinking maybe something like "**standard primary language tag**"? It's a bit of a mouth full, but I feel it describes this well. "standard" suggests it has to be a predefined thing, and "primary" I think is needed to make it more explicit that this is only about the primary tag.

**Comment by john-urbilog** [comment]
What if you just said "Conventional language tag" ?   (just another option, your argumentation is sound as is).
