### ISSUE TITLE
Orientation of page not restricted rule doesn't detect rotate: 90deg [b33eff]

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1678]
The rule's applicability includes `transform: rotate(90deg)` but not `rotate: 90deg`

https://developer.mozilla.org/en-US/docs/Web/CSS/rotate

https://act-rules.github.io/rules/b33eff

I can do a PR for this

**Comment by WilcoFiers** [comment]
Thought Carlos had responded. Sorry Mark. Yeah makes sense. A PR would be much appreciated!

**Comment by Jym77** [comment]
`rotate` seems to have very limited support (Firefox, and partly for Safari).
We should at least add a big "Accessibility Support" note with it; maybe wait until it has wider support before doing the change.

**Comment by dd8** [comment]
> `rotate` seems to have very limited support (Firefox, and partly for Safari).
> We should at least add a big "Accessibility Support" note with it; maybe wait until it has wider support before doing the change.

The orientation rule applies to mobile only - so practically this means Android and iOS. iOS 14 supports `rotate:` and will ship on 16 September 2021. iOS auto-updates so most iOS users will be on iOS 14 with Safari 14 a few weeks from now.

An update for Chrome on Android is in in progress - `rotate:` support was added, then dropped, from Chrome stable due to to a performance regression, but I'd expect this to appear again soon - probably by the time the PR is finished/approved:
https://bugs.chromium.org/p/chromium/issues/detail?id=696374

**Comment by dd8** [comment]
Yes, but might take a week or two to get round to it.

**Comment by WilcoFiers** [comment]
@dd8 Any update on this Mark?

**Comment by dd8** [comment]
Hoping to get to this at the end of this week.

**Comment by dd8** [comment]
@WilcoFiers PR https://github.com/act-rules/act-rules.github.io/pull/1742 submitted

PS I don't have permissions to assign myself or add labels per the PR Template

**Comment by carlosapaduarte** [comment]
Thanks @dd8 
Assignments done

**Comment by ChrisLoiselle** [comment]
@carlosapaduarte @dd8 , has a PR been made on your request regarding adding an updated example? Would you like to propose one if not? I'm happy to file if you want me to, just looking for clarity on where we are on this issue. Thank you both for your time.

**Comment by dd8** [comment]
> @carlosapaduarte @dd8 , has a PR been made on your request regarding adding an updated example? Would you like to propose one if not? I'm happy to file if you want me to, just looking for clarity on where we are on this issue. Thank you both for your time.

It's been done in https://github.com/act-rules/act-rules.github.io/pull/1742 - just waiting for another approval
