### ISSUE TITLE
Text spacing not !important rules should check text is actually affected [78fd32, 24afc2, 9e45ec]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1687]
This issue applies to the following three rules:
- [Letter spacing in style attributes is not !important](https://act-rules.github.io/rules/24afc2)
- [Line height in style attributes is not !important](https://act-rules.github.io/rules/78fd32)
- [Word spacing in style attributes is not !important](https://act-rules.github.io/rules/9e45ec)

These ACT rules should check that there are actual text nodes affected by the style attribute. For example, the following scenarios probably shouldn't be failing the rule:

```html
<div style="letter-spacing: 2px !important; border-top: 1px solid black;">
  <!-- empty div, border to make it "visible" -->
</div>
```

```html
<div style="letter-spacing: 2px !important">
  <p style="letter-spacing: 3px !important;">
    The toy brought back fond memories of being lost in the rain forest.
  </p>
</div>
```

**Comment by Jym77** [comment]
Should be fixed by the formulation I suggest in https://github.com/act-rules/act-rules.github.io/issues/1688#issuecomment-901739190 🤞
