### ISSUE TITLE
"Element with lang attribute has valid language tag" and "HTML element language subtag matches language" [de46e4, off6ek] should ignore whitespace only text

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1693]
```
<body><div lang="invalid"> <span lang="en">Hello</span> </div></body>
```
[Element with lang attribute has valid language tag](https://act-rules.github.io/rules/de46e4) fails this because there are two non-empty text nodes within the `div`, but these are whitespace and don't create problem.

[HTML element language subtag matches language](https://act-rules.github.io/rules/off6ek) is a bit mixed up there, these whitespace text nodes do not have any [most common language](https://act-rules.github.io/rules/off6ek#most-common-element-language) due to having no words, which make the expectation fails (`invalid` is not a most common language).

Suggestions (choose one):
1. In both rules, replace the last Applicability bullet from "non-empty text" to "non-whitespace text"
    **Problem**: we're still running into the same issue with corner cases of non-text "text" (e.g. smiley, punctuation, …); OTOH I'm not sure how this is announced… But at least `<span lang="en">😀</span>` doesn't have a most common language and therefore fails [HTML element language subtag matches language](https://act-rules.github.io/rules/off6ek). (yes, it's an Unicode smiley inside that text node, also works with an ASCII art one like `:-)`)
2. In both rules, update Expectation to say something like "either the element [on which the attribute is declared] has no most common language, or [current check]"
    **Problem**: this makes [Element with lang attribute has valid language tag](https://act-rules.github.io/rules/de46e4) much harder to fully automate since it needs to know the most common language. I sorta assume that tools will default to heuristic like "non-whitespace text". Depending on how strict we build our tests cases, this may result in having less implementations for the rule 😢 
3. Update Applicability of [Element with lang attribute has valid language tag](https://act-rules.github.io/rules/de46e4) to reject whitespace text nodes; and Expectation of [HTML element language subtag matches language](https://act-rules.github.io/rules/off6ek) to explicitly pass if there are no most common language.
    **Problem?**: [Element with lang attribute has valid language tag](https://act-rules.github.io/rules/de46e4) would still fail `<span lang="invalid">😀</span>` (or `<span lang="invalid">:-)</span>`). But maybe that is OK because the emojis (or symbols) are actually announced and therefore screen readers need a language to pick (i.e. "smiling face" is not the same as "visage souriant", so having an invalid `lang` attribute on such a `span` is indeed a real problem) 🤔

**Comment by WilcoFiers** [comment]
I think you're sort of mixing two problems together here. One of whitespace, and one of non-text unicode.

For the first one, I like your option 1. For the second one, I think it is reasonable to add an assumption that the text nodes contain human language.

**Comment by Jym77** [comment]
Alfa is effectively failing https://act-rules.github.io/rules/de46e4#passed-example-4 because we somehow grab the inter-element whitespaces `\n\t\t` as a text node and thus believe that the `article` element has some text 😞 (https://act-rules.github.io/implementation/alfa/incomplete#id-de46e4)

So, we obviously need to fix it in Alfa, but then I figured out that the rule itself is not behaving correctly in presence of whitespace only text nodes.

[HTML element language subtag matches language](https://act-rules.github.io/rules/off6ek) is still failing when there is no most-common language, which seems wrong (then whatever the `lang` attribute, it cannot be bad and shouldn't fail 3.1.2), but I agree that is likely a different problem.

So, I'd say option 1. Plus update [HTML element language subtag matches language](https://act-rules.github.io/rules/off6ek) to clarify that it passes (rather than fails) when there is no most common language.

**Comment by WilcoFiers** [comment]
Option 1 seems good to me. Feel free to pick up the issue.
