### ISSUE TITLE
Hidden state / Programmatically hidden doesn't handle collision between `hidden` and `display: none`

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1698]
Our definition of [Programmatically Hidden](https://act-rules.github.io/glossary/#programmatically-hidden) contains (roughly):
> has a `hidden` attribute or `display: none`

However, most (all?) browsers implement `hidden` as `display: none` which means that it can actually be overriden (`<p hidden style="display: block">Foo</p>` is actually not hidden.

How can we handle that in the definition?

1. Remove the bit about `hidden` attribute (keep only `display: none`), add an assumption that `hidden` is handled by `display: none`.
    **Problem**: that's an assumption we need to copy to every rule using this definition.
    **Problem**: if we end up with UA that don't do that, the def is broken for them…
2. Leave as is, add an Accessibility Support that "if `hidden` is handled as `display: none`, the `hidden` condition should not be used.
    **Problem**: that sounds pretty wonky and doesn't really help.
3. Replace `hidden` by something like "`hidden` and not visible".
    **Problem**: something like `<p hidden style="display: block; position: absolute; left: -9999em">` would match but would actually be exposed to ATs, so precisely the thing this definition tries to catch…

See also:
#1523 and https://github.com/act-rules/act-rules.github.io/pull/1663#issuecomment-903672856

**Comment by WilcoFiers** [comment]
@Jym77 have you tested what happens to AT when something has the hidden attribute, but then gets display:block? I'm guessing it'll still be programatically hidden.

**Comment by carlosapaduarte** [comment]
Discussed this on the call: resolution is to remove the hidden attribute from the definition, and add a note about it

**Comment by Jym77** [comment]
Add link to https://html.spec.whatwg.org/multipage/rendering.html#hidden-elements
