### ISSUE TITLE
ACT Rule Review: Line Height in style attributes is not !important

### ISSUE THREAD

**Issue by tbostic32** [act-rules/act-rules.github.io#1706]
### Trevor
- Recommended -> Required (PR #1683)
- Duplication of `1.5` needs clarification

### Wilco
- #1686, #1687, #1688
- The test cases don't actually show the effect of line-height, since these aren't multi-line examples. That seems like a problem to me.
- I'm not too bothered by the edge cases we opened. These rules have been in production for a while and I haven't seen anyone report this. These are hypothetical, so not blockers as far as I'm concerned.				

### Kathy
 - "Under Accessibility Support: "If accessibility support does not include assistive technologies that override line-height through author origin, this rule should not be used." - Can it be explained in the rule how would someone determine if accessibility support does (or does not) include this type of AT?"			

### Aron
- There needs to be a consensus about the "large enough" point of the Expectation section.	

## TODO: 
Trevor to make required updates.

**Comment by tbostic32** [comment]
@kengdoj Was our resolution for your comment to remove that sentence from the accessibility support? I remember us discussing that it was weird to intentionally allow developers/content authors to not follow the rule just because they thought no-one using the assistive technologies on their site would run into this.

**Comment by kengdoj** [comment]
I recall discussing that there's limited tools that fit the criteria and that they typically aren't considered AT. Removing the sentence would address my comment. Not sure if there was anything suggested to replace it. @WilcoFiers, do you remember?
