### ISSUE TITLE
"Zoomed text node is not clipped with CSS overflow" [59br37] is mixing vertical and horizontal overflows

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1733]
```html
<style>
  .container { border: red dashed 1px; width: 50px}
  .content {white-space: nowrap; border: green 1px solid}
  .clipping {overflow: hidden; }
  .short {white-space: nowrap; text-overflow: ellipsis; line-height: 5px; width: auto}
  .high {line-height: 100px}
</style>
<div class="container"><span class="content">Content overflows its container</span></div>
<div class="container clipping"><span class="content">Content is clipped by its container</span></div>

<div class="container clipping short"><span class="content">Passing due to first exception</span></div>
<div class="container clipping high"><span class="content">Passing due to second exception</span></div>
```
- The first content has full visible overflows and passes the rule, this is good.
- The second is clipped by its container and fails the rule, this is good.
- The third is vertically clipped by the container. Yet, the `white-space` and `text-overflow` make the clipping ancestor satisfy the first exception of the expectation, so it passes the rule; this is not super good.
- The fourth is horizontally clipped by the container. Yet, the huge `line-height` makes the clipping ancestor satisfy the second exception of the expectation, so it passes the rule; this is not super good.

Granted, these are only false negative, but I feel we should still split maybe the definition of [Clipped by Overflow](https://act-rules.github.io/rules/59br37#clipped-by-overflow) in two for `overflow-x` and `overflow-y` and have the exceptions matching these, so we could fail the 3rd and 4th case above.

**Comment by WilcoFiers** [comment]
@Jym77 I'm having a bit of a difficult time understanding your case, but if you have a solve, do you want to open a PR for it?
