### ISSUE TITLE
Should colour contrast rules (afw4f7, 09o5cg) test content of tables?

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1763]
https://act-rules.github.io/rules/afw4f7 and https://act-rules.github.io/rules/09o5cg

The role of `row` inherits from `widget`; and the rules do not apply for text in widgets (due to difficulties in handling states).

So, currently, the rules do not check colour contrast of text in `tr` elements, so effectively do not check content of a `table` element 🙈 

I'm not sure the provision on widget states makes that much sense for `row`… So I'm not sure whether we should add `row` as an exception to the exception ("except if … the ancestor is an inheriting semantic `widget` but not an inheriting semantic `row`" is a bit of a mouthful). Or just keep the rules as is and consider that it will be solved once we get to write colour contrast for widgets rules…

**Comment by WilcoFiers** [comment]
Talking this over with Carlos, we think it might be good to just drop the "no widgets" condition and replace it with a "no disabled widgets" thing. We'll discuss on an upcoming meeting.
