### ISSUE TITLE
Ways to allow others to provide feedback on the rules

### ISSUE THREAD

**Issue by HelenBurge** [act-rules/act-rules.github.io#1769]
Will use this issue to track a proposal of how to provide a working mechanism that is more transparent to those not in the community group on any issues or concerns with the rules.

Ideas so far are:
1. A banner with a link to guest access in GitHub - this might cause noise that is hard to work with but reduces the need for someone to manually enter issues
2. A contact form that has a link in the main navigation so available for all rules, that allows people to comment on active rules or suggest missing ones. It would require someone to review the comments and log new issues manually.
3. Advertise occasional meetings for Ask Us Anything ACT rule sessions? This might be as well as a per rule report link.

**Comment by WilcoFiers** [comment]
Moved this issue to https://github.com/w3c/wcag-act/issues/525
