### ISSUE TITLE
Updates to a25f45 - headers attribute specified on a cell refers to cells in the same table element

### ISSUE THREAD

**Issue by daniel-montalvo** [act-rules/act-rules.github.io#1770]
[headers attribute specified on a cell refers to cells in the same table element](https://act-rules.github.io/rules/a25f45)

- [x] [Consistency with SC names](https://github.com/act-rules/act-rules.github.io/pull/1767).
- [ ] Move notes in expectations to background
- [ ] Update Assumptions with idea that ids are unique.

**Comment by carlosapaduarte** [comment]
@daniel-montalvo can this be closed?
