### ISSUE TITLE
Deprecate description track rules

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1781]
Back in #1665 we removed descriptions tracks as a way to provide video alternative.

Rules [video element visual content has description track](https://act-rules.github.io/rules/f196ce) and [video element visual-only content has description track](https://act-rules.github.io/rules/ac7dc6) now seem to be orphaned and not used anywhere and should probably be marked as deprecated.

**Comment by carlosapaduarte** [comment]
@HelenBurge this should be fairly easy. Just adding DEPRECATED to the title and updating the front matter. 
See https://github.com/act-rules/act-rules.github.io/pull/1538 for what was done for a previous rule when it was deprecated

**Comment by HelenBurge** [comment]
Created #1786
