### ISSUE TITLE
Various undefined input aspects

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1783]
This rule uses an input aspect that does not exist in the common input aspects document. I think we may need to come up with one. https://act-rules.github.io/rules/e6952f

Similarly, there are a number of rules that use the `Audio output` and `Visual output` input aspects, for example: https://act-rules.github.io/rules/f196ce

**Comment by WilcoFiers** [comment]
We'll need to update the following file for this:

https://github.com/w3c/wcag-act/blob/master/NOTE-act-rules-common-aspects.bs

**Comment by kengdoj** [comment]
I've added PR https://github.com/w3c/wcag-act/pull/526, but wasn't able to add reviewers.
