### ISSUE TITLE
Add examples for definitions

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#182]
Add test cases for definitions

@annethyme - can you elaborate on this, for further discussion.

**Comment by WilcoFiers** [comment]
I found this today. It's a document that uses Gherkin to test implementations of the accessible name. That could be a way for us to start writing tests for definitions:

```
if given
  <div id="ID1">Rich's button</div>
  <input type="button" aria-labelledby="ID1" id="test">
then the accessible name of the element with id of "test" is "Rich's button"
```


https://www.w3.org/wiki/AccName_1.1_Testable_Statements

**Comment by WilcoFiers** [comment]
@kasperisager any thoughts on using Gherkin for tests of definitions?

**Comment by jkodu** [comment]
Priority to add examples is based on usage.

**Comment by Jym77** [comment]
Partial PR in #994. This is probably enough for a start given that the other widely used definitions are not so tricky (_e.g._ "non-streaming video").

Keeping this for now, but won't object closing it…

**Comment by jkodu** [comment]
Myself and @Jym77 agreed, we will add definitions as well/ improve other definitions. So #994 now completes this issue.
