### ISSUE TITLE
Documentation: Updates

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#183]
An overhaul of the documentation is essential across the auto-wcag website. I have enlisted not an exhaustive list of what needs updating. Feel free to add more items.

- Update documentation for review process of pull requests. With the new workflow there is no need for drafts, this needs to be reflected in the documentation. --> @annethyme
- Update documentation as to where the test assets are stored. This involves the test assets such as images and videos used within the code snippet blocks of test cases. To document he convention for directory structure & naming of test assets. --> @annethyme
- Update documentation for definitions (previously referred as algorithms). How definitions are to be used when referring them with in a rule, and how they are auto-generated as glossary for each page. --> @annethyme
- Update documentation for test case code snippets are embedded as iframe examples --> @annethyme
- Update documentation on how to author a description for a rule. (Do not use links, add backticks etc). This update needs to be added to the existing style guide. --> @annethyme
- Update rule template to reflect test cases.
- Document how to name pull requests with prefix (chore, rule, definition, etc.,). --> @annethyme
- Document how project board is managed/ automated. --> @annethyme

- The How to Contribute page, https://act-rules.github.io/pages/contribute/, has a lot of TBD links

**Comment by jkodu** [comment]
@nitedog @jeankaplansky @annethyme 
Looking to collaborate on the above documentation updates.

**Comment by jkodu** [comment]
@nitedog @jeankaplansky
I will setup a meeting for the same, to discuss a plan of action.

**Comment by jkodu** [comment]
@nitedog - can you take the lead on this please.

**Comment by jkodu** [comment]
@nitedog 

Can you please validate if this is relevant and which items have been actioned upon & help close this issue?

**Comment by EmmaJP** [comment]
@nitedog see https://github.com/act-rules/act-rules.github.io/issues/250#issuecomment-534488671 for suggested new wording of "Rule name and identifier" section of https://act-rules.github.io/pages/design/rule-design/#rule-properties

**Comment by jkodu** [comment]
Outdated.
