### ISSUE TITLE
Iframe negative tabindex; applicability does not work [akn7bn]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1843]
In a recent update, the applicability of this rule was changed to:
> This rule applies to any non-focusable `iframe` element that has [focusable][] content.

In the definition of "focusable" there is this exception:

> Exception: Elements that lose focus during a period of up to 1 second after gaining focus, without the user interacting with the page the element is on, are not considered focusable.

Since most browsers redirect focus from iframes, i.e. when the iframe is focused, focus is immediately moved to the first element inside that frame, iframes essentially are never focusable. I.e. in browsers that redirect focus, I think iframes are never focusable. I think we need to return to the previous wording of " a negative number as a `tabindex` attribute value".

**secondly**, there is a mismatch between the applicability and the examples. In particular passed example 1 seems like it should now be inapplicable, since the iframe content does not have focusable elements. I don't really understand why "has focusable content" was added to the applicability. That doesn't seem right.

**Thirdly**: It seems to me that passed example 4 should be inapplicable. In all other rules, content that is both visually hidden and hidden to AT is always inapplicable. Having that pass in this rule seems inconsistent.

**Comment by Jym77** [comment]
It looks like all these changes were done in #1779 I do not have access to the mentioned Survey to figure out what were the discussions there…
