### ISSUE TITLE
Organise face to face ACT-Rules meeting

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1847]
Now that covid is somewhat not a thing anymore, we are considering organising a face-to-face ACT rules meeting.
Keeping this open to record organisation and remember to talk about it 😄

**Comment by carlosapaduarte** [comment]
Survey open until July 25: https://www.w3.org/2002/09/wbs/114156/act2022f2f/

**Comment by Jym77** [comment]
Dates: 6 and 7 October 2022.
Location: Dublin, Ireland.

Hybrid meeting (face-to-face + online).

We'll try to have sessions for beginners; and sessions for tasks other than rule writing (website development, automation, …)

**Comment by HelenBurge** [comment]
The offices for the meetings are in:
Optum
https://maps.app.goo.gl/AvG6mH2jpz82m3ab7?g_st=ic

https://www.optum.ie/

I have booked a large room for the 2 days on the 2nd floor. When you enter reception, sign in and ask for Helen Burge and I will collect you to bring you to the shared space.

3 nearby hotels are (lots to choose from within walking distance of the office):
https://www.thespencerhotel.com/
https://www.hilton.com/en/hotels/dubchgi-hilton-garden-inn-dublin-city-centre/
https://www.thesamuelhotel.com/

**Comment by HelenBurge** [comment]
Oh and let me know numbers for a Guinness tour on the Saturday: https://www.guinness-storehouse.com/en/tickets or are there other preferences?

**Comment by HelenBurge** [comment]
As a note - on the 6th, I have an appointment in the morning, so when you arrive at the offices in the morning, ask for Mick Keane. He is a colleague who will be able to show you all to the room and area I booked for the event.

**Comment by HelenBurge** [comment]
This all has happened now!
