### ISSUE TITLE
"Element with presentational children has no focusable content" [307n5z]: Investigate actual UA/AT behaviour

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#1851]
[Element with presentational children has no focusable content](https://act-rules.github.io/rules/307n5z).

It seems that Chrome and Firefox (at least) ignore presentation children on some role, or when there is focusable content, or in some other cases…
```html
<button>
	Save
	<span role="button" aria-label="save options" aria-expanded="false" tabindex="0">▼</span>
</button>
```
(almost Failed Example 1) has both expose the `span` element as a `button`, ignoring the presentational children of the `button` role on the `button` element.

```html
<div role="tab">
  <a href="#">Foo</a>
</div>
```
has them expose the `a` element has a `link`, and NVDA shows it in its list of links.

---
This may actually be the [presentational role conflict resolution](https://www.w3.org/TR/wai-aria-1.1/#conflict_resolution_presentation_none) kicking in in presence of focusable content, which would make the full rule pointless 🙈 
* [Presentational Children](https://www.w3.org/TR/wai-aria-1.1/#childrenArePresentational):
    > The DOM descendants are presentational.
* [Presentational role conflict resolution](https://www.w3.org/TR/wai-aria-1.1/#conflict_resolution_presentation_none):
    > If an element with a role of presentation is focusable, or otherwise interactive, user agents MUST ignore the normal effect of the role and expose the element with implicit native semantics

So, (for the second example), the DOM descendant of the `<div role="tab">` are presentational (due to presentational children), but then the `a` element triggers the conflict between presentational role and focusable, and focusable wins, the element is exposed.

If this is indeed the case, the rule is pointless. Certainly not mapping to 4.1.2.

This seems different with [Element with aria-hidden has no focusable content](https://act-rules.github.io/rules/6cfa84) since `aria-hidden` is not listed in the presentational role conflict resolution and UA behaves differently on it ([Tests I mad previously](https://github.com/act-rules/act-rules.github.io/wiki/Tests-on-Presentational-role-Conflict-resolution)).

OTOH, if merging both as suggested in #1507 (into a "focusable content is included in the accessibility tree" rule), this would de facto solve the problem by letting the builder of the accessibility tree take responsibility of the conflict resolution…

**Comment by scottaohara** [comment]
While Chromium / Firefox expose the nested interactive, some AT still respect the specification and do not allow access to the nested interactive.  And even in situations where the nested interactive is discoverable by AT, it's not robust.  For instance, while someone can find a nested button within a button with NVDA and Chromium browsers if using Tab key or navigating explicitly by buttons, navigating with the virtual cursor (down/up arrow) will not navigate to the child button.

JAWS (firefox+chrome), iOS VO, macOS VO (safari), Talkback (chrome+firefox) all continue to treat the nested 'button' as if it doesn't exist.

```
<button>
  ex1
  <span role=button>ex2</span>
</button>
```

With JAWS + Chromium browsers, if the above span was given a tabindex, the nested button can be focused but will continue to announce as "ex1 ex2, button"

If Safari + VO are in use, and someone navigates to the nested ex2 button, keyboard focus moves to the element, but VO focus remains on the parent button, resulting in no announcement made.
