### ISSUE TITLE
"Image button has non-empty accessible name" [59796f] - clarification about input type image with empty alt but non-empty title

### ISSUE THREAD

**Issue by giacomo-petri** [act-rules/act-rules.github.io#1861]
- **Starting URL**: https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/
- **Highlighted element**: input type image, empty alt attribute and non-empty title attribute 
`<input type="image" src="test.png" alt="" title="non-empty value">`
- **Description**: should we add an example for input type image with empty alt attribute and non-empty title attribute that clearly identify it as a failure?
    - per failed example 2
    _The image button has an empty alt attribute, and no other attributes that can give it an [accessible name](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#accessible-name), hence its name is the default “Submit Query”._
`<input type="image" src="/test-assets/shared/search-icon.svg" alt="" />`
the input is failing due to the absence of an accessible name.
    - per passed example 3
_The image button has an [accessible name](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#accessible-name) through the title attribute._
_note: The title attribute may not always be [accessibility supported](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#accessibility-support)._
`<input type="image" src="/test-assets/shared/search-icon.svg" title="Search" />`
input has an accessible name thanks to the title attribute and title attribute can give it an accessible name.
- **Concerns**:
    - from failed example 2
    _The image button has an empty alt attribute, **and no other attributes** that can give it an [accessible name](https://www.w3.org/WAI/standards-guidelines/act/rules/59796f/#accessible-name),_
    actually, per passed example 3, the title attribute seems a valid attribute to give the input type image an accessible name. I understand that in this context, _can give it_ means that the resulting accessible name is non-empty, but might not be fully clear.
    - following the [accessible name computation](https://www.w3.org/TR/html-aam/#input-type-image-accessible-name-computation) instructions, the empty alt attribute should force the accessible name to be empty. That said, on Firefox, the title attribute is used as fallback even if the alt attribute is empty, as per screenshots attached:
    <img width="1792" alt="screenshot highlighting input type image code with empty alt attribute and non-empty title attribute in Firefox inspector" src="https://user-images.githubusercontent.com/106394951/173630662-484ab0e5-228a-4f94-aaa2-57132cc326db.png">
    <img width="1792" alt="screenshot highlighting input type image accessible name in Firefox accessibility inspector, computed using the title attribute, even if alt attribute is empty" src="https://user-images.githubusercontent.com/106394951/173630774-d41b5738-f083-4283-a7c0-4a937cb61223.png">
- **Conclusion**: Do you think might be helpful to include explicitly scenario above in _Image button has non-empty accessible name_ rule?

Giacomo

**Comment by WilcoFiers** [comment]
> Description: should we add an example for input type image with empty alt attribute and non-empty title attribute that clearly identify it as a failure?

Interesting. I did not realise there's a difference between having an empty alt and having no alt attribute here. Looking at the Chromium AXTree, there clearly is. I think that's it'd be a good idea to add that example. We should also put something about how Firefox handles this in the accessibility support section.

Would you be up for opening a pull request for this?

**Comment by Jym77** [comment]
As per [HTML AAM, accessible name computation](https://www.w3.org/TR/html-aam-1.0/#input-type-image-accessible-name-computation), steps 2 and 3 the `alt` attribute should be used if present and otherwise the `title` attribute should be used. However, step 4 has this "if the previous steps do not yield a usable text string" where I'm not sure if an empty string should count as a "usable text string" or not 🤔 

Quick check, both Chrome seems to give no name to `<input type="image" src="test.png" alt="" title="non-empty value">
` (i.e. consider the empty `alt` as a "usable text string"); but Firefox gives it a name (i.e. does not consider empty `alt` as a "usable text string"). 

So we definitely need an Accessibility Support note to mention that…

And with `<input type="image" src="test.png" aria-label="" title="non-empty value">` (replacing the `alt` by an `aria-label`), Chrome uses the `title` to give a name (this time considering the empty `aria-label` as not being an "usable text string") while Firefox defaults to "Submit query" (this time just ignoring the `title` because 🙃).

At this point, they seems to both interpret the AAM in different ways, but each in its own inconsistent way 🤷 🤦

**Comment by giacomo-petri** [comment]
> And with `<input type="image" src="test.png" aria-label="" title="non-empty value">` (replacing the `alt` by an `aria-label`), Chrome uses the `title` to give a name (this time considering the empty `aria-label` as not being an "usable text string") while Firefox defaults to "Submit query" (this time just ignoring the `title` because 🙃).

@Jym77 I've performed some test too using different browsers but I cannot replicate your experience with Firefox (version 101.0.1). It seems behaving consistently:
- `<input type="image" src="test.png" alt="" title="non-empty value">` has "non-empty value" as accessible name
- `<input type="image" src="test.png" aria-label="" title="non-empty value">` has "non-empty value" as accessible name too.

I've also tested the other html elements that support the alt attribute (img, input type image and area) and only the area element is inconsistent in Firefox:
- `<area shape="rect" coords="x1,x2,y1,y2" alt="" title="non-empty value" href="test1.htm">` returns "non-empty value" as accessible name
- `<area shape="rect" coords="x1,x2,y1,y2" aria-label="" title="non-empty value" href="test2.htm">` returns the href value as accessible name (**inconsistent**)

I experienced the same behaviour on Chrome (version 102.0.5005.61), that is consistent for every element (img, input type image and area), using the title value as accessible name if aria-label is empty and setting empty accessible name if used in combination with the empty alt attribute (alt="").

Safari (Version 15.4) is behaving pretty inconsistently.
For images:
- <img src="image.jpg" alt="" title="non-empty value"> returns "non-empty value" as accessible name
- <img src="image.jpg" aria-label="" title="non-empty value"> returns "non-empty value" as accessible name
But for inputs type image:
- `<input type="image" src="test.png" alt="" title="non-empty value">` returns default "Submit Query" as accessible name
- `<input type="image" src="test.png" aria-label="" title="non-empty value">` returns "non-empty value" as accessible name
For area:
- `<area shape="rect" coords="x1,x2,y1,y2" alt="" title="non-empty value" href="test1.htm">` returns "non-empty value" as accessible name
- `<area shape="rect" coords="x1,x2,y1,y2" aria-label="" title="non-empty value" href="test2.htm">` returns No Accessibility Information (but using VO, it announces "link, non-empty value".

**Comment by Jym77** [comment]
@giacomo-petri Interesting 🤔 
I've been using the following code:
```html
<input type="image" src="test.png" alt="" title="empty alt">
<input type="image" src="test.png" aria-label="" title="empty aria-label">
<input type="image" src="test.png" aria-labelledby="foo" title="empty aria-labelledby">

<span id="foo"></span>
```
And here is what I see in Chrome (102.0.5005.115) and Firefox (101.0.1), plus NVDA output on them.
![Chrome + NVDA screenshot](https://user-images.githubusercontent.com/19969498/174267773-957de526-84f1-4063-b4cb-5d1829306794.png)
![Firefox + NVDA screenshot](https://user-images.githubusercontent.com/19969498/174267778-299cb89e-29b0-4814-9500-f303a4bf7ca5.png)

So, Chrome is using the empty `alt` in the first case, but defaults to `title` in the two other cases. And Firefox somehow uses the `title` in the first case, but hides the button from NVDA 🤔 and defaults to "Submit Query" in the two other cases.

---
Aha 💡 
This actually depends whether the image loads 💥 With a loaded image, I get the following results.
![Chrome + NVDA screenshot (button image loaded)](https://user-images.githubusercontent.com/19969498/174269277-e3f33b6e-2c15-46f1-a82c-eff540005f6b.png)
![Firefox +NVDA screenshot (button image loaded)](https://user-images.githubusercontent.com/19969498/174269282-358b1b56-77c4-4522-b506-514f43f01297.png)

So when the image **does** load, Firefox is indeed defaulting to `title` in all three cases while Chrome only uses it after an empty `aria-label` but not after an empty `alt` or `aria-labelledby`.

---
Combined, this makes even less sense and everything is even more inconsistent, it feels 🙃

**Comment by giacomo-petri** [comment]
@Jym77, thanks for this input about images not loaded.

Based on our previous comments that highlight inconsistency between different browsers but also within the same browser, assuming that some of these inconsistent scenarios will be updated in the future, should we update the rule saying something like:
"Combinations of passed examples do not guarantee the fulfilment of this rule. For example ..."

Otherwise might be hard to cover all scenarios and keep it updated.

**Comment by Jym77** [comment]
@giacomo-petri We might actually want to investigate browser side (and HTML AAM side) whether they consider these are bugs and want to fix them… 
Is it something you want to do (investigate if there are open issues and open them if needed)?

Maybe there are some good reason why they behave that way and we just can't figure them out. It's also interesting to have the HTML AAM opinion on what the "good" way should be (so we can write our rule that way and claim the moral higher ground).

**Comment by giacomo-petri** [comment]
Request to the HTML AAM group submitted.
Once we have an answer with good practices, if still valid I'll ping browser side to understand if they consider highlighted scenarios as bugs and if they are interested solving them.

I'll keep the issue updated.

**Comment by giacomo-petri** [comment]
Updates:

per HTML AAM https://github.com/w3c/accname/issues/27#issuecomment-802138411 the intent was:

> if there's an alt="" that would indicate that the image is meant to be "hidden", and therefore the steps would stop at 2.

The HTML AAM topic was referring to images in general that are, by themselves, non-operable user interface components; here instead we are talking about input type="image", which are operable user interface components. That said, considering that the HTML AAM topic also included images wrapped within links, I'm assuming it can be consistently applied to input type images.

Pull request changed
<h4>`img` Element Accessible Name Computation</h4>
        <ol>
          <li>
            If the `img` element has an <a data-cite="wai-aria-1.2/#aria-label">`aria-label`</a> or an <a data-cite="wai-aria-1.2/#aria-labelledby">`aria-labelledby`</a> attribute the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a> is to be calculated using the algorithm defined in <a href="" class="accname">Accessible Name and Description: Computation and API Mappings</a>.
          </li>
          <li>Otherwise use `alt` attribute.</li>
          <li>Otherwise use `title` attribute.</li>
          <li>
            If none of the above yield a usable text string there is no <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a>.
          </li>
        </ol>
in
<h4>`img` Element Accessible Name Computation</h4>
        <ol>
          <li>
            If the `img` element has an <a data-cite="wai-aria-1.2/#aria-label">`aria-label`</a> or an <a data-cite="wai-aria-1.2/#aria-labelledby">`aria-labelledby`</a> attribute the <a data-cite="accname-1.2/#dfn-accessible-name">accessible name</a> is to be calculated using the algorithm defined in <a href="" class="accname">Accessible Name and Description: Computation and API Mappings</a>.
          </li>
          <li>
            Otherwise use `alt` attribute, even if its value is the empty string.
            <div class="note">
              An `img` with an `alt` attribute whose value is the empty string is mapped to the 
              <a class="core-mapping" href="#role-map-presentation">`presentation`</a> role. It has no accessible name.
            </div>
          </li>
          <li>Otherwise, if there is no `alt` attribute use the `title` attribute.</li>
          <li>Otherwise there is no <a class="termref">accessible name</a>.</li>
        </ol>


Topic was not completely closed, and further considerations for naming / exposing images is available here: https://github.com/w3c/html-aam/issues/404

**Comment by giacomo-petri** [comment]
Updates:

In light of @scottaohara clarification at https://github.com/w3c/html-aam/issues/414#issuecomment-1178384158, https://github.com/act-rules/act-rules.github.io/pull/1865#discussion_r916355347 and https://github.com/act-rules/act-rules.github.io/pull/1865#discussion_r916544922 the combination of empty alt attribute and non-empty title attribute gives the input type image a non-empty accessible name through the title attribute. 

In particular, empty alt does not provide a "usable string" for input element with a type image.

In the meantime I've opened a bug for Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1342873
