### ISSUE TITLE
Upgrade to WAI-ARIA 1.2

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1867]
- [x] Update WAI-ARIA specifications definition to use WAI-ARIA 1.2 @WilcoFiers 
- [ ] Accessibility Support for Explicit Semantic Role mentions ARIA in HTML is a working draft, it is no longer one @schne324 
- [ ] Update acc requirements mapping to go to ARIA 1.2 @WilcoFiers 
- [ ] https://act-rules.github.io/rules/6a7281#applicability needs updating, has ARIA 1.1 things @i01000001 
- [x] [Element with role attribute has required states and properties](https://act-rules.github.io/rules/4e8ab6) Update expectation, remove note on default values, and remove exception for default values @WilcoFiers 
- [ ] Update references to HTML in ARIA, indicating it is no longer a draft @schne324

**Comment by Jym77** [comment]
@WilcoFiers Do you want to take over #1700 and #1704 who seems to be related to ARIA 1.2?
(or close them if they are not relevant anymore)

**Comment by Jym77** [comment]
@WilcoFiers It seems that `aria-label(ledby)` being prohibited on a role of `presentation` means that it won't trigger the presentational role conflict resolution anymore. There are several rules that use this as examples…

Can you update them as part of the ARIA 1.2 update?

---
(see https://github.com/act-rules/act-rules.github.io/issues/1853#issuecomment-1195326291 or https://github.com/act-rules/act-rules.github.io/issues/1897#issuecomment-1195321778 for more on this).
