### ISSUE TITLE
Take a look at SC2-4-7-focus-in-viewport.md

### ISSUE THREAD

**Issue by Ryladog** [act-rules/act-rules.github.io#24]
Katie take a look at SC2-4-7-focus-in-viewport.md (https://github.com/auto-wcag/auto-wcag/blob/master/_rules/SC2-4-7-focus-in-viewport.md ). The question is to review it to make it fit into our new template, or just put it into our new template - that is here: https://github.com/WilcoFiers/auto-wcag/blob/b0442b231adc1f6308623ee25f924690b6d0e792/pages/rule-template.md

**Comment by WilcoFiers** [comment]
This rule is outdated. Is related to #415, which should address most of what this rule was trying to accomplish.
