### ISSUE TITLE
Create a "How to ACT-R Github guide"

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#240]
**Note:** Suggesting a new page that we can link to from the "Contribute" page. Suggested outline:

# How to Auto-WCAG Github guide

### reviewing and commenting on pull requests

**Comment by WilcoFiers** [comment]
@annethyme can this be closed?

**Comment by jkodu** [comment]
Closing issue https://github.com/act-rules/act-rules.github.io/issues/317 

Adding the same note here:

> Can we use anything from https://w3c.github.io/ for workflow or documentation?

**Comment by annethyme** [comment]
Siteimprove has created an internal guide that with some cleaning up could serve as a basis for this.
@nitedog has the guide in an email from me sent on May 2, 2019.

**Comment by jkodu** [comment]
@nitedog - progress?

**Comment by WilcoFiers** [comment]
We created the following guide a while back: https://github.com/act-rules/act-rules.github.io/blob/develop/github-guidelines.md
