### ISSUE TITLE
Code examples validity

### ISSUE THREAD

**Issue by audreymaniez** [act-rules/act-rules.github.io#253]
Do we have to write only valid examples ? 

The question came up while writing examples for the PR #245, as we wrote a passed example ([direct link to the discussion](https://github.com/auto-wcag/auto-wcag/pull/245/files#r217337851)): 

````html
<ul role='menu'>
	<li></li> <!-- implicit role -->
	<li role='menuitem'></li>
	<li role='menuitemradio'></li>
</ul>
````
`role='menuitemradio'` require the `aria-checked` property. This test doesnt evaluate the presence of required attributes and, at this time  "we don't care" about that property, but while writting snippet (and passed examples), don't we have to write valid code ? or it is assume somewhere (like a disclaimer), that the snippets we write just present the elements needed to accomplish the test, and no other ?

@annethyme add "Something that in a google search shows up as a passing test case on exactly the thing that you are looking for might very well be copy-pasted as is into real life code..."

**Comment by WilcoFiers** [comment]
@audreymaniez I'm moving this one off the September agenda. We have too many open PRs at the moment. We'll have it for October.

**Comment by EmmaJP** [comment]
Making use of comments, rather than ellipses, should keep the HTML valid for tests, without needing to bulk out the examples.

**Comment by WilcoFiers** [comment]
@audreymaniez We talked it through at the Auto-WCAG meeting. The conclusion is that we agree with your point. Even though it goes against the philosophy of keeping tests as atomic as possible, people tend to copy code without thinking, and so we should make sure the code snippets are complete.

**Comment by audreymaniez** [comment]
@WilcoFiers thank you for the info! (sorry for not having attending the meeting). I agree it makes the code full of information not relevant for **the** rule, but I do agree too it's necessary to deliver conform snippets. 👍

**Comment by jkodu** [comment]
@audreymaniez 

I see you are opening a few PR's for fixing examples. Make sure to link this issue if relevant, so we can see all the fixes from one place.

**Comment by audreymaniez** [comment]
You're right @jkodu. But PRs I open (like #615) are more directly related to the issue #546 opened by Wilco. 

Maybe be we can quote this issue in the #546 and close this issue #253 ? (because both have the same goal in fact) ?

**Comment by WilcoFiers** [comment]
As proposed by @audreymaniez I'm closing this issue in favour of #546.
