### ISSUE TITLE
Definition of "visible on the page" is circular

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#261]
The current definition of "visible on the page" (https://github.com/auto-wcag/auto-wcag/blob/master/pages/algorithms/visible-on-the-page.md) is circular, effectively making itself and all rules referencing it ambiguous 😢

**Comment by WilcoFiers** [comment]
Agreed. This isn't as solid as it should be IMO. Any suggestions for improving this Kasper?

**Comment by kasperisager** [comment]
This might be a start:

> An element is considered to be _visible on the page_ if the element generates one or more layout boxes with non-zero surface areas, is not fully transparent, and resides within an area of the viewport that can be reached via scrolling.

**Comment by Jym77** [comment]
Fun fact: the definition of [visible on the page](https://act-rules.github.io/glossary/#visible-on-the-page) still exists and is not even a definition.

I sort of understand that it should be replaced by [visible](https://act-rules.github.io/glossary/#visible) wherever it's used…

**Comment by Jym77** [comment]
Re-closed by #694 …
