### ISSUE TITLE
Using id's instead of SC+names in URLs for rules?

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#270]
With the current naming scheme for rule files, if we change the name or the success criteria for a rule (which could happen when techniques are updated), the URL changes, and links to that rule will break. 

Could we consider giving the rules an id that is less dependent on the content of the rule?

The examples for the ACT Rules Format uses this approach: https://w3c.github.io/wcag-act-rules/rules/ACT-R1.html

The rules list on https://auto-wcag.github.io/auto-wcag/pages/rules.html will still look the same. It even has id's already (# column).

The change will be visible 
* in the URLs (that will now be stable)
* in the files list (https://github.com/auto-wcag/auto-wcag/tree/master/_rules), where the rules list from https://auto-wcag.github.io/auto-wcag/pages/rules.html will be necessary as a key to finding the right rule when creating new pull requests.

**Comment by EmmaJP** [comment]
The group who met today voted that if this is something to change, which we also felt it might be, it is something to change now, not later. Agreed the face to face meeting would be a good place to figure out a solution.

**Comment by WilcoFiers** [comment]
During the F2F meeting, the conclusion was that we want to rename all of the rule files (which serve as their IDs) to a 6 character lower case alpha-numeric value. for example “i38ao3”

**Comment by annethyme** [comment]
@jkodu, how far are we from being able to implement this?

I have started doing it for my new rules, just using https://www.browserling.com/tools/random-hex to generate an id. 

I guess we need to: 

1. Create a procedure for generating new (and unique) ids for new rules that people start up.
2. Change rule template to have room for id.
3. Change file names of old rules, add id's to the template for existing rules, and ensure the website doesn't break when doing it - and ensure both name of rule and id are visible in overviews and on rule pages.
4. Update documentation so contributors know how to use the ids, e.g. when creating issues for published rules.

**Comment by jkodu** [comment]
This is completed.
