### ISSUE TITLE
What to do about MathML?

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#312]
Previously brought up in: https://github.com/auto-wcag/auto-wcag/pull/231#discussion_r223370534, https://github.com/auto-wcag/auto-wcag/pull/311#discussion_r226982316, and https://github.com/auto-wcag/auto-wcag/pull/233#discussion_r226979242

Some of our ARIA related rules currently consider MathML in addition to HTML and SVG, yet others don't. We need to decide whether we want to consider MathML or not and this should be consistent across rules.

**Comment by kasperisager** [comment]
Additional input: Given that we've decided to _explicitly_ take Shadow DOM into consideration, which perhaps has even poorer support than MathML in terms of browser usage, I do think it would make perfect sense to also consider MathML.

**Comment by annethyme** [comment]
@kasperisager, @carlosapaduarte, Mary Jo and Anne thinks that we should consider MathML in the rules. We just need to note in the accessibility support section that there is limited support for MathML.

**Comment by annethyme** [comment]
NEXT ACTION: Create PR against all of the other rules fixing applicabilities so that: 
- most rules apply to HTML and SVG elements
- aria "spell checking rules" apply HTML, SVG and MathML elements

**Comment by annethyme** [comment]
@jeankaplansky, do you have any advice on whether the above "next action" decision makes sense? Wilco says you know your MathML :)

**Comment by kasperisager** [comment]
Discussed this with @WilcoFiers and we agreed that we should revisit it in the future when MathML gains wider support.

**Comment by WilcoFiers** [comment]
Closing this issue. We can revisit this when someone proposes MathML rules.
