### ISSUE TITLE
How to get more people involved in Auto-WCAG

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#331]
## Audiences: 
- People who want to review rules
- People who want to contribute rules
- People who want to implement rules 

## For people who want to review rules
- Instructions for the rule writer on how to re-request reviews

## For people who want to contribute rules
- 

## For people who want to implement rules 
- What is coming up?

### Weekly email digest
- Push communication about what rules are there for review (new + almost done)

### Guides for the different audiences mentioned above
Two audiences for each guide: 
- recurring user, who just needs a quick reminder about the steps
- first-time user, who needs in-depth walk-through - need expandable sections (or links out to a fuller description) + videos in time

### Clean up Github repository
Transparent file/folder structure

### Workflow
Making it easier for people to suggest rules 

First stage in project board: Proposed 
Second stage in project board: To do

### Make rule creation easier
- Templates when creating new files, atomic/composite
- "Create new atomic rule", "Create new composite rule" etc. directly on the .io website?

### Rejected rules
Last stage in project board: 

## Other
Time horizon: 
- Before end of 2018

Communicate this goal with our work: Systematising rules in order to increase automations

**Comment by annethyme** [comment]
Next step for work on process improvements and stuff:

@nitedog, @jkodu and @annethyme will head it up.

Volunteers for giving input/feedback:
- @john-urbilog 
- @maryjom 
- (@EmmaJP)

**Comment by WilcoFiers** [comment]
@annethyme it doesn't look there is any action on this. Closing this. Feel free to reopen when you have time to revisit.
