### ISSUE TITLE
Atomic rules

### ISSUE THREAD

**Issue by jorgeponto** [act-rules/act-rules.github.io#338]
Atomic rules need to be more atomic. For example:
<img alt="something"> is a test rule
<img title="something"> is another test rule
<img aria-label="something"> is another test rule.
<img alt="" />
<img alt="foo" title="bar">

Actually all these in one rule alone.

**Comment by jkodu** [comment]
@jorgeponto I am closing this issue.

If this is still relevant, please re-open & add more context to the same.
