### ISSUE TITLE
New Rule Proposal: Color Contrast

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#405]
**Name:** `color contrast`

**Description:** make sure the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds.

**Success Criterion:** [SC 1.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/complete#visual-audio-contrast-contrast)

**Comment by annethyme** [comment]
See also old proposal: https://github.com/auto-wcag/auto-wcag/issues/48

**Comment by jkodu** [comment]
Issue https://github.com/act-rules/act-rules.github.io/issues/571 tackles for this requirement. Closing PR.
