### ISSUE TITLE
New Rule Proposal: Table Head Element Has Data Cells

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#407]
**Name:** `table head element has data cells`

**Description:** that each table header in a data table refers to data cells.

**Success Criterion:** [SC 1.3.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/complete#content-structure-separation-programmatic)

**Comment by Brynanders** [comment]
What about this table?

<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>
<table>
<thead>
<tr>
<th scope="col">Col 1</th>
<th scope="col">Col 2</th>
<th scope="col">Col 3</th>
</tr>
</thead>
<tbody>
<tr>
<td colspan="3">Sub header</td>
</tr>
<tr>
<td>Data 1</td>
<td>Data 1</td>
<td>Data 1</td>
</tr>
<tr>
<td>Data 2</td>
<td>Data 2</td>
<td>Data 2</td>
</tr>
<tr>
<td>Data 3</td>
<td>Data 3</td>
<td>Data 3</td>
</tr>
<tr>
<td colspan="3">Sub header 2</td>
<tr>
<td>Data 4</td>
<td>Data 4</td>
<td>Data 4</td>
</tr>
<tr>
<td>Data 5</td>
<td>Data 5</td>
<td>Data 5</td>
</tr>
<tr>
<td>Data 6</td>
<td>Data 6</td>
<td>Data 6</td>
</tr>
</tr>
</tbody>
</table>
</body>

</html>

**Comment by jkodu** [comment]
PR in place for the same - https://github.com/act-rules/act-rules.github.io/pull/417
