### ISSUE TITLE
Put IDs in rule frontmatter, rather than get it form the filename

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#422]
While I still like the idea of having "random" IDs, having random filenames probably isn't the best idea. It makes it difficult to look through the repository and find the rules you're working on. So instead I propose we do the following:

- Add an "id" field to the frontmatter of rules
- Use an abbreviation of the title as the file name

**Comment by annethyme** [comment]
@WilcoFiers, what is "frontmatter"?

And could we ALSO include the id in the filename to make it easy to search for?

**Comment by WilcoFiers** [comment]
TODO: come up with a schema for rule filenames, should include the ID as well.

**Comment by jkodu** [comment]
This is completed now.
