### ISSUE TITLE
Are iframes part of the accessibility tree? (#included-in-the-accessibility-tree)

### ISSUE THREAD

**Issue by carlosapaduarte** [act-rules/act-rules.github.io#425]
Following the discussion raised by @jorgeponto we need to agree on how rules process the content of iframes, i.e., is such content part of the accessibility tree or note? Probably, the outcome of this discussion should be made clear in the definition of `included in the accessibility tree`

**Comment by kasperisager** [comment]
From the HTML AAM (https://www.w3.org/TR/html-aam/#dfn-sub-document):

> __Sub-document__
>
> Any document created from a `<frame>`, `<iframe>` or similar mechanism. A sub-document may contain a document, an application or any widget such as a calendar pulled in from another server. In the accessibility tree there are two accessible objects for this situation—one represents the `<frame>`/`<iframe>` element in the parent document, which parents a single accessible object child representing the spawned document contents.

As such, both `<iframe>` elements and their contents will be part of the accessibility tree unless either has been explicitly excluded. It is up to each individual rule to account for this and many already do. For example, https://auto-wcag.github.io/auto-wcag/rules/SC4-1-1-unique-id.html states that each ID attribute should be unique within the scope of its associated document tree or shadow tree. As the contents of an `<iframe>` element would exist within its own document tree, the rule does not end up inadvertently failing IDs that might have been duplicated between the host document and the `<iframe>` contents.

**Comment by WilcoFiers** [comment]
I agree with Kasper on this. @carlosapaduarte want to make a suggestion on how to update the definition to better reflect this?

**Comment by WilcoFiers** [comment]
@carlosapaduarte I believe this question has been answered. Feel free to raise a new issue if you have further questions.
