### ISSUE TITLE
Documentation for permissions levels - and "how to get to next level"

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#443]
It should be clear for contributors what permissions they have, and what to do, if they feel they need more permissions.

**Comment by annethyme** [comment]
Some documentation can be found in this closed issue: https://github.com/act-rules/act-rules.github.io/issues/371

**Comment by jkodu** [comment]
@nitedog - progress?

**Comment by WilcoFiers** [comment]
This issue is very dated. I'm currently documenting what different permissions mean for the group. That should eliminate the need for this issue.
