### ISSUE TITLE
Contributors list in website is incomplete

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#445]
Whilst building the new website, noticed that the contributors list is not complete.

Eg: https://github.com/auto-wcag/auto-wcag/pull/380#discussion_r266776057

Action:
- To update contributors list.

**Comment by jkodu** [comment]
Completed. Also added code logic to flag missing contributors whenever that happens.

**Comment by ShadowBB** [comment]
Where can this contributors page be found?
