### ISSUE TITLE
"Image has accessible name" (23a2a8) has questionable test cases

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#446]
The rule currently lists the following case as inapplicable:

```html
<img alt="W3C logo" aria-hidden="true">
```

However, according to the rule, I'm fairly certain that the case above should be a pass. Firstly, the element is applicable as it's an HTML `<img>` element:

> The rule applies to (HTML `<img>` elements) or (any HTML element with the semantic role of `img` that is included in the accessibility tree).

Parentheses are my own to clarify the separation between the statements. The word "that" refers to "any HTML element with the semantic role of `img`" and the rule therefore applies to HTML `<img>` elements regardless of their inclusion in the accessibility tree, which is what we want. Otherwise, `<img>` elements that have a role of `none` or `presentation` would not be able to pass the rule as such elements would not be included in the accessibility per the Core AAM:

> The following elements are not exposed via the accessibility API and user agents MUST NOT include them in the accessibility tree:
>
> - Elements with `none` or `presentation` as the first mappable role in the role attribute. However, their exclusion is conditional and depends on other factors. [...]

As such, the test case I posted above actually _passes_ the rule as the `<img>` element is applicable and has an accessible name. This does not seem to be entirely intentional though. Thoughts?

**Comment by kasperisager** [comment]
I'd very much like to hear your take on this, @ShadowBB.

**Comment by Brynanders** [comment]
So if we updated the [applicability](https://github.com/auto-wcag/auto-wcag/pull/263/files) to separate out each point like so:

> The rule applies to any HTML `input` element with a [`type`](https://www.w3.org/TR/html/sec-forms.html#dom-htmlinputelement-type) of `image`, or any HTML element with the [semantic role](#semantic-role) of `img`
> Applicable elements must be [included in the accessibility tree](#included-in-the-accessibility-tree), and has an [accessible name](#accessible-name) that is equivalent to the [filename](#filename) specified in the `src` attribute. Difference in letter casing, and forward and trailing whitespace should be ignored.

**Comment by Brynanders** [comment]
I was basing the test case on the information provided as part of the definition for included in the accessibility tree that states

> An example of this is a focusable element with an aria-hidden attribute with a value of true.

I interpreted this as aria-hidden="true" by default removes an element from the accessibility tree and is only included if it has been explicitly given focus.

**Comment by annethyme** [comment]
@kasperisager and I just had a chat about this one and has come up with a suggestion for the applicability:

```
This rule applies to:
- any HTML `<img>` element that is [included in the accessibility tree](#included-in-the-accessibility-tree), unless it has been excluded from the accessibility tree because it is marked as decorative, and
- any HTML element with the semantic role of img that is [included in the accessibility tree](#included-in-the-accessibility-tree).
```

... where "marked as decorative" might need a definition, if it's not enough to link to https://auto-wcag.github.io/auto-wcag/pages/glossary/decorative.html, where the note says: 

> Note: Authors can mark an img element as decorative to indicate that it should be ignored by assistive technology by using either role="presentation", role="none", or alt="". An element should only be marked as decorative if removing the element does not cause a loss of information to the user.

**Comment by kasperisager** [comment]
The first point should be closer to:

> any HTML `<img>` element that is either [included in the accessibility tree](#included-in-the-accessibility-tree) or excluded from the accessibility tree because it is marked as decorative.

**Comment by ShadowBB** [comment]
I am unsure why we want <img> elements with a role of `none` or `presentation` to be applicable to this rule. If they are not then we can simply simplify the note in the expectation (or carry over a part of that note to the applicability).

Whether or not something passes or is inapplicable really doesn't matter that much though in my opinion.

I think we should however make the applicability less ambiguous (make what you did with the parentheses more apparent/explicit, because that is not how I read the sentence at all myself).

**Comment by WilcoFiers** [comment]
Agree with Anne's update + Kasper's addition.

**Comment by kasperisager** [comment]
@WilcoFiers Here's another case I just stumbled upon:

```html
<img alt="Hello world" hidden>
```

This would fail the rule as it indiscriminately applies to all `<img>` elements and requires that they either have a non-empty accessible name or are marked as decorative. Per https://www.w3.org/TR/accname/, accessible names are properties of accessible objects in the accessibility tree and we even state so ourselves in the definition:

> The accessible name is the programmatically determined name of a user interface element that is included in the accessibility tree.

Hidden elements must never be included in the accessibility tree per https://www.w3.org/TR/core-aam/#exclude_elements2. The above `<img>` therefore has no accessible name as it's not included in the accessibility tree and since it isn't marked as decorative it fails the rule 😕 

Come to think of it, the very same thing is actually true for `<img alt="W3C logo" aria-hidden="true">` as well 🤦‍♂
