### ISSUE TITLE
Adding a changelog to rules

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#458]
ACT rules format requires that rules include a changelog and a link to the previous version of the rule:

https://w3c.github.io/wcag-act/act-rules-format.html#change-log

These features currently are not part of auto-wcag rules. We might be able to use the git history somehow to produce this information, but we'd need to get a lot stricter about our commit messages.

There's another question of how we include changes to definitions, since changes need to be listed as a change to the rule.

**Comment by WilcoFiers** [comment]
Talked about it on the group. @kasperisager will be working on a little guidance doc on:
1. How to write good title / body for PRs
2. How to scope a PR

**Comment by jkodu** [comment]
Completed.
