### ISSUE TITLE
AGENDA ITEM, Reviewers wanted

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#462]
Here's the link:
https://github.com/auto-wcag/auto-wcag/pulls?q=is%3Aopen+is%3Apr+review%3Anone

**Comment by annethyme** [comment]
I was actually more thinking about all the things that have Review Required: https://github.com/auto-wcag/auto-wcag/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+review%3Arequired+

**Comment by annethyme** [comment]
... and maybe even better if we filter out the ones that have the "On hold" label: https://github.com/act-rules/act-rules.github.io/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+review%3Arequired+-label%3A%22On+hold%22

**Comment by WilcoFiers** [comment]
I'm finding we are not getting a lot of value out of this recurring agenda item anymore. I'm taking it off.
