### ISSUE TITLE
Clarification about "Final Call" phase

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#463]
We have previously (https://github.com/auto-wcag/auto-wcag/issues/368#issuecomment-463683911) decided that after the rule has its initial 3 approvals, it should go out in a "Final Call" for 2 weeks, where people have a last chance to object to a rule before it is published. 

While trying this out with a few rules, some questions have come up, and this is a suggestion for clarification from @WilcoFiers, @Brynanders and myself, that we would like to discuss with the community group.

### Which rules should have a "Final Call"?
The 2 week "Final call" applies to both:
- new rules, and
- already published rules, where substantial changes have been made.

**Note:** It hasn't been clear whether edits to published rules were included or not. But since edits can change whether a rule is considered implemented or not in a tool or methodology, we would like to send these out for a "Final call" as well.

### Changes that *does* require a "Final call"
Substantial changes, that require a "Final call", are in general changes that can affect the outcome of a rule. 
This includes, but might not be limited to changes that changes, extends or limits the scope of what is considered for these sections: 
- Accessibility Requirements (success criteria)
- Applicability
- Expectations
- Test cases (Passed/Failed/Inapplicable)

### Changes that *does not* require a "Final call"
These changes are considered non-substantial and will not require a "Final call" before being published:
- Editorial changes, that does not change the meaning of a rule (also if it's in the Applicability or Expectations)
- Changes to the Assumptions, Background, Accessibility Support. If changes to these sections seem to impact the possible outcomes of a rule, probably these sections have been misused.

### What happens if the rule is changed *during* the "Final call"
- We suggest allowing edits during the "Final call" phase, so we don't have to send it out too many times. 
- However, this is a subject we might want to pay attention to while we test out the "Final call" phase.

**Comment by annethyme** [comment]
We agreed in the teleconference call that also for changes during the "Final Call" we should evaluate whether the change falls into the category of changes that *do* require a final call, or the ones the *do not* require a final call.

If the changes are substantial, a new final call should be launched after the first one. It is recommended to let the first final call expire first, before launching a new one, to get a broad range of reviewers on board already in the first round to hopefully avoid multiple rounds of final calls for the same pull request.

Reviewers can help out when commenting by noting whether they consider the suggested changes to be substantial or not.

**Comment by WilcoFiers** [comment]
@annethyme can you put together a proposal to put this into the website?

**Comment by annethyme** [comment]
@WilcoFiers, I'll have a look at it some time after April 30, where I have a project deadline looming ;)
I'll remove the Agenda item label until it's a discussion topic again.

**Comment by WilcoFiers** [comment]
OK, no problem.

**Comment by annethyme** [comment]
Now documented on the website as part of https://act-rules.github.io/pages/design/process/
