### ISSUE TITLE
"Filename is valid accessible name" (9eb3f6) should limit its applicability

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#465]
The rule currently applies to all `<input type="image">` elements in addition to any element with a role of `img` and then proceeds to talk about the `src` attribute in its expectations. However, the `src` attribute only has meaning in context of `<input type="image">` and `<img>` elements. As such, the rule should not be applicable to a case such as this:

```html
<div role="img" aria-label="foo.png" src="foo.png"></div>
```

**Comment by kasperisager** [comment]
On a related node, the rule should probably not be applicable to images without `src` attributes or `src` attributes that are equal to the empty string. Consider a case such as this:

```html
<img src="" aria-label="">
```

This is currently undefined behavior as the rule doesn't specify how to handle `src` attributes when either not specified, when equal to the empty string, or when no filename can be determined form the `src` attribute alone. The definition of filename also fails to specify what to do about the empty string. To add to the confusion, consider this:

```html
<img src="?" aria-label="">
```

The `src` attribute would in the above case resolve to the current URL but with all query parameters removed. An entirely hypothetical case, yes, but it serves to highlight an issue.

**Comment by Brynanders** [comment]
@kasperisager are you suggesting the scope be limited to `<input type="image">` and `img`, that have a  `src` attribute?

**Comment by Brynanders** [comment]
<input type="image"> and img, that have a src attribute value that is not the empty string ("")

**Comment by jkodu** [comment]
@Brynanders 

I do not see what is agreed here being reflected in rule here - https://act-rules.github.io/rules/9eb3f6

Were you intending to open a PR for this?

**Comment by Brynanders** [comment]
Hi @jkodu , the applicability is too broad ATM according to Kasper. He is suggesting that we restrict the test target `<input type="image">` and `<img>` elements instead of "any HTML element with the semantic role of `img`"

**Comment by jkodu** [comment]
@Brynanders seems like the above applicability is not reflected in the rule https://act-rules.github.io/rules/9eb3f6#applicability, can you please put in a PR for this?

**Comment by kasperisager** [comment]
Closing this in light of #1273.

**Comment by Jym77** [comment]
I actually think we should keep this open as long as we haven't taken a descision on #1273. (if the decision is to keep the rule, then this issue is still relevant…)

**Comment by kasperisager** [comment]
Fair point 👍
