### ISSUE TITLE
Negative formulation

### ISSUE THREAD

**Issue by audreymaniez** [act-rules/act-rules.github.io#467]
More a general reflexion about how we write tests etc... 

In RGAA we have a writing rule that is not to write test in negative form. This because writing in a negative way can lead testers (manual tester espacially) answer "no" to a test when it is compliant (precisly because of the syntaxic form of the test). 

This is more a question of linguistic/syntaxic format/norm, even logical format.

Really basic example: to the following test

> "That element doesn't have that property"

You will propbably answer:

> "**NO** it doesn't have" 

and 

> "**YES** it does have" (or even "**NO**  it does have").

**The problem is you can anwer by "YES" to a non compliant test (and "No or yes" to a compliant). And that is not a logicial outcome.**

Real example from Auto-WCAG rules 

> **None of the target elements** participate in sequential focus navigation, **nor do they have** descendants in the flat tree that participate in sequential focus navigation

With the writing rule we have in RGAA, It would become, something like that:

> Target elements and their descendants in the flat tree, if any, are excluded from the sequential focus navigation.

Another example, an applicability section with multiple conditions: 

> Any WAI-ARIA required state or property that
> 
>    - is specified on an HTML or SVG element
>   -  is one of the aria-* attributes included in the accessible name computation, or is specified on an element that is included in the accessibility tree or is focusable,
>   -  **is not the empty string ("")**,
>    - **does not have a default value listed under WAI-ARIA implicit value for role**.

The last two conditions are negative. With the writing rule, It would become, something like that: 

> Any WAI-ARIA required state or property that
> 
>   - is specified on an HTML or SVG element
>   - is one of the aria-* attributes included in the accessible name computation, or is specified on an element that is included in the accessibility tree or is focusable,
>   - **is different from an empty string ("")**,
>   - **has a value different from the default value listed under WAI-ARIA implicit value for role.**

**Comment by EmmaJP** [comment]
One of the agreed naming conventions #250 is to use declarative verbs. I think this should help to achieve positive language in the rule names/titles. 

Perhaps resolving this issue will do a similar thing for the descriptions, which I agree should also use declarative verbs and positive language - where meeting the rule is a pass.

**Comment by jkodu** [comment]
@audreymaniez do you still see this as an issue?

**Comment by jkodu** [comment]
Spoke to @audreymaniez, who confirmed that this issue can be closed.
