### ISSUE TITLE
Potential failure techniques for consideration as ACT Rules

### ISSUE THREAD

**Issue by nitedog** [act-rules/act-rules.github.io#469]
@mbgower has some [suggestions for potential failure techniques](https://github.com/w3c/wcag/issues/683) for consideration as ACT Rules.

**Comment by jkodu** [comment]
@WilcoFiers @nitedog 

I see no actionable based from this issue. Can this be closed?

**Comment by WilcoFiers** [comment]
This suggestion has not been picked up after a year. I'm closing this. Anyone who still wants is free to pick it up, but this doesn't need to stay open indefinitely.
