### ISSUE TITLE
Updating the rules format

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#472]
An updated version of the ACT Rules Format is about to get published. This will require us to go back to some of the already published rules and update them. To do this, I'd like to get together a small group of people that takes this task on.

The latest draft can be found here:
https://w3c.github.io/wcag-act/act-rules-format.html

## Open Tasks

- [x] Add a changelog to rules, base on that rule file's commit history
- [x] Add an expandable section to accessibility requirements mapping to show mapping details, see: https://www.w3.org/TR/act-rules-format/#example-fa957b6e
- [x] Add a link to an issues list
- [x] Link input aspects to their definitions
- [x] Rename "Test aspects" to "Input aspects" in the page template
- [ ] Add leading paragraphs to the background section (Todo for @WilcoFiers)
- [x] Make "authors" a subsection of a new "Acknowledgements" section, where we can free-form put in acknowledgements.
- [x] Rename the "Atomic rules" section to "Input rules"
- [x] Add all missing authors to contributors

**Comment by annethyme** [comment]
@WilcoFiers, @carlosapaduarte and @annethyme are meeting on it this week.

**Comment by annethyme** [comment]
Pull request for new template: https://github.com/act-rules/act-rules.github.io/pull/488

**Comment by WilcoFiers** [comment]
@annethyme @jkodu I've updated the issue description to include a list of changes that still need to be made to the rules for them to conform to the CR format.

**Comment by WilcoFiers** [comment]
Worked with Anne and Kasper this morning. What I'd like from the changelog is the following:

- git log narrowed to a specific rule file
  - Needs to work across file name changes
- list the commit message of the change
  - Link to the diff
  - Link to previous version
