### ISSUE TITLE
Review draft SC1-4-3-text-bg-contrast

### ISSUE THREAD

**Issue by EmmaJP** [act-rules/act-rules.github.io#48]
Current rule is at https://github.com/auto-wcag/auto-wcag/blob/master/_drafts/SC1-4-3-text-bg-contrast.md and includes commented notes.

For review purposes:

## Description

This test checks that the text nodes on a page contrast sufficiently with the background, gradient or image behind them.

## Background

- Understanding SC 1.4.3
- Contrast (Minimum) Understanding SC 1.4.3
- G18: Ensuring that a contrast ratio of at least 4.5:1 exists between text (and images of text) and background behind the text
- G145: Ensuring that a contrast ratio of at least 3:1 exists between text (and images of text) and background behind the text
- F24: specifying foreground colors without specifying background colors
- F83: Failure of Success Criterion 1.4.3 and 1.4.6 due to using background images that do not provide sufficient contrast with foreground text (or images of text)

## Assumptions

- Code validates to a published grammar (eg. 4.1.1 and 4.1.2)
- Only checking HTML text nodes, not text in images
- Requires a rendered page (manual steps will require sight)
- Only checking text nodes on a single page at a time

### Selector

Select elements that match the following XPath or Javascript selector:

//*[text()]
node.nodeType = 3;

For each selected item, go through the following steps:

### Step 1

Determine if the text node has an applied/computed "color" property (ie. not default and not a background image or gradient). Record the text-color value; unknown or null if default.

Continue with step 2

### Step 2

Determine if the parent, or another layer or layers behind the text node, has an applied/computed "background-color" (ie. not default and not a background image or gradient) and is not transparent. Record the background-color value or values; unknown or null if default.

Continue with step 3

### Step 3

Check if the recorded text-color value, or background-color value or values, is unknown or null, while the other or others has a color.

if yes, return step3-fail else, continue with step 4

### Step 4

Check if the text-color value and background-color value or values contrast sufficiently for the size and boldness of text. Record all contrast-ratios.

if no, return step4-fail else, continue with step 5

### Step 5

Determine if any other styles are applied to the text node or background element or elements that would affect the colour contrast. For example, background image or gradient, drop-shadow, border or opacity. Record text-styles and background-styles.

if yes, return step5-cannottell else, return step 5-pass

### step3-fail

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Failed
| description | Text node or background has some color property, while the other does not (see F24).

### step4-fail

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Failed
| description | Text node color property and background color property do not contrast sufficiently (for the text size and weight): [contrast-ratio].

### step5-cannottell

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | CannotTell
| description | Further contrast tests are needed for text node and background, because of [text-styles] and/or [background-styles].

### step5-pass

| Property    | Value
|-------------|----------
| type        | TestResult
| outcome     | Pass
| description | Text node and background appear to contrast sufficiently: [contrast-ratio].

**Comment by EmmaJP** [comment]
It would be nice to include Rob in this again if he's willing. This approach might be OK for him as it's not time specific and possibly less time consuming.

I'm trying (and failing) to recall if there were reasons this is still a draft.

**Comment by WilcoFiers** [comment]
Yeah, just drop him an e-mail, see if he's up for it.

**Comment by WilcoFiers** [comment]
> Determine if the parent, or another layer behind the text node, has an applied/computed "background-color" (ie. not default). Record the background-color value; unknown or null if default.

This doesn't have to be the parent I think. What I'd suggest is that we check if there is a single that has a background color set, that fully contains the text. Something like that.

> Check if one recorded value is unknown or null, while the other is a color.

This seems to trigger when there's a background image. That doesn't seem correct. Do we need a separate step to deal with background images / gradients, or with scenarios where the text overlaps two different background colors?

> Determine if any other styles are applied to the text node or background element would affect the colour contrast. Record text-styles and background-styles. (see comments)

I'm not clear what this means. Could we add some examples?

**Comment by EmmaJP** [comment]
Note: need to change "Warning" outcome to a "CannotTell" outcome, in keeping with https://github.com/auto-wcag/auto-wcag/pull/56, and add some tests once a template is documented https://github.com/auto-wcag/auto-wcag/issues/57.

**Comment by EmmaJP** [comment]
Edited the issue description, adding in "For each selected item, go through the following steps:" as with #62

**Comment by EmmaJP** [comment]
Edited the first comment to use the "CannotTell" outcome, and account for the possibility of multiple background elements. Also added something to ensure the initial grab of color values is not from a background image or gradient. 

Even if a text-node or background element has a background image or gradient applied, it should still have a color or background color to fall back on to meet F24.

Step 5 returns a CannotTell suggesting further testing is needed, if a background image or gradient is detected, or any other style that could affect contrast and make testing more complex.

**Comment by EmmaJP** [comment]
Trying this with proposed the Applicable/Expectations format:

## Applicability

The rule applies to any text node within a document.

## Expectations

### Expectation 1  (equivalent of Step 3)

The text node has a color value set, and any element or elements behind it also have a color or background color value set. OR The text node has no color value set and is inheriting a default color value, and any element or elements behind it also have no color value set and are inheriting default color values.

### Expectation 2 (equivalent of Step 4 - are specifics needed, they vary A - AA - AAA)

The text node color value, or inherited default color value, contrasts sufficiently for the size and weight of the text node with all color or background color values, or inherited default color or background color values, of any element or elements behind it.  

### Expectation 3 (equivalent of Step 5 - not meeting this is not a fail)

The text node, and any element or elements behind it, have no other applied styles that would affect colour contrast, such as background image or gradient, drop-shadow, border or opacity.

**Comment by EmmaJP** [comment]
This rule also needs Implementation Tests. What would you suggest @WilcoFiers ?

**Comment by WilcoFiers** [comment]
I'm wondering if we shouldn't break this rule up at the scope level. What I found working on color contrast is that it gets incredibly complicated if you try to break off too much at once. So for this rule, why don't we just limit it to a text node for which a single background color can be determined?

**Comment by WilcoFiers** [comment]
I've put together some test cases as well:
https://codepen.io/wilcofiers/pen/WMQomo?editors=1000

**Comment by annethyme** [comment]
@WilcoFiers, can we close this one as being replaced by https://github.com/act-rules/act-rules.github.io/issues/571 ?

**Comment by EmmaJP** [comment]
Things have moved along and changed so much, I certainly don't have an issue with that.

**Comment by WilcoFiers** [comment]
Jup, closing it.
