### ISSUE TITLE
Provide an option to upload manual implementation results to the repo

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#482]
After completing https://github.com/act-rules/act-rules.github.io/issues/481, we need the ability to submit the audit reports to the ACT-R repository and display them as implementations.

I think the best way to do that is to have an `implementations` directory in the repo, and for each implementation have a separate dir containing all the audit files available for that implemtnation. Example `implementations/rgaa2/image-button-has-accessible-name-evaluation-report.json `

When building the implementations, we need a script that goes through all these directories and pulls out all of the different implementations and counts them for the number of implementations, similar to how automated implementations are counted.

**Comment by jkodu** [comment]
@WilcoFiers 
I believe this is completed now. Implementations thus far have been hosted on separate repositories under the ACT Rules organisation.

For future implementations, this will be coordinated.

If you think, this needs to be re-open, please add what needs to be done around the same.
