### ISSUE TITLE
Should atomic rules be associated via unique id, rather than file name.

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#490]
When renaming the rule files as a part of this PR - https://github.com/act-rules/act-rules.github.io/pull/489, noticed that `atomic_rules` front-matter is inferred by file name.

Question is:
- Will it be better to refer then by their unique ids?

**Comment by annethyme** [comment]
In my opinion, YES.

Example where this was done: https://github.com/act-rules/act-rules.github.io/pull/416/files (probably not in line with how we name files and insert id's anymore, though).

**Comment by WilcoFiers** [comment]
Decided to change to IDs, and add the rule title in a comment.

**Comment by jkodu** [comment]
Done in PR #547
