### ISSUE TITLE
Clean up "Background" section for published rules

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#515]
On the "Background" section, the newest version of the ACT Rules Format reads: 
"The relationship to the relevant reading should be specified."

In our current rules, the background section either just lists the URLs or the titles of the linked documents, but none of them actually specifies how the reading is related to the rule.
This has to be added to all published rules for them to conform to the ACT Rules Format. 

See also https://github.com/act-rules/act-rules.github.io/issues/516 about moving techniques out of the Background section and into the Accessibility Requirements mapping.

**Comment by jkodu** [comment]
Note from ACT Call:

@WilcoFiers & @ShadowBB will work on a proposal for the explainer texts.

**Comment by annethyme** [comment]
Being handled by https://github.com/act-rules/act-rules.github.io/pull/580
