### ISSUE TITLE
How do we link to input rules? Id or filename?

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#517]
Tofday it seems that input rules are referenced via their file name, e.g. "audio-have-transcript-2eb176" (https://github.com/act-rules/act-rules.github.io/pull/501/files)

However, we have in general started using id's as a reference because the file names were found to be unstable as reference points. 

I suggest we start using the id as reference. And then if we really want somethin human readable in the file, make a comment "# (Human readable full name of rule)"

**Comment by WilcoFiers** [comment]
Input rules are linked through IDs. This has been changed. Closing this issue.
