### ISSUE TITLE
Headings mixed up on the rules page

### ISSUE THREAD

**Issue by carlosapaduarte** [act-rules/act-rules.github.io#558]
Looking at heading levels inside the rules page there are some levels that don't make sense:
- The "Rules" heading is h1
- Rule names are h2
- The accessibility requirements' label is h1
- The authors' label is also h1

Also the "ACT Rules CG" menu heading is h2. Not sure if it should be.

**Comment by jkodu** [comment]
@carlosapaduarte 

Believe most of these were fixed as part of this PR - https://github.com/act-rules/act-rules.github.io/pull/552.
