### ISSUE TITLE
Why is author not shown on rule on the website? 

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#561]
On the published rule [Document title is descriptive](https://act-rules.github.io/rules/c4a8a4), @corbb is not showing up as author, even though he is listed as an author in the [code of the rule](https://github.com/act-rules/act-rules.github.io/edit/develop/_rules/document-title-is-descriptive-c4a8a4.md) and is [listed as a contributor](https://github.com/act-rules/act-rules.github.io/blob/develop/package.json).

Does anyone know why?

**Comment by jkodu** [comment]
@annethyme I can see @corbb - https://act-rules.github.io/rules/c4a8a4#acknowledgements
