### ISSUE TITLE
Broken links on website on "Contribute" page

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#562]
All links to the Github repository that I clicked on the [How to Contribute](https://act-rules.github.io/pages/contribute/#feedback-for-ideas-and-early-drafts-issues-on-github) page on the website that I clicked when trying to demo the rules repository for @corbb's team lead to a [Not found](https://act-rules.github.io/pages/contribute/%7B%7Bsite.data.package.bugs.url%7D%7D) page.

**Comment by jkodu** [comment]
All of the rogue links have been fixed.
