### ISSUE TITLE
Closing the Auto-WCAG CG

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#564]
I'd like to pick a date at which we close the Auto-WCAG community group. ACT-R has been open for several weeks now. Everyone that wants to migrate will have had the time.

**Comment by WilcoFiers** [comment]
Decision: Wilco will send out a notification and close Auto-WCAG after 2 weeks.

**Comment by annethyme** [comment]
@WilcoFiers, is this task done so that issue can be closed?

**Comment by jkodu** [comment]
@WilcoFiers closing this, as I believe the previous CG has been closed. If not feel free to reopen.
