### ISSUE TITLE
BUTTONS HAVE AN ACCESSIBLE NAME test should pass input type submit without value

### ISSUE THREAD

**Issue by mraccess77** [act-rules/act-rules.github.io#565]
When an input of type submit is present without a value -- browsers assign an accessible name of "submit" by default.   This test would seem to fail this situation when it actually passes.  I'd suggest we add a pass condition showing <input type="submit">

**Comment by WilcoFiers** [comment]
@mraccess77 This is addressed by the accessible name computation, which when it encounters an input button will get a localised default. I think the rule can be clearer about this though, so I'll add an example to show this.

**Comment by mraccess77** [comment]
@WilcoFiers you might want to check if aXe flags it as I noticed that it did -- so I wanted to make sure that we are all on the same page.  Bryan Garaventa and others are working on an accessible name calculation prototype/test set to make sure browser, ATs, and testing tools agree on the calculation.

**Comment by WilcoFiers** [comment]
@mraccess77 Axe does this correctly. I'm aware of Bryan G's work on this, I actually used their test cases for axe-core's accname implementation: https://www.w3.org/wiki/AccName_1.1_Testable_Statements
