### ISSUE TITLE
Branch name in the template fo PR

### ISSUE THREAD

**Issue by audreymaniez** [act-rules/act-rules.github.io#570]
In the template for PR description, we can read: 

> Guidance for the PR (pull request) creator
> 
> When creating PR:
> Make sure you requesting to pull a issue/feature/bugfix branch (right side) **to the master branch** (left side).

It says the PR has to be merged with the **master** but (or I didn't understand^^) it seems PR are merged with the **develop** branch.

Proposal: Just change that name in the template

> Make sure you requesting to pull a issue/feature/bugfix branch (right side) **to the develop branch** (left side).

**Comment by jkodu** [comment]
PR in place. Closing.
