### ISSUE TITLE
Face to Face meeting, September 2019?

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#578]
As we've done in previous years, I would like to organise a face to face meeting of the ACT-R community again this year. We'll have to look at dates and locations. I'm thinking early September, in the Netherlands. Will be discussed on the next ACT-R call.

**Comment by jkodu** [comment]
My preference would be end of September/ early October.

**Comment by EmmaJP** [comment]
I'm on holiday early September, so early October would suit me better.

**Comment by jkodu** [comment]
@audreymaniez is willing to attend, but cannot make early September

**Comment by annethyme** [comment]
Update: 

ACT Rules CG will hold its face-to-face meeting on 24-25 September 2019
in Copenhagen, Denmark hosted by Siteimprove.

See full invitation and sign up on: https://www.w3.org/community/act-r/act-rules-cg-face-to-face-meeting-on-24-25-september-2019-in-copenhagen-denmark/

**Comment by annethyme** [comment]
Closing now dates are settled. I have opened a new issue for "remember to sign up" to ensure that everyone can find the invitation: https://github.com/act-rules/act-rules.github.io/issues/708
