### ISSUE TITLE
Should assumptions be displayed above applicability

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#581]
This is something that is done in Trusted tester in the baseline:
https://section508coordinators.github.io/ICTTestingBaseline/16AudioVideo.html

Where I think this helps, is to make it more prominent that exceptions exist to rules, and that those need to be looked at before deciding to implement a rule. Also if someone finds an issue with a rule (such as a false positive), probably the first thing they should want to see is the assumptions.

**Comment by jkodu** [comment]
Wilco & Emma to come up with a proposal for this.

**Comment by jkodu** [comment]
Decision is NO.
