### ISSUE TITLE
Be more clear on the meaning of `attribute=value`

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#584]
Many rules use the notation `attribute=value` when referring to attributes with certain values. While this may seem intuitive at first, it quite often masks the complexity of the underlying attribute values. 

For example, many attributes in HTML are so-called [enumerated attributes](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#enumerated-attribute) in which attribute values are mapped to a finite set of possible states. One such attribute is the `type` attribute for the `<input>` element and as such using the notation `type="text"` really means an `<input>` element in the `Text` state (https://html.spec.whatwg.org/multipage/input.html#text-(type=text)-state-and-search-state-(type=search)). However, the values of enumerated attributes are case-insensitive and usually have defaults so both `type=""`, `type="TEXT"`, and `type="foo"` would result in an `<input>` element in the `Text` state.

Some more examples from different rules:

- https://act-rules.github.io/rules/73f2c2#applicability
- https://act-rules.github.io/rules/97a4e1#applicability
- https://act-rules.github.io/rules/bc659a#applicability
- https://act-rules.github.io/rules/6cfa84#applicability
- https://act-rules.github.io/rules/5c01ea#passed-example-2

**Comment by jkodu** [comment]
Note from ACT-R call, proposal to be authored by one of the assignees

**Comment by kasperisager** [comment]
I'd suggest disallowing the notation `attribute=value` altogether to avoid confusion and require that authors be explicit about attribute values instead. Some examples:

- If we're looking for `<input type=text>`, we'd write _`<input>` element in the `Text` state_ and add a reference to the HTML specification on the possible states of the `<input>` element and how to map the `type` attribute to a state.

- If we're looking for `aria-disabled=true`, we'd write _`aria-disabled` attribute with a value that is an ASCII case-insensitive match for `true`_.

**Comment by Jym77** [comment]
What about values that are case-sensitive? (ids, it seems, so how to replace `aria-labelledby=foo`)

**Comment by kasperisager** [comment]
Just leave out "ASCII case-insensitive": _`aria-labelledby` attribute with a value that is equal to `foo`_.

**Comment by EmmaJP** [comment]
Should this be added in to the rule guidance documentation? I'm trying to wrap up #946 so perhaps it could be added as a separate PR after that is merged.

**Comment by Jym77** [comment]
Yes, but we'll make a separate PR.
I'd like to have more data (look a bit more into what we currently do and how we should do it and have us agree on some changes) before writing out guidelines for the future…
