### ISSUE TITLE
Dead link in the rule-template page

### ISSUE THREAD

**Issue by audreymaniez** [act-rules/act-rules.github.io#588]
On the website, [in the rule template page](https://act-rules.github.io/pages/design/rule-template/) , 
the two links "empty atomic rule template" (https://act-rules.github.io/pages/design/rule-template/atomic-template-empty.html) and "rule design"  (https://act-rules.github.io/pages/design/rule-template/rule-design.html) leads to 404.

I suppose: 
-  "empty atomic rule template" should be an anchor to the template available below and so the url be `#atomic-rule-template`
- 'rule design" should lead to this page https://act-rules.github.io/pages/design/rule-design/

**Comment by jkodu** [comment]
PR in place https://github.com/act-rules/act-rules.github.io/pull/649, closing issue.
