### ISSUE TITLE
Typo in Video Has Captions "backed" > "baked"

### ISSUE THREAD

**Issue by Brynanders** [act-rules/act-rules.github.io#590]
Typo in Video Has Captions https://act-rules.github.io/rules/f51b46

Pass example 1 description uses "backed" in stead of "baked". Additionally the word "baked" referring to "baking" as in "bread baking" is a colloquial/slang term used to describe something that is included earlier on or at the beginning of the "baking" process and not after.

Either correct the spelling or use a different word.

e.g.
A video element that has captions for all the audio backed into it.
>
The video element source file includes all of the captions required for the video's audio..

**Comment by jkodu** [comment]
PR - https://github.com/act-rules/act-rules.github.io/pull/650
