### ISSUE TITLE
side bar is not responsive

### ISSUE THREAD

**Issue by nitedog** [act-rules/act-rules.github.io#602]
On my setup, the side bar is only visible when i go into full-screen mode on my office monitor. Maybe I'm missing some hamburger menu or such when the side bar is not visible?

**Comment by jkodu** [comment]
@nitedog 

You should see a hamburger menu like so:

![image](https://user-images.githubusercontent.com/20978252/60601106-70dbd600-9da9-11e9-8030-b59ac05ba21e.png)

Additionally I have tweaked some behavior of the sidebar to adapt to various breakpoints/ media queries.

If you are experiencing problems do reach out directly and or feel free to open the same or another issue with more details.
