### ISSUE TITLE
Broken link https://act-rules.github.io

### ISSUE THREAD

**Issue by jake-abma** [act-rules/act-rules.github.io#608]
Not sure if this is where you want this issue, but at https://act-rules.github.io/pages/about/ there's a broken link at "Who We Are": ACTR Website (https://auto-wcag.github.io/auto-wcag)

Cheers,
Jake

**Comment by jake-abma** [comment]
https://act-rules.github.io/pages/contribute/#give-feedback-on-rules

+ See the ideas and early drafts that might need input (https://act-rules.github.io/pages/contribute/%7B%7Bsite.data.package.bugs.url%7D%7D)

+ Use the Definition of "Done" to guide your review (https://act-rules.github.io/pages/pages/design/definition-of-done.html)

**Comment by jake-abma** [comment]
and more... suggest to check for more!

**Comment by WilcoFiers** [comment]
Thank you Jake!

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/637

Looking into perhaps automating broken links across site as a part of the test run.
