### ISSUE TITLE
Buttons have an accessible name Passed example 4

### ISSUE THREAD

**Issue by Aniort** [act-rules/act-rules.github.io#609]
in Passed Example 4 of rule documentation "buttons have an accessible name", the code of the example displayed is : 
`<span role="button" aria-label="My button"></button>`
it should be : 
`<span role="button" aria-label="My button"></span>`
as in the test case html page https://act-rules.github.io/testcases/97a4e1/36c92faf3ffc34dc7a5820bdefdf5d534fb60e49.html

**Comment by jkodu** [comment]
PR in place, closing issue.
