### ISSUE TITLE
Algorithms "Used in Rules" is ugly and hard to use on smaller screens

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#610]
When I am on my laptop, the "Used in Rules" part of algorithms becomes really weird and hard to read because the column is very narrow, even though there is plenty of room for it: 

![Screenshot 2019-06-17 at 14 28 52](https://user-images.githubusercontent.com/15611692/59604423-67494180-910c-11e9-8da5-46f8db852f0f.png)
(screenshot shows resized window on bigger screen, but behaviour is excactly the same)

https://act-rules.github.io/glossary/

**Comment by jkodu** [comment]
Closing: PR in place - https://github.com/act-rules/act-rules.github.io/pull/636
