### ISSUE TITLE
Outdated links to auto WCAG in composite rules

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#624]
Some composite rules (maybe all, I haven’t checked yet) have correct links to the ACT-R rules in their "Input rule" Section, but still have the outdated links to auto WCAG in their "Expectation" Section.
At least
https://act-rules.github.io/rules/eac66b
https://act-rules.github.io/rules/c3232f
are affected.
I haven’t checked the other composite rules but I guess they might also be affected.

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/627, closing issue.
