### ISSUE TITLE
Input rules are shown in a messy way on Rules page

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#626]
When showing composite rules on https://act-rules.github.io/rules/, the Input rules are shown without anything to seperate them, so it is hard to see where one input rule ends and the next one begins: 

<img width="1354" alt="Screenshot 2019-06-26 at 15 20 04" src="https://user-images.githubusercontent.com/15611692/60183150-fac5f500-9825-11e9-8db6-b09576cf6283.png">

Suggestion: bulleted list (best for overview), or simply a comma separated list (with proper spaces).

**Comment by jkodu** [comment]
Closing as PR is open - https://github.com/act-rules/act-rules.github.io/pull/628
