### ISSUE TITLE
Rule SC2-4-7-focus-in-viewport.html assumes negative offset

### ISSUE THREAD

**Issue by detlevhfischer** [act-rules/act-rules.github.io#63]
I was looking at
https://auto-wcag.github.io/auto-wcag/rules/SC2-4-7-focus-in-viewport.html
Just wondering if the check would catch cases where authors pick large positive offsets to move items to outside the viewport. The problem is clear: the exact size of the viewport is not known.  x=2000px / y=2000px will movce the item outside the viewport but not on very large screens. So it seems this can only be tested for negative offsets - or positive offsets just beyond the currenty available screen resolutions.

**Comment by WilcoFiers** [comment]
The initial thinking on this was that positive offset would be reachable because it could be scrolled into view. That doesn't take clipping into account though, so that's something to consider, but I would say we might want to work out a separate rule for this.

**Comment by WilcoFiers** [comment]
Closing this, as the issue is massively outdated.
