### ISSUE TITLE
ARIA attribute is valid (5f99a7) to apply to elements with a known role, or without any

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#641]
In this comment https://github.com/act-rules/act-rules.github.io/pull/607#discussion_r298148776, @kasperisager correctly pointed out that ARIA doesn't say anything about using `aria-*` attributes not part of the ARIA 1.1 spec.

What it does do however is say which attributes are allowed for certain roles. We already have a rule for that (`ARIA state or property allowed`), but it excludes attributes that aren't part of the ARIA spec. To address this, I propose the following changes:

1. Deprecate `ARIA attribute is valid`

2. Change the applicability of `ARIA state or property allowed` to include any `aria-*` attribute rather then limiting it to known ARIA state and property attributes.

**Comment by jkodu** [comment]
@WilcoFiers can you do this change or give me a heads up as to what needs to happen?

**Comment by jkodu** [comment]
Myself and @WilcoFiers discussed this issue and we believe it is fixed by having no accessibility requirements mapping for this rule.

See - https://github.com/act-rules/act-rules.github.io/blob/develop/_rules/aria-attr-defined-5f99a7.md#L7

**Comment by kasperisager** [comment]
Agreed; my concern was with the requirements mapping 😄
