### ISSUE TITLE
QualWeb implementation reports

### ISSUE THREAD

**Issue by carlosapaduarte** [act-rules/act-rules.github.io#644]
HTML Page has a title report - http://qualweb.di.fc.ul.pt/act_reports/qualweb-2779a5.json
HTML has lang attribute report - http://qualweb.di.fc.ul.pt/act_reports/qualweb-b5c3f8.json
HTML lang and xml:lang match report - http://qualweb.di.fc.ul.pt/act_reports/qualweb-5b7ae0.json
Meta-refresh no delay report - http://qualweb.di.fc.ul.pt/act_reports/qualweb-bc659a.json
Validity of HTML Lang attribute report - http://qualweb.di.fc.ul.pt/act_reports/qualweb-bf051a.json

**Comment by jkodu** [comment]
Thanks for this @carlosapaduarte.
I was wondering if you would like to host them in a separate repository here (like other reports here) - https://github.com/act-rules?type=source.

This will help for easier consumption.

**Comment by carlosapaduarte** [comment]
Yes @jkodu, please do. The name is fine.

**Comment by jkodu** [comment]
@carlosapaduarte I have added the reports here. I will adapt them into implementations in this PR - https://github.com/act-rules/act-rules.github.io/pull/604

So from now any json (valid) added to the above repo, should pick up as implementation statistic everytime the site is built.

I will close this issue. Thanks again.
