### ISSUE TITLE
implicit / explicit semantic role definitions are missing [4e8ab6]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#670]
In `Role has required states and properties`, the terms "explicit semantic role" and "implicit semantic role" are used. Both link to the "semantic role" definition. These are two parts of how to compute the semantic role, but they're not equivalent. Those two terms really should have their own definitions, possibly used in the `semantic role` definition.

**Comment by Jym77** [comment]
Closed by #689.
