### ISSUE TITLE
Glossary-to-glossary links broken

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#672]
It seems that we have 3 "glossary-to-glossary" links that are broken…

* [matching characters](https://raw.githubusercontent.com/act-rules/act-rules.github.io/develop/pages/glossary/matching-characters.md) links to the non existing `[characters](#character)`.
* [text-content](https://raw.githubusercontent.com/act-rules/act-rules.github.io/develop/pages/glossary/text-content.md) links to both non-existing `[rendered text]: rendered-text.html` and `[text alternative computation]: text-alternative.html`

We probably want to check glossary-to-glossary links, same as we check rule-to-glossary links.
(but I'm keeping it as a separate issue so we can close #634 in the meantime…)

We also should use a single way of writing these links (and not using once `#character` and once `rendered-text.html`). According to the (working) link in [visible-text-content](https://raw.githubusercontent.com/act-rules/act-rules.github.io/develop/pages/glossary/visible-text-content.md), the first one seems to be correct.

**Comment by jkodu** [comment]
@annethyme, @Jym77  - do we know if #character definition is being authored elsewhere in any other PR?

**Comment by jkodu** [comment]
Partial PR - https://github.com/act-rules/act-rules.github.io/issues/672

**Comment by Jym77** [comment]
> @annethyme, @Jym77 - do we know if #character definition is being authored elsewhere in any other PR?

I don't know.
