### ISSUE TITLE
"Used in composite rules" for atomic rules

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#673]
It would be nice to backlink from atomic rules to the composite rules they are part of, like for the Glossary terms. Maybe as part of the "background" section. 

Discussed in teleconference on July 11. ACT-R CG agreed that it is a good idea to have backlinks, but it has to be figured out how we want it done.

**Comment by jkodu** [comment]
Should go under: Accessibility Requirements Mapping

**Comment by jkodu** [comment]
@Jym77 do you want to take on this one?

**Comment by Jym77** [comment]
> @Jym77 do you want to take on this one?

Yes. Can do.

**Comment by Jym77** [comment]
Closed by #707
