### ISSUE TITLE
Show Conformance Level for WCAG SC on Rules page

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#675]
Can we show the conformance level for WCAG success criteria already along with the title of the success criterion on the Rules page?

<img width="1372" alt="Screenshot 2019-07-12 at 12 49 00" src="https://user-images.githubusercontent.com/15611692/61122984-78833500-a4a3-11e9-9b87-5a7fdbac4332.png">

... and on the pages for the individual rules?

Kind of like we do in the comments on the success criterion name when we write the rule:

<img width="1426" alt="Screenshot 2019-07-12 at 12 50 34" src="https://user-images.githubusercontent.com/15611692/61123082-b718ef80-a4a3-11e9-8f17-bad80cb4cb48.png">

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/677. Closing issue.
