### ISSUE TITLE
Changing file name will dismiss all reviews

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#681]
For rule https://github.com/act-rules/act-rules.github.io/pull/255/ we changed the filename to follow the new naming convention, and that dismissed the two approving reviews that were already on the pull request. It now just says in the Conversation tab that "XXX reviewed Y hours ago" without giving any information on whether the review was an Approved/Changes Requested/Comment. 
The only way to find out what the original review said, is apparently to dig out the status mail sent when the review originally happened.

I guess the dismissal on file name change has to do with the settings of the repository. 

Since we don't automatically dismiss reviews with any other change to a pull request, I don't think we should do it either for file name changes.

**Comment by jkodu** [comment]
Hi @annethyme, unfortunately git UI for comments do not use the `--follow` tag thereby losing all the history before the filename changes. I cannot think of a workaround for the same.

**Comment by annethyme** [comment]
It seems that the dismissal of approvals is not limited to just changing file names. It seems that ANY CHANGE will now result in a dismissal of all reviews.

E.g.: ShadowBB approved #447 22 hours ago. I did two editorial fixes ("an" --> "a" and "L" --> "l") per review from carlosapaduarte - and then the review from ShadowBB  is now registered as a comment, not an approval anymore. 

Has any changes been made to the settings, @jkodu and @WilcoFiers?

It might in some ways be great with a stricter approach towards keeping approvals even when changes are made, but right now it just seems impossible to get 3 approvals, if I have to start all over again every time someone catches a typo.

**Comment by jkodu** [comment]
GitHub allows only 2 options
- either reset the approvals after a commit
- do not reset approvals after a commit

We cannot configure things like, only reset approvals when commit is not typo, for example.

**Comment by annethyme** [comment]
But up until now we have had it set to "do not reset approvals after a commit". I am not aware that a decision has been made to change this, and right now it blocks us from ever getting 3 approvals. 
If it hasn't been agreed to change the settings, can we then change it back to what we have initially agreed upon, so that it again works like we are used to?

**Comment by EmmaJP** [comment]
If approvers also +1 the CFC, does that deal with the issue of approving something that may have changed?

**Comment by jkodu** [comment]
Updated the settings accordingly. Closing.
