### ISSUE TITLE
What is the process for handling incoming issues?

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#696]
It might be that we have a process that I am just not aware of, but to me it seems that there are a lot of issues reported for published rules that are never discussed or assigned to anyone. 
Is there already a process for handling incoming issues and following up on old ones? 
And if not, should we agree on how to do it?

**Comment by WilcoFiers** [comment]
Wilco to meet with Jean-Evys and Jey for ACT-R Grooming.

**Comment by jkodu** [comment]
This is happening and some issues are closed.

We will set up a bi-monthly recurring grooming session.
