### ISSUE TITLE
Can we show rule IDs on the Rules overview page?

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#704]
Would make it easier for me when I am searching for a specific rule.
Now I have to open another rule and edit the URL to find a rule, if I only have the ID to go by.

**Comment by jkodu** [comment]
I think this is a good idea. 
I also think some kind of filtering should be added to the rules page.

**Comment by jkodu** [comment]
This will be solved by filtering panel, https://github.com/act-rules/act-rules.github.io/issues/709.

So closing this.
