### ISSUE TITLE
Update "Rule Design" page

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#706]
The Rule Design page, https://act-rules.github.io/pages/design/rule-design/, is really outdated.

Suggested updates: 

Introduction:
- Link out to ACT Rules Format, https://www.w3.org/TR/act-rules-format/

Rule name and identifier:
- Remove things about having identifiers in this form: SC#-#-#
- Add advice on how to generate a hex code as id for the rule
- Add advice on naming of rules (see https://github.com/act-rules/act-rules.github.io/issues/250) 
- Use of backticks (yes/no)
- Use of capitalization

Description (Add section for this): 
- Advice on the form of it ("This rule checks..."
- Use of backticks (yes/no)
- Linking to definitions (yes/no)

Test aspects: 
- Change section title to "Input aspects"
- Link out to https://www.w3.org/TR/act-rules-format/#input-aspects 
- Point out that Input aspects are only for atomic rules, and that composite rules have "Input rules", see https://www.w3.org/TR/act-rules-format/#input-rules

Authors: 
- Change advice about adding to contributors file - since that one no longer exist. 

Assumptions:
- Link out to https://www.w3.org/TR/act-rules-format/#assumptions

Applicability: 
- Link out to https://www.w3.org/TR/act-rules-format/#applicability

Expectations: 
- Link out to https://www.w3.org/TR/act-rules-format/#expectations

New Section with a general style guide for rules?
- When using words that are definitions, they should always link out to the definition (all occurrences of the word).
- avoid abbreviations unless extremely well-known by everyone reading the rule. Our audience could be QA testers as well as accessibility experts. (so WCAG for Web Content Accessibility Guidelines is okay. SC for success criterion, or AG for Accessibility Guidelines Working Group is not).

**Comment by Jym77** [comment]
We've had update to the document fairly recently (March 2020) and I think this is now reasonably up-to-date. 
We can probably close this.
@WilcoFiers ?
