### ISSUE TITLE
REMEMBER: Sign up for face-to-face meeting 24-25 September 2019

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#708]
ACT Rules CG will hold its face-to-face meeting on 24-25 September 2019
in Copenhagen, Denmark hosted by Siteimprove.

See full invitation and sign up on: https://www.w3.org/community/act-r/act-rules-cg-face-to-face-meeting-on-24-25-september-2019-in-copenhagen-denmark/

**Comment by Jym77** [comment]
Too late to sign up now!
