### ISSUE TITLE
Test asset missing for "Video has captions" (f51b46)

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#718]
In rule [Video has captions](https://act-rules.github.io/rules/f51b46), three examples are referencing the file `../test-assets/perspective-video/perspective-keyboard-compatibility-video.mp4` which does not exist.

I sort of guess this should be one of the other video files, but I don't know which one…

Less problematic, `perspective-video-with-captions-silent.mp4` is present but never used.

@WilcoFiers @ShadowBB you're authors of this rule, can you check what happened?

@jkodu can we test for missing or unused test assets?

**Comment by jkodu** [comment]
I have reached out to @ShadowBB for missing assets.

**Comment by ShadowBB** [comment]
Yeah. In all 3 cases it should simply be "perspective-video.mp4"

**Comment by jkodu** [comment]
@Jym77  `perspective-video-with-captions-silent.mp4` is used in other media rules. I will fix the other one

**Comment by jkodu** [comment]
PR [https://github.com/act-rules/act-rules.github.io/pull/731] in place.
