### ISSUE TITLE
Implementation reports not showing correct results

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#729]
The implementation on this page shows an "expected: passed, actual: failed":
https://act-rules.github.io/implementation/axe-core#b5c3f8

This implementation should not show up as a correct implementation of that rule.

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/733
Given number of incomplete implementations identified, several reports have to be updated by various authors.
