### ISSUE TITLE
Implementation shown as complete with untested results

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#730]
This implementation is shown as complete, even though it has two "expected: passed, actual: untested"
https://act-rules.github.io/implementation/access-engine#97a4e1

**Comment by jkodu** [comment]
@WilcoFiers this seems to be a discrepancy between the the report provided here https://github.com/act-rules/act-rules-implementation-access-engine/blob/master/report.json and the actual number of testcases for this rule.

The last 2 testcases are missing implementation test case. 

I have reached out to Level Access for the same. 

Let me know if you have any ideas to proceed in the meantime.

**Comment by jkodu** [comment]
Is it worth marking reports with untested test cases as incomplete?

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/733
Given number of incomplete implementations identified, several reports have to be updated by various authors.

**Comment by jkodu** [comment]
PR #733 in place. Closing this.
