### ISSUE TITLE
Video has captions (f51b46) test cases refers to non-existent test-assets

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#732]
When creating tests for our semi-automated implementation of the rule Video has captions, our tester found some issues with the referenced test assets. 
This might already have been discussed with the authors of the rule (@WilcoFiers and @ShadowBB), but since I can't find an issue on it, I will raise it here.

In the rule Video has captions, three test cases are referencing the file `../test-assets/perspective-video/perspective-keyboard-compatibility-video.mp4` which does not exist.

We think it should be the file `../test-assets/perspective-video/perspective-video.mp4`, but are not completely sure.

**Comment by jkodu** [comment]
@annethyme I fixed these yesterday & in this https://github.com/act-rules/act-rules.github.io/pull/731 PR you will see the other issue that existed for the same.

Closing this as a PR exists.
