### ISSUE TITLE
"See file at given version" in Changelog seems to be broken for updates before end of April

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#734]
On rule https://act-rules.github.io/rules/2779a5, the older items in the Changelog has broken links for "See file at given version"

> Apr 29, 2019 | chore: rename files and update associations (#489) **<-- WORKS**
> 
> Apr 16, 2019 | chore: add unique id to all rules (#478) **<-- Gives a 404**

If it's because we don't have anything to link to, could we just remove the links?

**Comment by jkodu** [comment]
Good catch, this has happened due to file name changes between 2 commits. 
But I will research if this can be fixed easily.

**Comment by jkodu** [comment]
Action for @jkodu - remove column on changelog for see file at version.

**Comment by jkodu** [comment]
This PR - https://github.com/act-rules/act-rules.github.io/pull/787 removes the column which allows to see file at given commit.
