### ISSUE TITLE
Add notes on interpretations in rule "HTML Page has a title" (2779a5)

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#735]
From the ACT TF: [HTML has title rule](https://act-rules.github.io/rules/2779a5) should have notes documenting the following:

There is an interpretation made that it is okay that `title` elements are not placed in the `head` of the document, which they should be according to the HTML spec. The reason for allowing this is that testing showed that modern browsers don't care where the `title` element is located. 
This was however a big discussion item because it goes against what many considers to be the correct way of testing for this SC, so it would make sense to document it in Assumptions instead of just creating passing test cases for the scenario. 

There is also an interpretation that it is okay to have multiple `title` elements, which is also not currently widely accepted across accessibility testers.

**Comment by EmmaJP** [comment]
We check for valid HTML as a first step before running any other checks. I think the permutations for rules / test-cases become too plentiful to cover otherwise.

**Comment by jkodu** [comment]
PR in place, close issue.
