### ISSUE TITLE
Can we split website and rules up into two different repositories?

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#757]
... to ease the clutter on the PR page and make it more clear what is up for review by the rule writer community.

**Comment by jkodu** [comment]
That is additional overhead Anne.
Discussed with @WilcoFiers & we believe it will add more complexity to the way the site is built.

Closing Issue.

**Comment by EmmaJP** [comment]
If _rules is the only folder someone is involved with, can they limit notifications etc to just that folder?

Is it possible to group all the other website specific stuff into a _website folder, or would that also be too much overhead?

Just wondering.
