### ISSUE TITLE
Don't use / allow URLs as link text

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#761]
We have quite a number of rules that use the URL as link text. This is especially common in the background section. We need to make sure that all links have a meaningful link text. This requires two things.

1. Fix all of the instances where a rule has URLs as link texts

2. Write a test that checks a rule for URLs as link texts (in a separate PR)

**Comment by jkodu** [comment]
PR - https://github.com/act-rules/act-rules.github.io/pull/776
