### ISSUE TITLE
Missing definition of "character" linked to from "matching characters" definition

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#783]
See https://act-rules.github.io/glossary/#matching-characters. "Character" is a link to https://act-rules.github.io/glossary/#character, but no such definition exists.

**Comment by annethyme** [comment]
For "character" definition, http://www.unicode.org/reports/tr10/#Canonical_Equivalence could be used.

**Comment by jkodu** [comment]
Note:

@Jym77 is going to remove a link above...

**Comment by Jym77** [comment]
closed by #845
