### ISSUE TITLE
Create tests for verifying hyperlinks used in rules

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#784]
Create tests to check links used in rules:
- if they are broken links
- if link text is URL as against a valid name
- if link refers to only of the below outdated resources
   - WCAG20
   - Please add links that should not be referred.

**Comment by Jym77** [comment]
Other outdated resource: https://www.w3.org/TR/dom41/ (instead of https://dom.spec.whatwg.org). There's currently a redirection, but we may still rather use the correct URL…

**Comment by jkodu** [comment]
Have a PR in place.
