### ISSUE TITLE
Split up the repository of website vs the rules

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#786]
**Problem**
Given the number of changes happening in the repository which are not just related to rules authoring, like:
- chore like dependency managements
- chore like website layout updates
- new functionality in the website
- implementation related changes

This causes a lot of chattiness in the number of pull requests that are not just rules related. Sadly this also affects the changelog of the rules.

**Solution**
Split the repositories
- A repo for rules, glossary (markdown files)
- A repo for website stuff

This is not new, we already pull implementations from various other repositories, but it is quite a bit of work to get this architected.

**Comment by jkodu** [comment]
I believe @annethyme had an issue for this in the past.

A proposal for doing this would be:
- Create a new repo `act-rules-website`
- Extract everything that is `gatsby` static site generation related into the repository.
- Make the website repo a dependency of the rules repository
- Build the website from the rules repository by passing the necessary arguments to directories and files necessary for static site generation.

How to solve:
- Gatsby expects directories as a part of the configuration from which rules, pages, glossary, test assets etc, can be parsed. This is configured for plugin `gatsby-source-filesystem` in https://github.com/act-rules/act-rules.github.io/blob/develop/gatsby-config.js#L62.
- If these can be passed as arguments from the rules repository, then the website can be built.
- The output of the generated website should be places on the top level of the rules repository in a `public` directory. This will allow for using the same CI process for deploying the website.

**Comment by Jym77** [comment]
@jkodu 
> * Make the website repo a dependency of the rules repository
> * Build the website from the rules repository by passing the necessary arguments to directories and files necessary for static site generation.

As much as possible, I'd rather go the other way around: have the rules be a dep of the website and build the website from the website. Reasons:
* website must know about rules, rules can ignore website, so the dep is more logical that way.
* building from rules using code in another repo seems quite the wrong way around to me.
* part of the goal of this split is to keep the rules repo free from anything that is not rules (in order to have rules writers concentrate on rules writing), so ideally we should only keep the markdown (and test assets) in the rules repo.

**Comment by jkodu** [comment]
The actual splitting of the repository is complete.
What is pending is the engineering required to both trigger a new build of the website when the rules repository changes, as well as publish the changes back to the rules repository.

I have created granular issues for this & therefore closing this.
