### ISSUE TITLE
When are "Authors" deprecated?

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#799]
Do we keep the original author(s) listed on a rule when some one else has made changes to the rule? 

Also if the original author(s) haven't even reviewed the new rule and therefore no one knows if they would still agree to the rule that has their name listed as an author?

Other suggestions would be: 
- having to dig into the change log to find out who was listed as rule writers originally
- Splitting up the authors list into "authors for this version of this rule" and "authors for previous version(s) of this rule"

**Comment by annethyme** [comment]
One real world example of this is https://github.com/act-rules/act-rules.github.io/pull/447 where the rule has changed substantially, and only one of the original authors have been involved in these changes. 
The question actually came up because it was asked whether the original co-authors can serve as reviewers (and count towards 3 approvals) in iterations of the rule.

**Comment by WilcoFiers** [comment]
Opened an issue for this on the website.
