### ISSUE TITLE
Update Documentation on website

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#804]
The pages under "Documentation" on [the website](https://act-rules.github.io/pages/about) are in different stages of unfinished (e.g. the [Process [DRAFT]](https://act-rules.github.io/pages/design/process/)), or outdated (e.g. [Rule Design](https://act-rules.github.io/pages/design/rule-design/) doesn't match current naming conventions and does not link to ACT Rules Format where relevant).

I suggest making a master plan for the documentation needed, and then updating (or removing) accordingly).

**Comment by jkodu** [comment]
Duplicate - https://github.com/act-rules/act-rules.github.io/issues/183
