### ISSUE TITLE
Embrace tabs to split out contents of rule page

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#807]
Currently we have a lot of content in a given rule page (Eg: see https://act-rules.github.io/rules/73f2c2), thereby resulting in a long page.

Would the group be open to introducing tabs to split out the content of the page.

Something like below

```
Rule Name as heading
________________
| Rule Details | Test Cases | Changelog

- Rule meta data 
- Description
- Applicability
- ...

```

The tabs being 
- Rule Details
- Test Cases
- Changelog

Thoughts welcome.

**Comment by jkodu** [comment]
This would also solve for - https://github.com/act-rules/act-rules.github.io/issues/480

**Comment by annethyme** [comment]
Not sure about the tabs idea, but if we do it, I think there should be tabs for at least the Issues list too, and maybe the Glossary.

**Comment by jkodu** [comment]
Decided not to use tabs.
