### ISSUE TITLE
Check for broken glossary-to-glossary links

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#829]
We check if glossary links used in rules actually refer to existing glossary items. This is however not the case for glossary links used in glossary items, as shown in #783.

We should add a test for this.

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/857

**Comment by jkodu** [comment]
See comment - https://github.com/act-rules/act-rules.github.io/pull/857#issuecomment-529893002
