### ISSUE TITLE
Image has accessible name (#23a2a8) need aria-labelledby example

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#830]
Rule [image has accessible name](https://act-rules.github.io/rules/23a2a8) could use an example with a label given by `aria-labelledby`.

**Comment by WilcoFiers** [comment]
Could you create a PR for this @Jym77

**Comment by Jym77** [comment]
Will do.

**Comment by Jym77** [comment]
Closed by #831
