### ISSUE TITLE
Unifying example descriptions

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#834]
Examples description varies wildly from rule to rule, and also inside a rule…

* Ending the sentence is sometimes done with a full period (`.`), sometimes with a colon (`:`) and sometimes with nothing at all. We should always do it the same way.
(I'm roughly counting 438 periods, 19 colons and 103 nothing, numbers are not 100% accurate, seems to indicate that period is the preferred way)
* Use of "this" + declarative form (notably in failed examples).
"this element has no foo" vs "element without foo"
* fully qualifying entities
"the attribute `foo` is blah blah" vs "`foo` is blah blah"
* naming elements/attributes
"this `a` element" vs "this element"
"a set of two links that blah blah" vs "links blah blah"
* others… I'm sure there are more…
* descriptions have to be precise: e.g "`title` element" instead of "`title`"
* front-load the description with the applicable "thing". "This X element has a Y" instead of "Y is available on element X"

I guess it's a quite huge task but we should at least:
* agree on some general rules on how to write these descriptions
* probably document these guidelines in a "how to contribute" page (same as we should document the guidelines for rule names of #250) 
* Keep that in mind when writing/reviewing/updating rules so that the overall quality increases.

I think that having inconsistent wording for descriptions, especially when it's often barely even a real English sentence, is really bad for the overall quality of the rules.
(often, the "description" of examples look more like a short bullet list of all cases that need to be written, intended for a co-writer rather than for further readers…)

## preferred format

This [test target] [meets / does not meet condition] [because optional reasons].

Examples of [test target]:
- `button` element
- `div` element with [semantic role](#semantic-role) of `button`
- `aria-required` property
- `id` attribute
- page

Examples of [meets / does not meet condition]:
- has an accessible name
- does not have an accessible name
- contains a `title` element with content
- have the same accessible name and embed the same resource

Example of [because optional reasons]:
- given by the `alt` attribute
- because it is not [visible](#visible)
- even though the referenced element is not yet in the DOM

**Comment by jkodu** [comment]
Come up with some guidelines on how to author test case descriptions for newly authored rules.

@Jym to come up with a proposal.

**Comment by EmmaJP** [comment]
Should this be part of what feeds into #946?

**Comment by Jym77** [comment]
@EmmaJP I've been wondering the same 😄

**Comment by Jym77** [comment]
The guidelines have now been included in the rule design document. Closing this.
