### ISSUE TITLE
Reduce the Final Call period to 1 week

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#844]
Originally, the final call was intended as an opportunity for implementors to adopt rules, which is why we decided on a 2 week final call period. I haven't seen much evidence of this happening, and speaking as a product owner of one implementor, I would also say that 2 weeks isn't nearly enough time for that.

To be able to more quickly iterate, especially with rules going to the ACT Task Force, I think it would be beneficial to reduce the final call period to 1 week.

**Comment by jkodu** [comment]
I am neutral on this idea.

**Comment by Jym77** [comment]
I'm not in favour of this. We (=Siteimprove) do use the 2 weeks time to write implementations and many detailed comments that we make during Final Calls arise from precise questions that need to be solved during implementation. Cutting that down to 1 week would leave us with very little flexibility as to when to work on implementation (sometimes it's just not possible during a given week).

Additionally, given the time it takes to write a rule, I do not think that cutting 1 week out of it is going to make a huge difference in the iteration time… What need to be cut down is waiting time in the change/review/change/review cycle.

**Comment by Jym77** [comment]
Separate 1 week/2 weeks labels in place.
PR for changing template in place: #915
