### ISSUE TITLE
Don't allow "untested" for inapplicable results

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#847]
We are currently using "untested" to mean two different things:
1. The implementor hasn't looked at the test case, because it is new or it has changed
2. The implementor was unable to test the test case, for example because it was a PDF and the tester only tests HTML pages

This is problematic because we don't want an implementation to be considered "correct" if some of the inapplicable test cases weren't even looked at (scenario 1). To solve this, I propose we no longer allow "untested" as an outcome for inapplicable test cases.

Implementors should report either "inapplicable" or "cantTell" for test cases they are unable to test, instead of "untested" as for example axe-core does today for SVG pages. It is up to the implementor to decide which result is most appropriate for different scenarios. For example, known limitations could be reported as "inapplicable", and errors thrown by the engine could be reported as "cantTell".

**Comment by Jym77** [comment]
Won't "inapplicable" create a similar mix with

3. there is not applicable target in the test subject

which seems to be yet another thing.

**Comment by jkodu** [comment]
PR in place. Closing issue.
