### ISSUE TITLE
Difference in implementation outcomes by partners

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#850]
Recently when going through some incomplete implementations with RGAA (@audreymaniez), it was found out that not all implementation reports submitted would necessary agree on the expected outcome of a given test case.

**Example:**

For this [test case](https://act-rules.github.io/testcases/9eb3f6/f1b3be194f69c6f222f53cfd46cad299d94c8445.html) ACT-R expects an outcome of `inapplicable`.

But for RGAA, an `img` tag MUST have an alt attribute and if `aria-label` is present too on the `img`, then both `alt` and `aria-label` must have similar text string (or the same text string).  

Therefore RGAA fails the above test case.

**Question**
How do we streamline expected vs actual outcomes on submitted implementations?

**Comment by WilcoFiers** [comment]
I talked to Audrey about this at the F2F meeting. We concluded that we need to differentiate between implementations that have untested results and those that have inconsistent results. Proposal to have allow the implementation status to be "incomplete" and "inconsistent" (or both). This will create greater clarity about why something is missing.

**Comment by WilcoFiers** [comment]
I've opened an issue in the mapper repo. Closing this one.
