### ISSUE TITLE
Use "top-level browser context" instead of "web page"?

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#869]
As proposed by Jean-Yves:

https://github.com/act-rules/act-rules.github.io/pull/851#pullrequestreview-283011292

The HTML definition of "top-level browser context" is more precise than WCAG's "Web page" definition. It might be better to replace that definition.

**Comment by Jym77** [comment]
Would [the definition of web page worked here](https://github.com/act-rules/act-rules.github.io/blob/update-rule-links-with-identical-names-serve-equivalent-purpose-b20e66/pages/glossary/web-page.md) be a good compromise?

**Comment by EmmaJP** [comment]
Maybe something like:

An HTML web page (link to W3 definition) is the set of all fully active documents (link) which share the same top-level browsing context (link).

**Comment by WilcoFiers** [comment]
This update is in a PR. Closing the issue.
