### ISSUE TITLE
Citing HTML spec: v5.2 or WHATWG?

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#879]
There are essentially 2 versions of the HTML specs: The "stable" HTML5.2 published by W3C at https://www.w3.org/TR/html52/ and the "living standard" published by WHATWG at https://html.spec.whatwg.org/ (and redirected to by W3C from https://www.w3.org/TR/html/).

Previously, the living standard was W3C editor's draft published only at https://www.w3.org/TR/html/ but the task of writing it has been delegated to WHATWG on May 28, 2019 by this MOU: https://www.w3.org/2019/04/WHATWG-W3C-MOU.html

Many of our links were to https://www.w3.org/TR/html/ and have been updated to https://html.spec.whatwg.org/ some links are nonetheless to the stable v5.2.

---
We should decide which version to cite and keep consistency between all rules (consistency is relatively easy to enforce by tests banishing the wrong URL).

* The main drawback of citing WHATWG is that it is a living standard. Thus, it can theoretically change any day and either our link could get broken or our rules could get broken before they refer to a definition that has change and changes the meaning of the rules. Broken links are a mild annoyance, but having our rules broken by external changes is pretty bad.
* The main drawback of citing HTML5.2 is that it may drift quite a bit from the living standard and its implementations in browsers. Thus, our rules could link to a _de facto_ outdated definition and not reflect reality. We have a lot of discussion about accessible names and such about how such browser is computing it (no matter what the spec we cite says), it would be pretty bad to start adding the same kind of discussion about HTML (if browsers implement the living standard rather than v5.2).

---
Anyway, I guess this needs some discussion and decision and unification…

**Comment by Jym77** [comment]
See https://github.com/act-rules/act-rules.github.io/pull/768#discussion_r322190389 (and previous comments) for a bit of discussion on that topic.

**Comment by Jym77** [comment]
Note: links to DOM specs are also concerned.

**Comment by kasperisager** [comment]
To be frank, I don't see _any_ reason why we should continue to reference the now superseded W3C HTML and DOM specifications. All future W3C specifications will also reference the WHATWG HTML and DOM specifications per the MoU:

> For these other specifications published at WHATWG that are not parts of the WHATWG HTML and DOM specifications, the W3C will: [...] 3. prefer that normative references from W3C specifications reference the WHATWG versions.

https://www.w3.org/2019/04/WHATWG-W3C-MOU.html#transition

**Comment by jkodu** [comment]
@WilcoFiers it looks like we need your opinion on this.

**Comment by WilcoFiers** [comment]
This was discussed on the call https://www.w3.org/2019/09/12-act-r-minutes.html#item03

WHATWG has commit snapshots that we could potentially use, although they have a pretty annoying "This is a commit snapshot" banner sitting on them: https://html.spec.whatwg.org/commit-snapshots/ead4aa8ec576d7d330a04f7ec8508e336b895fdb/

**Comment by Jym77** [comment]
The "this is a commit snapshot" banner includes the sentences:
>  Do not reference this version as authoritative in any way. Instead, see https://html.spec.whatwg.org/ for the living standard.

How is us linking to it not "referencing this version as authoritative"?

**Comment by jkodu** [comment]
Have tests to catch this and all links have been updated to use whatwg. Closing issue.
