### ISSUE TITLE
Author a custom markdown linter to validate/test our rules

### ISSUE THREAD

**Issue by jkodu** [act-rules/act-rules.github.io#886]
**Problem**
Today we have a variety of unit tests authored using `jest` which seems to test a given markdown for a number of inconsistencies & thus resulting in a verbose test output which sometimes does not provide a clear message.

**Solution**
Write a custom markdown linter which wraps all of those test cases into a easier to interpret checker

**Comment by Jym77** [comment]
Would [remark](https://github.com/remarkjs/remark) be of any help for that? As in, doing all the boring parsing and building nice syntax tree for us, so we can run tests easily.

**Comment by jkodu** [comment]
We have reached an intermediate solution which uses `jest` and `markdownAST` parsed using `remark`, to enable testing of MD files.
