### ISSUE TITLE
The `gh-pages` branch has been deleted

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#911]
@jkodu The `gh-pages` branch has disappeared off the face of the earth 🤔 

![Help](https://media.giphy.com/media/gw3MYmhxEv8T52ow/giphy.gif)

**Comment by jkodu** [comment]
After debugging and several attempts to fix, finally got there. Had issues with concurrency when `rm` `node_modules` & this caused some failures.
