### ISSUE TITLE
inconsistent default text for Assumptions and Accessibility Support

### ISSUE THREAD

**Issue by nitedog** [act-rules/act-rules.github.io#932]
The default text for Assumptions and Accessibility Support varies: sometimes with italics, sometimes with full-stop at the end, and combinations thereof. It seems the template changed over time. Also the template (wrongly) does have a full-stop at the end of the text, and also needs clean-up.

Note: The two texts/sentences are written in different style editorially and could be refined in the process.

**Comment by colabottles** [comment]
Can anyone tell me where I need to be looking to find what I need to help fix this issue? Thanks.

**Comment by daniel-montalvo** [comment]
Hey @colabottles 

This refers to the text under the headings "Assumptions" and "Accessibility support" for each of the rules.


For example:

https://act-rules.github.io/rules/3e12e1#assumptions
  has a different text under that heading than
https://act-rules.github.io/rules/aaa1bf#accessibility-support

Ideally, we can harmonize how we write these paragraphs.

**Comment by colabottles** [comment]
I have yet to get to this due to a heavy workload. I won't make the earlier ACT-R calls, so just wanted to leave this here as an update.

**Comment by colabottles** [comment]
Under "Assumptions" We have:

_[There are currently no assumptions](https://act-rules.github.io/rules/3e12e1#assumptions)_ and _[No assumptions](https://act-rules.github.io/rules/3e12e1#assumptions)_

Under "Accessibility Support" there is:

"There are no major accessibility support issues known for this rule." 

[Some italicized](https://act-rules.github.io/rules/3e12e1#accessibility-support) and [some not](https://act-rules.github.io/rules/5f99a7).

I guess my next question is what are the next steps and should the text be in italics uniformly across the pages?

**Comment by daniel-montalvo** [comment]
My preference would be:

- No assumptions
- No accessibility support issues known

Not italicized

I may have some time to work on this tomorrow.
