### ISSUE TITLE
Test case files are all invalid HTML and trigger quirks mode

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#952]
The test case files listed in https://act-rules.github.io/testcases.json contain HTML fragments which are not valid HTML documents since they don't start with a DOCTYPE

>Documents must consist of the following parts, in the given order:
>Optionally, a single U+FEFF BYTE ORDER MARK (BOM) character.
>Any number of comments and ASCII whitespace.
>A DOCTYPE.

https://html.spec.whatwg.org/#writing

Apart from validity, omitting the DOCTYPE sets the example files to quirks mode. You can confirm this by typing document.compatMode at the console for the example files - it prints "BackCompat" if page is in quirks mode.

Quirks mode changes how numerous HTML/CSS/DOM features work, some of which affect accessibility. For example:

1) ID and Class selectors become case-insensitive in quirks mode:
>When matching against a document which is in quirks mode, class names must be matched ASCII case-insensitively; class selectors are otherwise case-sensitive.

https://drafts.csswg.org/selectors/#class-html

> When matching against a document which is in quirks mode, IDs must be matched ASCII case-insensitively; ID selectors are otherwise case-sensitive.

https://drafts.csswg.org/selectors/#id-selectors

2) The DOM behaves differently
> The comparisons for the classes must be done in an ASCII case-insensitive manner if root’s node document’s mode is "quirks", and in a case-sensitive manner otherwise.

https://dom.spec.whatwg.org/

3) And numerous other changes are applied as described in the Quirks Mode Standard
https://quirks.spec.whatwg.org/

4) Edit: quirks mode also applies numerous quirks mode changes specified in the HTML Standard, including how HTML is parsed and rules in the user-agent stylesheet. For example:

> Quirk: If the document has been set to quirks mode, has the same origin as the URL of the external resource, and the Content-Type metadata of the external resource is not a supported style sheet type, the user agent must instead assume it to be text/css.

https://html.spec.whatwg.org/#link-type-stylesheet

>If rowspan is zero and the table element's node document is not set to quirks mode, then let cell grows downward be true, and set rowspan to 1. Otherwise, let cell grows downward be false.

>Let document be a new Document, marked as an HTML document in quirks mode, whose content type is "text/html", origin is origin, active sandboxing flag set is sandboxFlags, feature policy is feature policy, and which is both ready for post-load tasks and completely loaded immediately.

**Comment by dd8** [comment]
Pages with no DOCTYPE are rare - they account for about 1% of the pages our free trial scans:
https://try.powermapper.com/Stats/HtmlVersions

That's probably an over-estimate since a lot of those are likely to be default error pages (404 etc)

**Comment by dd8** [comment]
Here's an example where omitting DOCTYPE affects accessibility:

1) No DOCTYPE means page is rendered in quirks mode, which means class and id selectors are case-insensitive:

```
<html lang='en'>
<head>
   <title>Test</title>
   <style>
      h1 { color: black; background-color: white; } /* contrast ratio 21.00 */
      h1.TEST { color: yellowgreen; background-color: white; } /* contrast ratio 1.88 */
   </style>
</head>
<body>
   <!-- this fails 1.4.3 Contrast (Minimum) because h1.TEST matches class="test" -->
   <h1 class="test">Test</h1>
</body>
</html>
```

2) HTML5 DOCTYPE means page is rendered in standards mode, which means class and id selectors are case-sensitive:

```
<!DOCTYPE html>
<html lang='en'>
<head>
   <title>Test</title>
   <style>
      h1 { color: black; background-color: white; } /* contrast ratio 21.00 */
      h1.TEST { color: yellowgreen; background-color: white; } /* contrast ratio 1.88 */
   </style>
</head>
<body>
   <!-- this passes 1.4.3 Contrast (Minimum) because h1.TEST does not match class="test" -->
   <h1 class="test">Test</h1>
</body>
</html>
```

**Comment by WilcoFiers** [comment]
@dd8 can you explain why having test cases in quirksmode is a problem?

**Comment by dd8** [comment]
There's a partial list of quirks mode changes here:
https://stackoverflow.com/questions/1848542/list-of-everything-that-doesnt-work-correctly-in-quirks-mode

These quirks mode features affect WCAG evaluation:
- font sizes are calculated differently - larger or smaller depending on element (which impacts SC 1.4.3, 1.4.6, 1.4.12  and probably 1.4.4/1.4.8/1.4.10)
- borders widths and colors are calculated differently (which impacts SC 1.4.11)
- box sizes are calculated are calculated differently (which impacts SC 2.5.5 and SC 1.4.10)
- HTML is parsed differently (which may impact SC 4.1.1)

There are likely other SC's affected as well. Note that some browsers also have undocumented quirks mode behaviour, so there are likely to be other hard-to-find issues.

**Comment by dd8** [comment]
Here's an example where the DOCTYPE makes the difference between a pass or fail of SC 1.4.3
1.4.3 Contrast (Minimum):

- with no DOCTYPE table cells are 12 pt with contrast ratio 3.95 : 1 which fails 1.4.3 because small text needs a minimum ratio of 4.5 : 1
- with an HTML5 DOCTYPE table cells are 20 pt with contrast ratio 3.95 : 1 which passes 1.4.3 because large scale text bigger than 18pt only needs a ratio of 3.0 : 1 

```
<html lang='en'>
<head>
   <title>Test</title>
   <style>
      body { font-size: 20pt; /* text bigger than 18pt is large scale text */ }
      td { color: rgb(128,128,128); background-color: white; /* contrast ratio 3.95 */ }
   </style>
</head>
<body>
   <!-- with DOCTYPE table cells are 20pt, with no DOCTYPE cells are 16px=12pt-->
   <table>
      <tr><th>Year</th><th>Snow Days</th></tr>
      <tr><td>2018</td><td>20</td></tr>
      <tr><td>2019</td><td>35</td></tr>
   </table>
</body>
</html> 
```

Note: quirks mode can also be triggered by some legacy DOCTYPEs:
https://html.spec.whatwg.org/multipage/parsing.html#the-initial-insertion-mode

**Comment by jkodu** [comment]
3 items to be done for this issue:
- Add `DOCTYPE` at build time to the generated examples (#75)
- Document in the test cases page about the default DOCTYPE
- Add `Open example in a new tab` link near each example

**Comment by jkodu** [comment]
For:
- Add `Open example in a new tab` link near each example 

An issue exists in ACT Web repo - https://github.com/act-rules/act-rules-web/issues/39
