### ISSUE TITLE
Expectation: "**each** test target" vs "**the** test target"

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#956]
Most rules have expectation(s) that start with "Each test target …", for example "Each test target has an accessible name".

I feel that the quantifier is plain wrong here. The way I read that (in a pure logical/formal language) is that we have an expectation that is checking something on the full set of test targets. And thus, for example, a test subject with several test targets would only pass "Each test target has an accessible name" if each individual target has an accessible name, and the subject would fail if a single test target has no accessible name. This is not correct with the fact that expectations concern individual target and the result of the rule is a set of pass/fail values (not a single one).

Once the Expectation is reached, the rule only consider a single test target at a time. Therefore I think that the correct formulation should be "**The** test target …", for example "**The** test target has an accessible name".

---
Compare to a "mathematical" rule like:
> Applicability: this rule applies to prime numbers.
> Expectation: Each target number is odd.

As such, the rule only has one outcome which is "fail" since it is false that "each prime number is odd" (because 2 is prime).
If expectation is written has "The target number is odd", then the rule will fail for 2 and pass for every other test target, which is the way we want it.

**Comment by jkodu** [comment]
Conclusion is we use `Each test target...`, given that is in the ACT rules format.

**Comment by Jym77** [comment]
Actually, the ACT rules format as a note saying (among other) (emphasis is mine):
> The expectation would then be "**The** test target (the page) has a text alternative for X% of all img elements".

and the normative part of it is (emphasis is mine):
> All expectations of an atomic rule must describe the logic that is used to determine a single passed or failed outcome for **a** test target.

So, I have to disagree that the ACT rules format is clear on that point.

**Comment by kasperisager** [comment]
I'm with @Jym77 on this; the current formulation is plain wrong and the normative sections of the ACT RF support this.

**Comment by Jym77** [comment]
The fact that "Each test target" is a quantifier is further supported by [a formulation like this](https://github.com/act-rules/act-rules.github.io/pull/832/files#diff-a038494de50fa84e9251d790f2ab8dbdR39), namely "**Each** test target [checks some condition A] except if **the** test target [checks some condition B]".

The fact that "the test target" is used the second time, together with the fact that "each test target" would make no sense at that point in the sentence (or at least would completely change the meaning) confirms that the initial "Each test target" is a quantifier over the set of all test targets.

The quantifier can be made more explicit, _e.g._ "**For each** test target, **the** test target [checks condition A], except if **the** test target [checks condition B]". I think this is a logically equivalent formulation.

On a purely logical level, a proposition which starts with a quantifier is having a single truth value per set, not one per element in the set. In that case, one single outcome per test subject (the set), not one per test target (the elements in the set).

**Comment by EmmaJP** [comment]
I like that more explicit quantifier. It brings out the individuality of the checks against the expectations while still recognising the rule is checking multiple targets within a page.

**Comment by Jym77** [comment]
My understanding of the ACT rule format:
> All expectations of an atomic rule must describe the logic that is used to determine a single passed or failed outcome for a test target.

is that this quantifier is already implicitly included in the format. _I.e._ the process of checking a rule is "for each test target, check if this test target passes the expectations; report individual result of each test target". That is why I feel that the quantifier is redundant and wrong: the expectation is only ever checked against one test target at a time.

**Comment by Jym77** [comment]
> My understanding of the ACT rule format is that this quantifier is already implicitly included in the format.

To make this a bit more precise, I understand the test procedure of an ACT rule as
> For each [test target], check whether [expectation] and report individual results.

This is supported by the fact that the expectations have to produce individual outcome for a single test target.

---
Now, if I take a (simplified) rule like "`img` element has non-empty accessible name" and try to plug that into this test procedure:
* the "the test target" formulation gives
> For each [_`img` element_], check whether [_the `img` element has non-empty accessible name_] and report individual results.

* the "each test target" formulation gives
> For each [_`img` element_], check whether [_each `img` element has non-empty accessible name_] and report individual results.

It is pretty clear that the second formulation is plain wrong both in English and as a logical statement.

---
If I want a procedure where plugging the "each test target" formulation makes sense, I could go for something like
> Consider the set of [test targets] and check whether [expectation].

However, plugging the rule into that gives
> Consider the set of [_`img` elements_] and check whether [_each `img` element has non-empty accessible name_].

This does make perfect sense in English. But on the logical level, this only has a single outcome, not one per test target. That is, if I have to test something like that, I'm going to stop at the first `img` with empty accessible name and say that the result is `false` without proceeding further.

---
Of course, things are not as simple as plugging a sentence into another one.
But these examples do illustrate why I believe that the quantification is already implied by the ACT rules format, and that the expectations are expected to work on a single test target at a time, thus using "the test target" to refer to it.

**Comment by WilcoFiers** [comment]
The decision that was made during the previous call was to open an issue with the ACT Task Force. I think that needs to happen before this is put on the agenda again.

**Comment by Jym77** [comment]
It wasn't "put on the agenda again", we just all forgot to remove the label after the previous call…

**Comment by jkodu** [comment]
@Jym77 and I discussed that we seem to have a rule design, where we say `this test target ....`, hence closing the issue.
