### ISSUE TITLE
Accessibility requirements: WCAG 2.0 or 2.1

### ISSUE THREAD

**Issue by Jym77** [act-rules/act-rules.github.io#974]
Currently, most rules cite WCAG 2.0 as accessibility requirement. The only exceptions are:
```sh
$ grep wcag21: _rules/*.md
_rules/autocomplete-valid-value-73f2c2.md:  wcag21:1.3.5: # Identify Input Purpose (AA)
_rules/css-restrict-orientation-b33eff.md:  wcag21:1.3.4: # Orientation
_rules/visible-label-in-accessible-name-2ee8b8.md:  wcag21:2.5.3: # Label in Name
```
Should we rather cite WCAG 2.1 every time?

**Comment by WilcoFiers** [comment]
Removing this from the agenda. @Jym77 this was discussed before you joined. The decision at the time was use the version number of the version where an SC was introduced. So 2.0 for all the ones in 2.0, and 2.1 only for the new ones.

**Comment by Jym77** [comment]
This should probably be mentioned in the rule design document.
@EmmaJP #946

**Comment by jkodu** [comment]
Note:
Add a test to ensure URL and text match WCAG SC.

**Comment by jkodu** [comment]
Closing this issue, with the presumption that comment - https://github.com/act-rules/act-rules.github.io/pull/946#discussion_r335422370 will be addressed.
