### ISSUE TITLE
Test foot note links for correctness

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#984]
Things like `[semantic role][]`. We need to add tests to catch if these definitions are missing.

**Comment by Jym77** [comment]
Yes, I thought I had one when I added support for the footnote links, but somehow I guess I messed up my regex or something 😞 

Hmm, looking at it, it seems I only gathered the refs and checked that the corresponding definition exists, and did not check that the internal link references an existing ref 😞 (_i.e._ I checked that if `[foo]: #foo` is used, then `foo.md` exists; but didn't check that if `[foo][]` or `[bar][foo]` exists, then `[foo]: something` also exists in the same file).

This should however be super standard markdown linting, so I kinda assume that tools for doing that already exist and we don't need to reinvent them.

Relevant code is here:
* https://github.com/act-rules/act-rules-web/blob/master/build/create-glossary-usages.js#L93-L121
* https://github.com/act-rules/act-rules-web/blob/master/utils/reg-exps.js

**Comment by jkodu** [comment]
PR in place - https://github.com/act-rules/act-rules.github.io/pull/1083
