### ISSUE TITLE
Introduce rule that checks for potential issues when non-primary language subtags don't match between `lang` and `xml:lang` attributes

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#999]

**Comment by dd8** [comment]
Here's test data on non-primary language region subtags
https://qa.powermapper.com/Tests/ACT-R/primary-ext-lang.html

* English - same voice used no matter which region is selected
* Nederlands - nl-NL and nl-BE - no real effect in VoiceOver, pronounced identically in NVDA, pronounced as English in JAWS
* Português - pt-PT and pt-BR - pronounced differently in VoiceOver,  pronounced same in JAWS/NVDA
* Cantonese - zh-HK pronounced as Cantonese in VoiceOver, Mandarin in NVDA, not read in JAWS
* Mandarin - zh-HK pronounced as Mandarin in VoiceOver, Mandarin in NVDA, not read in JAWS

In addition to Cantonese/Mandarin there may be  similar issues with pt-PT and pt-BR. European Portuguese speakers find Brazilian Portuguese easy, but some Brazilian Portuguese speakers find European Portuguese hard to understand:
https://youtu.be/wfs_PNA_R-M?t=95

**Comment by WilcoFiers** [comment]
Closing, since nobody has picked this up.
